### ISSUE TITLE
Selectable CPU scheduler

### ISSUE THREAD

**Issue by jirikivaari** [xanmod/linux#10]
Hello,

Thanks for the kernel package. I wonder if you could provide a selectable cpu scheduler. Because I don't think its easy to do perhaps provide a  branch without the CPU scheduler patches but all of them in one directory.

Do you have any information regarding performance of PDS scheduler and advantages of it over BFS?

**Comment by xanmod** [comment]
The primary CPU scheduler is not designed for multiple cpu schedulers. Alternating a process queue in the SCHED_OTHER (CFS / PDS / MuQSS / BFS) policy to another queue is not a simple task as in the case of I/O queues.

[https://github.com/xanmod/linux/blob/4.16/Documentation/scheduler/sched-PDS-mq.txt](https://github.com/xanmod/linux/blob/4.16/Documentation/scheduler/sched-PDS-mq.txt)
