### ISSUE TITLE
Bluetooth stops working at any moment

### ISSUE THREAD

**Issue by Pilleo** [xanmod/linux#101]
Hello! 
With recent xanmod kernel I am facing huge problems with bluetooth module. Not sure if it problem of xanmod or vanilla kernel.
I have a RTL8822BE 802.11a/b/g/n/ac WiFi adapter (0xB822) with integrated bluetooth, and after ubuntu loads bt works just fine and then it just stops. Switching bt off and on helps, but again it will stop working at any moment. It does not show that connection is lost, it just hangs.
No problems with current ubuntu kernel. Not sure, but i think this problem appeared with 5.9 kernel. 
Any more data I can provide?
Thank you!

**Comment by xanmod** [comment]
Please, send me your /var/log/kern.log

**Comment by Pilleo** [comment]
Please check your mail for logs

**Comment by xanmod** [comment]
Inform your distribution and version of the installed linux-firmware package.

**Comment by Pilleo** [comment]
kubuntu 20.10,
linux-firmare is 1.191

**Comment by xanmod** [comment]
Please, check with 5.9 mainline if it works normally: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.10/

**Comment by xanmod** [comment]
low-latency:

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.10/amd64/

[linux-image](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.10/amd64/linux-image-unsigned-5.9.10-050910-lowlatency_5.9.10-050910.202011221708_amd64.deb)
[linux-modules](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.10/amd64/linux-modules-5.9.10-050910-lowlatency_5.9.10-050910.202011221708_amd64.deb)

**Comment by Pilleo** [comment]
Have been using ubuntu 5.9 kernel for 2 days now. It is definitelly better, but I still had 3 freezes.
