### ISSUE TITLE
5G Wifi under 1MBps on ax200 with 5.9.xx

### ISSUE THREAD

**Issue by spxak1** [xanmod/linux#102]
Pop_OS 20.10 with 5.9.11 (and all previous xanmod 5.9.xx) on Thinkpad T460p, i7-6820hq and intel ax200.

With stock kernel 5.8.0-7630 (and all other stock) I get speeds up to 40MByte per second on my Netgear r7800  (5GHz, 160Mhz) router when copying to my server.

With Xanmod I get only up to 1MByte per second or less.

When connected to 2.4GHz I get comparable speeds regardless of the kernel.

Thank you.

**Comment by xanmod** [comment]
It seems to be the way of negotiating your wifi device under 5.9 with your router. See the behavior improving the signal and follow with wavemon monitor. Post a screenshot here for us to see.

Also check if the linux-firmware package is at version 1.192.
