### ISSUE TITLE
5.9 RT build release schedule

### ISSUE THREAD

**Issue by SicLuceatLux** [xanmod/linux#104]
HI,
first of all thx for your incredible work. 
Now my issue:
Will RT releases be not supported anymore? 

I have tried cachy on an amd 3600XT but In my case it induced some stutter once or twice in a minute. (march=znver2)

Therefore I'm still on 5.9.1 RT which works super smooth but the last release is over a month ago and chachy appears more frequently - so will the RT release swapped for cachy? 

Best regards

**Comment by xanmod** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/log/?h=linux-5.9.y-rt

No, the rt-edge branch is currently based on the linux-5.9.y-rt repository. It will probably be updated when final 5.10 is updated, rt-stable remains active.

**Comment by SicLuceatLux** [comment]
merci, for your reply.
