### ISSUE TITLE
Unable to run it on VirtualBox

### ISSUE THREAD

**Issue by Joe23232** [xanmod/linux#108]
I am unable to run VirtualBox using this kernel, other kernels work though, but not `linux-xanmod`

![image](https://user-images.githubusercontent.com/34926497/103150796-9776a380-47cb-11eb-9a21-8769848f9e73.png)

I tried to run `'/sbin/vboxconfig'` but didn't work.

I ran `yay -S virtualbox-host-dkms` on Arch-based Linux but after a reboot it did nothing. How would I solve this?

**Comment by figue** [comment]
Do you `modprobe vboxdrv`? I've been running virtual machines with VirtualBox and XanMod always.

**Comment by hamadmarri** [comment]
If you installed any new kernel you need to install vbox drivers on that kernel as @figue said.

You need to run the command shown in the error message:
`/sbin/vboxconfig` as root

**Comment by figue** [comment]
In Arch with virtualbox-host-dkms package vboxconfig is not necessary. You just need to load vboxdrv kernel module.

**Comment by Joe23232** [comment]
@figue 

> Do you `modprobe vboxdrv`? I've been running virtual machines with VirtualBox and XanMod always.

I ran your suggested command but I get this error:

```
modprobe: FATAL: Module vboxdrv not found in directory /lib/modules/5.10.2-xanmod1-1
```

@hamadmarri 

> You need to run the command shown in the error message:
/sbin/vboxconfig as root

As I mentioned in my post, I did run this as root but I get an error message:

```
sudo: /sbin/vboxconfig: command not found
```

@figue 

> You just need to load vboxdrv kernel module.

Running `modprobe vboxdrv` loads the vboxdrv kernel module, right?

**Comment by jumoog** [comment]
you can't build kernel modules with 5.10.. see https://www.virtualbox.org/ticket/20055

**Comment by Joe23232** [comment]
@jumoog

> you can't build kernel modules with 5.10.x see https://www.virtualbox.org/ticket/20055

is `5.10.x` the kernel version or the vbox kernel modules version?

**Comment by jumoog** [comment]
> 
> 
> @jumoog
> 
> > you can't build kernel modules with 5.10.x see https://www.virtualbox.org/ticket/20055
> 
> is `5.10.x` the kernel version or the vbox kernel modules version?

yes the kernel version sorry.

**Comment by Joe23232** [comment]
All good mate, and wow that kinda sucks. I hope it will be patched soon :)

**Comment by figue** [comment]
5.10 is supported:
```
figue on pluto ~ ➜  uname -a                                  
Linux pluto 5.10.3-xanmod1-1 #1 SMP PREEMPT Sat, 26 Dec 2020 18:39:34 +0000 x86_64 GNU/Linux
figue on pluto ~ ➜  lsmod | grep vboxdrv                      
vboxdrv               532480  2 vboxnetadp,vboxnetflt
figue on pluto ~ ➜  LC_ALL=C pacman -Qs virtualbox | grep dkms
local/virtualbox-host-dkms 6.1.16-4
```

**Comment by jumoog** [comment]
> 
> 
> 5.10 is supported:
> 
> ```
> figue on pluto ~ ➜  uname -a                                  
> Linux pluto 5.10.3-xanmod1-1 #1 SMP PREEMPT Sat, 26 Dec 2020 18:39:34 +0000 x86_64 GNU/Linux
> figue on pluto ~ ➜  lsmod | grep vboxdrv                      
> vboxdrv               532480  2 vboxnetadp,vboxnetflt
> figue on pluto ~ ➜  LC_ALL=C pacman -Qs virtualbox | grep dkms
> local/virtualbox-host-dkms 6.1.16-4
> ```
> 
> The dkms package automatically build the kernel module during the installation.
> 
> ```
> dkms install --no-depmod -m vboxhost -v 6.1.16_OSE -k 5.10.3-xanmod1-1
> ```

yes maybe the OSE Version

**Comment by Joe23232** [comment]
@figue 

Hey mate thank you for your suggestion.

> The dkms package automatically build the kernel module during the installation.

I have attempted to run your suggested command.

```
sudo dkms install --no-depmod -m vboxhost -v 6.1.16_OSE -k 5.10.3-xanmod1-1
```

And I am getting this error:

```
Your kernel headers for kernel 5.10.3-xanmod1-1 cannot be found at
/usr/lib/modules/5.10.3-xanmod1-1/build or /usr/lib/modules/5.10.3-xanmod1-1/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
```

I am not too sure what to do?

**Comment by figue** [comment]
I think you didn't install linux-xanmod-headers package. Without headers, you can't build external modules. If you used yay or another AUR helper, you should type: `yay -S linux-xanmod linux-xanmod-headers` and VirtualBox module should be built automatically.

**Comment by Joe23232** [comment]
I see, thanks, one last thing, do I need to reboot the system for it to take effect? I have now installed it?

**Comment by figue** [comment]
If it's the same kernel, perhaps it loads... But maybe not, and you need to reboot to load the new kernel.

**Comment by Joe23232** [comment]
I see, it seems to have resolved it, thanks :)
