### ISSUE TITLE
[FEATURE REQUEST]BBR2 

### ISSUE THREAD

**Issue by tg12** [xanmod/linux#109]
Is there any chance you can include BBR2 in the Edge or Experimental versions?

It would be great to test it as a userbase! Further reading

https://github.com/google/bbr/blob/v2alpha/README.md

https://dropbox.tech/infrastructure/evaluating-bbrv2-on-the-dropbox-edge-network

Thanks for your hard work!

**Comment by xanmod** [comment]
It will be added in the next revision if there are no conflicts with the current source.

**Comment by tg12** [comment]
Awesome! I look forward to testing that. I tried myself but I think it would be better coming from you. Will this be in your "edge" version of the kernel?

**Comment by Potterli20** [comment]
#41 ????? @xanmod

**Comment by xanmod** [comment]
bbr2 is in 5.4 base with net subsystem largely modified to mainline, tcp congestion too complex to port to 5.10 now, I believe that the base will soon be updated to 5.10 lts.

**Comment by Potterli20** [comment]
> bbr2 is in 5.4 base with net subsystem largely modified to mainline, tcp congestion too complex to port to 5.10 now, I believe that the base will soon be updated to 5.10 lts.

QUIC BBR??

**Comment by Potterli20** [comment]
> bbr2 is in 5.4 base with net subsystem largely modified to mainline, tcp congestion too complex to port to 5.10 now, I believe that the base will soon be updated to 5.10 lts.

this bbrplus https://github.com/UJX6N/bbrplus-5.9/blob/main/convert_official_linux-5.9.x_src_to_bbrplus.patch

**Comment by xanmod** [comment]
Try this build: https://dl.xanmod.org/dl/experimental/bbr2_tcp_cong/5.10.4-xanmod2/

Thanks to firelzrd
https://forum.xanmod.org/thread-4015-post-7403.html

**Comment by tg12** [comment]
For anyone else reading I had to 

`modprobe tcp_bbr2`

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/bdce8ad4d2d70bc0ce43c87565a95c3d7bf017c0/.config#L1193
