### ISSUE TITLE
XanMod kern issue

### ISSUE THREAD

**Issue by Markospoko** [xanmod/linux#11]
Hi there,

I'm attempting to get 4.14.50 Xanmod kernel running, I built linux-xanmod-lts package from [https://aur.archlinux.org/packages/linux-xanmod-lts/](https://aur.archlinux.org/packages/linux-xanmod-lts/) with makepkg after downloading snapshot but when on it the cursor in LightDM/X moves only vertically - when I move horizontally on a touchpad, when I move vertically it doesn't move at all. A previous 4.14.x version that I got via pkg manager some time ago works fine, it was happening there too however booting fallback version of that previous Xanmod and back ordinary Xanmod somehow sort of fixed it. Touchpad with fallback version of this new one also sometimes works. I'm running Manjaro Cinnamon with recent updates, nothing significant was changed to the system since fresh install, basically it's like new, using nouveau on MacBook Pro 15" Core i7 2.66 GHz mid-2010 and I'd like to be adviced how to solve it.. Please don't suggest just to rebuild, that won't do it, I'm hoping that you'll reply a bit more thoughtfully.

Muchas gracias

**Comment by xanmod** [comment]
Has the current version 4.14.55-xanmod37 solved this problem?
