### ISSUE TITLE
What is the difference between the real time kernel and non real time kernel of Xanmod?

### ISSUE THREAD

**Issue by Joe23232** [xanmod/linux#110]
What is the difference between the real time kernel and non real time kernel of Xanmod?

Which one should I use?

**Comment by rauldipeas** [comment]
`-rt` it's just for realtime applications, like music production, video editting and meteorologic calcule, or a sort of.

**Comment by Joe23232** [comment]
If I installed real time kernel without using realtime applications, would I still get a performance boost in other areas?

Are there downsides to using real time kernels over non real time kernels?

**Comment by jumoog** [comment]
https://wiki.archlinux.org/index.php/Realtime_kernel_patchset#What_is_realtime?

**Comment by Joe23232** [comment]
Thanks

**Comment by rauldipeas** [comment]
> If I installed real time kernel without using realtime applications, would I still get a performance boost in other areas?
> 
> Are there downsides to using real time kernels over non real time kernels?

No performance increase in another areas, in fact you could get a decrease with some apps, like games, in most cases.

**Comment by SicLuceatLux** [comment]
but it can increase responsiveness on the other hand (games)

**Comment by rauldipeas** [comment]
> but it can increase responsiveness on the other hand (games)

In fact, there are no responsiveness increase with `-rt` kernel for apps that no designed for it.

**Comment by SicLuceatLux** [comment]
Almost decade old discussion. 
https://www.phoronix.com/forums/forum/software/linux-gaming/30865-a-low-latency-kernel-for-linux-gaming

**Comment by cr1ogen** [comment]
The xanmod's Kernel-rt, gives a lot of xruns when I use Jack for audio production

**Comment by rauldipeas** [comment]
> The xanmod's Kernel-rt, gives a lot of xruns when I use Jack for audio production

Are you using JACK in `rt` mode? I'm getting a pretty decent performance here.

**Comment by cr1ogen** [comment]
> > The xanmod's Kernel-rt, gives a lot of xruns when I use Jack for audio production
> 
> Are you using JACK in `rt` mode? I'm getting a pretty decent performance here.

I think so. I get this message in verbose mode "JACK server starting in realtime mode with priority 95"

**Comment by rauldipeas** [comment]
> > > The xanmod's Kernel-rt, gives a lot of xruns when I use Jack for audio production
> > 
> > 
> > Are you using JACK in `rt` mode? I'm getting a pretty decent performance here.
> 
> I think so. I get this message in verbose mode "JACK server starting in realtime mode with priority 95"

If you can explain your full setup, hardware and software, maybe i can help you with this.

**Comment by Joe23232** [comment]
Are there any vulnerabilities if I use a real time kernel? If I am a typical Desktop User, how come I am recommended the standard kernel over real time kernels? What is the downsides of using real time kernels?

**Comment by rauldipeas** [comment]
> Are there any vulnerabilities if I use a real time kernel? If I am a typical Desktop User, how come I am recommended the standard kernel over real time kernels? What is the downsides of using real time kernels?

I don't know the technical details, maybe @xanmod could help with this.

I think that is something related to entropy.

**Comment by cr1ogen** [comment]
> > > > The xanmod's Kernel-rt, gives a lot of xruns when I use Jack for audio production
> > > 
> > > 
> > > Are you using JACK in `rt` mode? I'm getting a pretty decent performance here.
> > 
> > 
> > I think so. I get this message in verbose mode "JACK server starting in realtime mode with priority 95"
> 
> If you can explain your full setup, hardware and software, maybe i can help you with this.
Excuse the delay. My setup is i5-3570k, 8GB of ram memory, a 2TB HDD and a 240GB SSD, and a graphics card from Nvidia. I also have a Focusrite Scarlett 2i2 for sound. I wanted to comment that in kernels-rt compiled by me, I had no problems with xruns. And just by using qjacktl with the M.O.C music player, it gave me 5 to 6 xruns in half a minute. Thanks a lot

**Comment by ionutnechita** [comment]
Hi @Joe23232,

Kernel with Full RT, is used for Audio/Video Production or Streaming, Gaming Best Performance, Radio broadcasts, Data Analysis, Communication and Data collection with external sensors, Critical prediction systems ( meteorological or seismic calculations ), Real-time emulators, Industrial Systems.
This kernel should be used responsibly.

For best performance, a kernel with medium preemption will provide the best ratio for multiple scenarios. ( low-latency or voluntary preempt ).

All the best.

**Comment by rauldipeas** [comment]
> Hi @Joe23232,
> 
> Kernel with Full RT, is used for Audio/Video Production or Streaming, Gaming Best Performance, Radio broadcasts, Data Analysis, Communication and Data collection with external sensors, Critical prediction systems ( meteorological or seismic calculations ), Real-time emulators, Industrial Systems.
> This kernel should be used responsibly.
> 
> For best performance, a kernel with medium preemption will provide the best ratio for multiple scenarios. ( low-latency or voluntary preempt ).
> 
> All the best.

Exclude _Gaming Best Performance_ from this list, it's not accurate enough.

**Comment by lilianmoraru** [comment]
@Joe23232 If you are not sure what RT kernel does, then most probably you don't need it.

> If I am a typical Desktop User

You definitely don't need RT kernel(besides some DKMS modules not working with it). It won't improve your general performance(when comparing with the normal Linux Xanmod Kernel) - most likely that it will degrade it, for your use-case.
It could theoretically improve the performance of some games but that depends a lot on the game and most probably the performance will degrade.
You are sacrificing throughput for responsiveness. That makes sense for music production where you have multiple channels and you can't have delays in the audio(every ring-buffer gets small chunks of attention time) but that does not mean "it's more performant", it's a very specific use case.

> This kernel should be used responsibly.

"responsibly" - there is no "risk" with an RT kernel, does not have to do with using it "responsibly".
You either have a specific use-case or not, it does not involve a "risk".

**Comment by Joe23232** [comment]
I see, thanks guys :)
