### ISSUE TITLE
Latest CacULE fix

### ISSUE THREAD

**Issue by raykzhao** [xanmod/linux#112]
Hi @xanmod 

The latest CacULE scheduler has a starvation fix here: hamadmarri/linux@63764f2764f2a2f48414b3ea4dcc2013b74c65b3. Also the author suggested to disable the `FAIR_GROUP_SCHED` (and therefore `SCHED_AUTOGROUP`), see the discussions at hamadmarri/cacule-cpu-scheduler#15.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/compare/5.10.3-xanmod1-cacule...5.10.3-xanmod3-cacule
