### ISSUE TITLE
Why is use_ns=n the default?

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#113]
I tested latest xanmod kernel on Arch Linux. The `use_ns` default in PKGBUILD is `use_ns=n`.

Setting `use_ns=n` as default breaks the evolution email client. Evoltuion is not able to display the emails and gives the following error message:

`bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.`

Is there any particular reason for not using `use_ns=y` as the default?

**Comment by figue** [comment]
In Arch Linux all XanMod patches offer to enable this as you mention, setting use_ns=y you can avoid Evolution and Brave, for example, to fail.

I don't remember if this was discussed in the past, but the patch we apply in Arch Linux is [here](https://aur.archlinux.org/cgit/aur.git/tree/0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-CLONE_NEWUSER.patch?h=linux-xanmod)

**Comment by mabod** [comment]
I know how to customize the xanmod package build to fix this.
But my question was why a default was chosen which breaks important apps. There must be a reason.

**Comment by figue** [comment]
Upstream doesn't have this patch, so I respect that in PKGBUILD (upstream default, you know). I imagine you post this issue to request directly upstream to include the patch. Right?

**Comment by paulmenzel** [comment]
It was disabled in Debian until linux (5.10.1-1~exp1) [release in mid-December 2020](https://metadata.ftp-master.debian.org/changelogs//main/l/linux-signed-amd64/linux-signed-amd64_5.10.4+1_changelog). [Debian bug report #898446)[https://bugs.debian.org/898446] contains more information, but basically it was disabled due to frequent security issues in the past.

**Comment by mabod** [comment]
That is interesting. So how is the evolution email client running on debian then? Did they patch it to work with use_ns=n?
