### ISSUE TITLE
Disable tracers and minimal debug in binaries for Debian GNU/Linux

### ISSUE THREAD

**Issue by BigmenPixel0** [xanmod/linux#114]
Hello! Please turn off tracers by default in binaries for Debian GNU/Linux and make minimal debug, like in Liquorix kernel.

And very big thanks for LTS kernel, this fine for my server ;)

**Comment by paulmenzel** [comment]
Can you elaborate a little, what the downside of enabling tracers is? To my knowledge you can disable (blacklist) the tracer init function on the Linux kernel command line.

If you could list the Kconfig option names, that would be also great.

**Comment by BigmenPixel0** [comment]
> Can you elaborate a little, what the downside of enabling tracers is? To my knowledge you can disable (blacklist) the tracer init function on the Linux kernel command line.
> 
> If you could list the Kconfig option names, that would be also great.

Disable tracers good for perfomance. Tracers in config:
![Снимок экрана от 2021-01-05 13-50-07](https://user-images.githubusercontent.com/73637218/103625597-1ccc2780-4f33-11eb-8647-99a0a9e61c9c.png)

**Comment by paulmenzel** [comment]
Do you have concrete numbers? I have not heard, they have an effect on performance, especially when not being used.

Also, they are nice to have for debugging. People not wanting them should blacklist the init function on the Linux kernel line.

**Comment by BigmenPixel0** [comment]
> Do you have concrete numbers? I have not heard, they have an effect on performance, especially when not being used.
> 
> Also, they are nice to have for debugging. People not wanting them should blacklist the init function on the Linux kernel line.

Okay. How then can I disable them through kernel parameters?

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/bdce8ad4d2d70bc0ce43c87565a95c3d7bf017c0/.config#L10806

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/bdce8ad4d2d70bc0ce43c87565a95c3d7bf017c0/.config#L10806

I didn't find any problems when disabling in the current versions, so I'm considering it.

**Comment by paulmenzel** [comment]
I still do not understand, why you disable a feature without any hard data that performance is improved by it? Actually, you can’t use certain tools, like [perf-tools](https://github.com/brendangregg/perf-tools) now.

The only downside of having ftrace built into the Linux kernel is, up to 30 ms added to the startup time. As written above, Linux allows to blacklist certain init functions. `initcall_blacklist=ftrace_init` should have done the trick here..
