### ISSUE TITLE
xanmod-lts wireguard-dkms

### ISSUE THREAD

**Issue by bcookatpcsd** [xanmod/linux#116]
Not sure what I might be doing wrong.. but I'm not an ubuntu user, just helping someone who is new to linux.. and they want to use ubuntu with the lts xanmod.. 

root@dl3400-lnx:/usr/lib/modules/5.4.87-xanmod1# apt install wireguard-dkms 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  wireguard
The following NEW packages will be installed:
  wireguard wireguard-dkms
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 258 kB of archives.
After this operation, 1,779 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 wireguard-dkms all 1.0.20201112-1~20.04.1 [254 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 wireguard all 1.0.20200513-1~20.04.2 [3,264 B]
Fetched 258 kB in 1s (217 kB/s)      
Selecting previously unselected package wireguard-dkms.
(Reading database ... 164445 files and directories currently installed.)
Preparing to unpack .../wireguard-dkms_1.0.20201112-1~20.04.1_all.deb ...
Unpacking wireguard-dkms (1.0.20201112-1~20.04.1) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../wireguard_1.0.20200513-1~20.04.2_all.deb ...
Unpacking wireguard (1.0.20200513-1~20.04.2) ...
Setting up wireguard-dkms (1.0.20201112-1~20.04.1) ...
Loading new wireguard-1.0.20201112 DKMS files...
Building for 5.4.87-xanmod1
Building initial module for 5.4.87-xanmod1
Secure Boot not enabled on this system.
Done.

wireguard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.87-xanmod1/updates/dkms/

depmod...

DKMS: install completed.
Setting up wireguard (1.0.20200513-1~20.04.2) ...
root@dl3400-lnx:/usr/lib/modules/5.4.87-xanmod1# cd updates/dkms/
root@dl3400-lnx:/usr/lib/modules/5.4.87-xanmod1/updates/dkms# ls
wireguard.ko

(great, looks like it built)

root@dl3400-lnx:/usr/lib/modules/5.4.87-xanmod1/updates/dkms# insmod wireguard.ko 
insmod: ERROR: could not insert module wireguard.ko: Unknown symbol in module

(dmesg | grep wireguard)
 6572.027774] wireguard: Unknown symbol udp_sock_create4 (err -2)
[ 6572.027791] wireguard: Unknown symbol udp_tunnel6_xmit_skb (err -2)
[ 6572.027838] wireguard: Unknown symbol udp_tunnel_sock_release (err -2)
[ 6572.027851] wireguard: Unknown symbol setup_udp_tunnel_sock (err -2)
[ 6572.027859] wireguard: Unknown symbol udp_sock_create6 (err -2)
[ 6572.027879] wireguard: Unknown symbol udp_tunnel_xmit_skb (err -2)

Any suggestions on what I could do to get them a working wireguard module with xanmod-lts?

Thanks in advance for any suggestions..

**Comment by BigmenPixel0** [comment]
Yes! linux-xanmod-lts with wireguard module will awesome

**Comment by bcookatpcsd** [comment]
Thanks for the reply 

How would I add WireGuard to the LTS kernel if not with dkms..

Thanks in advance

**Comment by mjeveritt** [comment]
@zx2c4 the author of Wireguard might be able to shed some light here (apologies for random ping, Jason!) :smiley:
