### ISSUE TITLE
xanmod patch set

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#118]
I want to compare the patch sets of some kernels to better understand how similar / different they are.

For most kernels I can find those patch sets but for xanmod I only find one big patch file (e.g. patch-5.10.6-xanmod1.xz). And the PKGBUILD on arch Linux is pulling in just this one patch file. This makes it hard to compare the xanmod kernel with e.g. vanilla arch, Manjaro, etc.

How is the xanmod patch file created? Can I see somewhere which individual patches are pulled in?

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/releases/tag/5.10.6-xanmod1

**Comment by mabod** [comment]
No, this is not it. The page you share here is basically listing the vanilla kernel patches similar to what is provided here: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.6

The only difference are the first three entries:

```
f3196f4 Linux 5.10.6-xanmod1
e5ce351 Merge tag 'v5.10.6' into 5.10
5650152 Linux 5.10.6
```

Where "Merge tag 'v5.10.6' into 5.10" seems to be the xnamod patch. But it is just one patch file with no further information where the patches are coming from.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/releases/tag/5.10.1-xanmod1
