### ISSUE TITLE
WARNING: cpupower not found for kernel 5.10.12-xanmod1

### ISSUE THREAD

**Issue by GHM-0** [xanmod/linux#121]
Does cpupower had any change? Or thats only hanpping to me?

I'm using  5.10.12-xanmod1-cacule and 5.10.12-xanmod1

I coul no more set :

sudo cpupower frequency-set --governor powersave
WARNING: cpupower not found for kernel 5.10.12-xanmod1

  You may need to install the following packages for this specific kernel:
    linux-tools-5.10.12-xanmod1-cacule
    linux-cloud-tools-5.10.12-xanmod1-cacule

  You may also want to install one of the following packages to keep up to date:
    linux-tools-cacule
    linux-cloud-tools-cacule

Those packages doesn't seems to exists in apt repository (I'm using ubuntu 20.10)?

apt E: Couldn't find any package by glob 'linux-tools-5.10.12-xanmod1-cacule'

Should I recompile the kernel?

**Comment by xanmod** [comment]
Install the linux-cpupower package from the repository.

`sudo apt purge linux-tools-common --auto-remove --purge && sudo apt install linux-cpupower`
