### ISSUE TITLE
Add CONFIG_KERNEL_ZSTD=y

### ISSUE THREAD

**Issue by figue** [xanmod/linux#127]
Soon, Archlinux will use zstd compression by default to build the default initramfs images.

Can we enable CONFIG_KERNEL_ZSTD by default? If for some reason we can't, I'll add directly to the Arch's package.

https://github.com/xanmod/linux/blob/5.11/.config#L40

Thanks.

**Comment by HougeLangley** [comment]
I think it could be used by default. I used this one in gentoo ebuild.

**Comment by xanmod** [comment]
You can without problems, the default of xanmod is lz4 for the maximum decompression speed available for the vmlinuz image, with zstd it will be comparable to lzo in performance and better compression than gzip/deflate. With lz4, the image size is ~12 MB and zstd ~9 MB. For a typical 64-bit desktop it makes no difference, it would have only few benefits for a limited /boot space.

**Comment by figue** [comment]
I'm sorry if I didn't explain myself well, I want it in the project, not only for Arch. That's why I asked here.

**Comment by xanmod** [comment]
I apologize for not concluding in the comment.

I prefer to keep lz4 by default. In a very poor test PC here (AMD C-60) the decompression time of vmlinuz with lz4 is noticeable in relation to zstd.

**Comment by figue** [comment]
Sorry, I'll close this issue, I thought CONFIG_KERNEL_ZSTD was needed to boot with a zstd image but I've tried now in a laptop and it works with the current config.

**Comment by xanmod** [comment]
I updated the ZSTD libraries of the kernel and with general performance optimization. On old / poor hardware, the decompression time of vmlinuz is closer to lz4, now it makes sense to use KERNEL_ZSTD=y.
https://github.com/xanmod/linux/releases/tag/5.11.8-xanmod2

**Comment by xanmod** [comment]
I updated the ZSTD libraries of the kernel. On old / poor hardware, the decompression time of vmlinuz is closer to lz4, now it makes sense to use KERNEL_ZSTD=y.
https://lwn.net/Articles/838875/
https://github.com/xanmod/linux/releases/tag/5.11.8-xanmod2

**Comment by figue** [comment]
I saw it, for me it's OK. Tested in Arch, and it goes well.
