### ISSUE TITLE
Future of CaCULE?

### ISSUE THREAD

**Issue by xuanruiqi** [xanmod/linux#128]
Hamad, the author of CaCULE, said that he [isn't working on CaCULE at the moment](https://github.com/hamadmarri/cacule-cpu-scheduler/issues/21), so I guess no official patch for 5.11 at the moment. I wonder what's the plan for 5.11-cacule, as we probably don't want to stay on 5.10 forever. 

There are reports of successfully running the 5.10 patch on 5.11 with some modifications, so maybe we can port the patch over to 5.11 as-is. I would love to help with this. Maybe we could just drop CaCULE for the moment too.

**Comment by figue** [comment]
I think the author wants to wait a bit, until 5.11 branch is "more stable", but I think he will maintain CaCULE for now.

**Comment by xuanruiqi** [comment]
I don't think Hamad is dropping CaCULE, but it seems that he is busy finding a job and 5.11-cacule might be delayed. FWIW, I have switched to the non-CaCULE branch at the moment, but when 5.11-cacule is released I'll be switching back.

**Comment by xuanruiqi** [comment]
I saw the cacule branch got an update so this issue is outdated :-D Thanks for the work!!!
