### ISSUE TITLE
booting with secureboot does not work in the hyper-v virtual machine

### ISSUE THREAD

**Issue by ionutnechita** [xanmod/linux#129]
Hi Alexandre Frade,

I try to install CacULE Xanmod kernel in Hyper-V Debian VM.
But it doesn't seem to boot through Secure Boot.
Do I have to do the signing part?

I encounter this error:
![image](https://user-images.githubusercontent.com/9405900/109427420-04403100-79fb-11eb-8667-7d0235297887.png)

Do you know what it can be?

OS: Windows 10 Enterprise 1909
VM: Gen2 UEFI Debian - Microsoft UEFI Certificate Authority

Thanks.

**Comment by jumoog** [comment]
The Kernel isn't signed or not signed with a know key
