### ISSUE TITLE
sporadic double-time effect on kernel startup in loader stage

### ISSUE THREAD

**Issue by ionutnechita** [xanmod/linux#130]
Hi Alexandre Frade,

I noticed a while more boot time after a few resets.

Xanmod CACULE - 1 CPU - 5.11.1-xanmod2-cacule #0~git20210225.68991f7
Startup finished in 303ms (firmware) + **_6.810s (loader)_** + 2.459s (kernel) + 5.337s (userspace) = 14.909s
graphical.target reached after 5.289s in userspace
Startup finished in 200ms (firmware) + 2.166s (loader) + 2.476s (kernel) + 5.834s (userspace) = 10.678s
graphical.target reached after 5.800s in userspace
Startup finished in 246ms (firmware) + 3.352s (loader) + 2.560s (kernel) + 6.955s (userspace) = 13.115s
graphical.target reached after 6.871s in userspace
Startup finished in 173ms (firmware) + 6.644s (loader) + 2.539s (kernel) + 5.567s (userspace) = 14.925s
graphical.target reached after 5.525s in userspace
Startup finished in 170ms (firmware) + 6.566s (loader) + 2.627s (kernel) + 6.153s (userspace) = 15.517s
graphical.target reached after 6.101s in userspace
Startup finished in 207ms (firmware) + 3.407s (loader) + 2.499s (kernel) + 6.034s (userspace) = 12.149s
graphical.target reached after 5.990s in userspace
Startup finished in 233ms (firmware) + 2.286s (loader) + 2.422s (kernel) + 5.252s (userspace) = 10.195s
graphical.target reached after 5.215s in userspace
Startup finished in 180ms (firmware) + 3.070s (loader) + 2.505s (kernel) + 6.067s (userspace) = 11.824s
graphical.target reached after 6.022s in userspace
Startup finished in 185ms (firmware) + 4.644s (loader) + 2.411s (kernel) + 5.560s (userspace) = 12.801s
graphical.target reached after 5.511s in userspace
Startup finished in 212ms (firmware) + 6.658s (loader) + 2.600s (kernel) + 5.988s (userspace) = 15.459s
graphical.target reached after 5.950s in userspace

Normal Debian Kernel - 1 CPU -  5.9.1-1 - 5.9.0-1-amd64
Startup finished in 215ms (firmware) + 2.999s (loader) + 3.059s (kernel) + 6.614s (userspace) = 12.888s
graphical.target reached after 6.325s in userspace
Startup finished in 196ms (firmware) + 3.356s (loader) + 3.066s (kernel) + 6.692s (userspace) = 13.312s
graphical.target reached after 6.646s in userspace
Startup finished in 354ms (firmware) + 3.004s (loader) + 3.054s (kernel) + 6.881s (userspace) = 13.295s
graphical.target reached after 6.832s in userspace
Startup finished in 218ms (firmware) + 3.336s (loader) + 3.079s (kernel) + 7.011s (userspace) = 13.646s
graphical.target reached after 6.965s in userspace
Startup finished in 306ms (firmware) + 3.525s (loader) + 3.174s (kernel) + 6.987s (userspace) = 13.993s
graphical.target reached after 6.943s in userspace
Startup finished in 271ms (firmware) + 3.061s (loader) + 3.196s (kernel) + 7.726s (userspace) = 14.255s
graphical.target reached after 7.467s in userspace
Startup finished in 213ms (firmware) + 2.917s (loader) + 3.015s (kernel) + 6.491s (userspace) = 12.638s
graphical.target reached after 6.450s in userspace
Startup finished in 188ms (firmware) + 3.537s (loader) + 3.000s (kernel) + 6.407s (userspace) = 13.135s
graphical.target reached after 6.360s in userspace
Startup finished in 204ms (firmware) + 2.723s (loader) + 2.975s (kernel) + 6.972s (userspace) = 12.875s
graphical.target reached after 6.928s in userspace
Startup finished in 192ms (firmware) + 3.407s (loader) + 3.094s (kernel) + 6.851s (userspace) = 13.545s
graphical.target reached after 6.805s in userspace

Have you seen anything like this before?

OS VM: Debian 11 Unstable

lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          1
On-line CPU(s) list:             0
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
Stepping:                        12
CPU MHz:                         2112.007
BogoMIPS:                        4224.01
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Mitigation; TSX disabled
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdts
                                 cp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx
                                 f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 smep b
                                 mi2 erms invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities

Linux debian-test 5.11.1-xanmod2-cacule #0~git20210225.68991f7 SMP PREEMPT Thu Feb 25 19:16:09 UTC 2021 x86_64 GNU/Linux

**Comment by xanmod** [comment]
Does this issue persist?
