### ISSUE TITLE
build/vmlinux is very large?

### ISSUE THREAD

**Issue by xuanruiqi** [xanmod/linux#131]
I find the interesting phenomenon that:

```
xuanrui@xuanrui-desktop:~ % du -sh /usr/lib/modules/*
805M	/usr/lib/modules/5.11.1-xanmod2-cacule-2-cacule
272M	/usr/lib/modules/5.11.2-arch1-1
```

The modules directory of XanMod is about 3 times as large as the one for the stock Arch Linux kernel.

It seems that the reason is:

```
xuanrui@xuanrui-desktop:~ % du -sh /usr/lib/modules/5.11.1-xanmod2-cacule-2-cacule/build/vmlinux
624M	/usr/lib/modules/5.11.1-xanmod2-cacule-2-cacule/build/vmlinux
xuanrui@xuanrui-desktop:~ % du -sh /usr/lib/modules/5.11.2-arch1-1/build/vmlinux                
69M	/usr/lib/modules/5.11.2-arch1-1/build/vmlinux
```

However:
```
xuanrui@xuanrui-desktop:~ % du -sh /boot/vmlinuz-*                              
9.0M	/boot/vmlinuz-linux
7.0M	/boot/vmlinuz-linux-xanmod-cacule
```

The end vmlinuz is actually smaller! What could be the reason for that? It's not a bug, but it's quite interesting, and it would be good if I could make the folder smaller.

FWIW, this issue seems XanMod-specific. I don't seem to have this problem with other self-compiled kernels. Is this an option in the config causing all this, or is it a XanMod patch?

I have suspected the problem is -O3, but it doesn't seem so because switching to -O2 didn't make it visibly smaller either.

**Comment by figue** [comment]
I was comparing both PKGBUILD and I think I found it:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/linux&id=7398961ba1f96e302ee0977895f6b53babf67a52#n166

Arch seems to strip the image at the end. I'm merging it and make a build test.

**Comment by xuanruiqi** [comment]
I think you've found it:

```
xuanrui@xuanrui-desktop:~ % ls -alh vmlinux                                  
-rw-r--r-- 1 xuanrui xuanrui 641M  3月  3 07:25 vmlinux
xuanrui@xuanrui-desktop:~ % strip -v vmlinux                 
copy from `vmlinux' [elf64-x86-64] to `stS0bwQs' [elf64-x86-64]
xuanrui@xuanrui-desktop:~ % ls -alh vmlinux
-rw-r--r-- 1 xuanrui xuanrui 41M  3月  3 07:25 vmlinux
```

After stripping the binary, it's even smaller than:
```
xuanrui@xuanrui-desktop:~ % ls -alh /usr/lib/modules/5.11.2-arch1-1/build/vmlinux  
-rw-r--r-- 1 root root 77M  2月 27 03:26 /usr/lib/modules/5.11.2-arch1-1/build/vmlinux
```

**Comment by xuanruiqi** [comment]
Solution: add the stripping to XanMod PKGBUILD?

**Comment by figue** [comment]
> Solution: add the stripping to XanMod PKGBUILD?

Yes, it's already updated.
