### ISSUE TITLE
How to optimise Xanmod for a specific CPU using a development environment. 

### ISSUE THREAD

**Issue by TJ101** [xanmod/linux#132]
Dear all,
 
I’ve been trying to setup a development environment for compiling Xanmod Kernels.

I would like to use the compile native option of GCC to optimise my build, but can’t use the latest version of GCC and binutils with my current Debian build. 

I also don't have enough free storage on my router to compile everything.
 
I’ve therefore setup Ubuntu with GCC 10.2 and Binutils 2.35 on a development box.

Does anyone know how I can specifically build my Xanmod Kernels for my target router CPU environment?

I’ve found the following useful commands to run on my target router.
gcc -march=native -dM -E - </dev/null

This exports all the available features from the target router environment.

If I run gcc -march=native -Q --help=target|grep march

I get skylake-avx512

If I run cat /sys/devices/cpu/caps/pmu_name

I get skylake

Do I just set gcc -march= skylake-avx512 on my development box?

Any thoughts on how to get the best possible optimised compile for my target router is very much appreciated.

**Comment by hamadmarri** [comment]
You are probably looking for cross-compiling.

See this:
https://wiki.osdev.org/GCC_Cross-Compiler
https://landley.net/writing/docs/cross-compiling.html
https://www6.software.ibm.com/developerworks/education/l-cross/l-cross-ltr.pdf

It is not an easy task.
Good luck.

**Comment by figue** [comment]
If you want to optimize by CPU microarchitecture, you can patch kernel config. Disable CONFIG_GENERIC_CPU and enable CONFIG_MSKYLAKEX or CONFIG_MNATIVE.
