### ISSUE TITLE
Is there a compiled version on the AUR?

### ISSUE THREAD

**Issue by Joe23232** [xanmod/linux#133]
Hi, by any chance I was wondering if there a compiled binary version in the AUR?

**Comment by figue** [comment]
The only repo I know is packaging and shipping AUR binaries is Chaotic:

https://aur.chaotic.cx/

**Comment by arthurflor23** [comment]
Hi, is there a possibility to provide a compiled bin version?

I ask this because I have been using xanmod for some time now (really wonderful), and it take 1h42min to compile (all threads enabled and with i7 7th).. then I think twice before updating weekly with new patches (:/).

Anyway, I'll see the best way to update here.
Good job and success to you guys!

**Comment by figue** [comment]
Long time ago, I used OBS (Opensuse Build Service) to trigger all kernel compilations. Now I simply build for myself with _localmodcfg=y so build time is less than 20 minutes in my old laptop.

I don't know if there is an official build machine that we can use for this @xanmod

**Comment by figue** [comment]
I was playing with OBS after some time. For now the packages are only for testing purposes. To use the repo add this to your pacman.conf, import the key and install as usual.
```
[home_ffigue_Arch]
SigLevel = Optional TrustAll
Server = https://download.opensuse.org/repositories/home:/ffigue/Arch/$arch
```
```
curl -s "https://download.opensuse.org/repositories/home:/ffigue/Arch/x86_64/home_ffigue_Arch.key" | pacman-key --add -
pacman-key --lsign-key 252F52439C20FA87AE0E78E3F5AAC5A5424ED5CA
```

**Comment by AndreVuillemot160** [comment]
> I was playing with OBS after some time. For now the packages are only for testing purposes. To use the repo add this to your pacman.conf, import the key and install as usual.
> 
> ```
> [home_ffigue_Arch]
> SigLevel = Optional TrustAll
> Server = https://download.opensuse.org/repositories/home:/ffigue/Arch/$arch
> ```
> 
> ```
> curl -s "https://download.opensuse.org/repositories/home:/ffigue/Arch/x86_64/home_ffigue_Arch.key" | pacman-key --add -
> pacman-key --lsign-key 252F52439C20FA87AE0E78E3F5AAC5A5424ED5CA
> ```

Hey, maybe add headers to dependencies to kernel?
Like `linux-xanmod and linux-xanmod-headers`

**Comment by figue** [comment]
@AndreVuillemot160 headers are not a dependency of the kernel package itself. Compare with the rest of the kernel packages.

**Comment by mmetak** [comment]
@figue  Why are you building headers package separately in OBS?

**Comment by figue** [comment]
> @figue Why are you building headers package separately in OBS?

OBS don't handle PKGBUILD with multiple packages, so it needs to be compiled separately.

**Comment by mmetak** [comment]
Yes they do. Here's my page. https://build.opensuse.org/project/show/home:metakcahura:kernel
