### ISSUE TITLE
5.4-rt branch - update to 5.4.109-rt56

### ISSUE THREAD

**Issue by mjeveritt** [xanmod/linux#136]
Upstream released 5.4.109-rt56 on 17.04.2021 - https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.4/

Any chance of getting merge and new release?
TIA

**Comment by mjeveritt** [comment]
> Upstream released 5.4.109-rt56 on 17.04.2021 - https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.4/
> 
> Any chance of getting merge and new release?
> TIA

Failing that, assuming the update process isn't too complicated, I may be able to co-maintain and push updates to the main repo.

**Comment by xanmod** [comment]
Are you having problems with 5.10-rt?

**Comment by xanmod** [comment]
the latest 5.10-rt version has improved performance, probably better than 5.4-rt now

**Comment by mjeveritt** [comment]
> the latest 5.10-rt version has improved performance, probably better than 5.4-rt now

Do you have some metrics on this, or commentary from upstream?

**Comment by mjeveritt** [comment]
I'll take care of this myself. Closing.
