### ISSUE TITLE
Touchpad issue

### ISSUE THREAD

**Issue by Hergeirs** [xanmod/linux#138]
I was trying this out, and really enjoyed the responsiveness under heavy load, but was stumped by a weird issue.
My touchpad seems to use a higher lower sensitivity than on the main archlinux kernel.
I have a hard time believing this a kernel issue, as I've not seen this issue with other kernels.
Please educate me if I'm wrong and this is not an issue with linux-xanmod specifically.

I know this seems weird, but the only difference between when the touchpad sensitivity is off on my system is the kernel.

System info pasted from `neofetch`

```
OS: Arch Linux x86_64
Host: XPS 15 7590
Kernel: 5.12.0-xanmod1-2
Shell: zsh 5.8
Resolution: 3840x2160
DE: GNOME
WM: Mutter
WM Theme: Adwaita
CPU: Intel i7-9750H (12) @ 2.600GHz
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
GPU: Intel UHD Graphics 630
Memory: 1566MiB / 15633MiB
```

If you need anything else I'll try to give it to you as quickly as I'm able.

**Comment by xanmod** [comment]
It could be that in kernel 5.12 there was some change in the module that controls the sensitivity of your touchpad. I need more information to investigate.

Send information about your hardware and modules loaded with the commands:

`sudo lshw > lshw.log && lsmod > lsmod.log`

Send here the lshw.log and lsmod.log files

**Comment by Hergeirs** [comment]
I have attached the output below :)
[lshw.log](https://github.com/xanmod/linux/files/6408494/lshw.log)
[lsmod.log](https://github.com/xanmod/linux/files/6408495/lsmod.log)

**Comment by xanmod** [comment]
I didn't find any direct changes in the synaptics touchpad / hid modules on Dell hardware, there may also be some changes with the xinput / ibus driver that change the behavior with the 5.12 kernel. Archlinux will soon release the 5.12 kernel in the main repository for confirmation.

https://kernelnewbies.org/Linux_5.12#Tablets.2C_touch_screens.2C_keyboards.2C_mouses
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=69aea9d2843669387d100e353b5113d1adc9502f

**Comment by Hergeirs** [comment]
I built the linux-mainline kernel (5.12.0-1-mainline) and indeed do see the same behaviour. 
It seems very odd. Might this be a part of `reenable touchpad control` under `platform -> ideapad-laptop` ?
Even though this is not a Lenovo.... I however have no idea what else it could be.
I'll try to glance through the commits.

Sorry about using your time unnecessarily.

**Comment by Hergeirs** [comment]
Now kernel 5.12 hit arch and very confusingly it does not show the same behavior as the mainline did. No problem on it what so ever.

**Comment by Hergeirs** [comment]
The issue has disappeared. Now all touchpad behaviour is consistent between linux-mainline and linux-xanmod as far as I can determine.

Sorry about my tardiness. Because of some very basic kernel programming assignment I felt safer using the mainline lately.
