### ISSUE TITLE
Phylib can be built as a module

### ISSUE THREAD

**Issue by solbjorn** [xanmod/linux#141]
`CONFIG_ETHTOOL_NETLINK` was requiring `CONFIG_PHYLIB` to be built-in in Linux 5.8, but since 5.9 it's possible again to build Phylib as a module and have Ethtool Netlink interface.

So please consider the following changes to the dotconfigs:

```
CONFIG_PHYLIB=m
CONFIG_FIXED_PHY=m
CONFIG_BCM84881_PHY=m
CONFIG_MDIO_DEVICE=m
CONFIG_MDIO_BUS=m
CONFIG_MDIO_DEVRES=m
```

(they are all `=y` as of now)

**Comment by xanmod** [comment]
For Debian? Is there a issue with this current configuration?

**Comment by xanmod** [comment]
I keep the default configuration closest to the most recent release distributions.

Ubuntu and Fedora also use =y by default, there must be some reason.
