### ISSUE TITLE
Module compression by default?

### ISSUE THREAD

**Issue by solbjorn** [xanmod/linux#142]
Lots of distros and custom kernels enable `CONFIG_MODULE_COMPRESS` by default and, in most cases, choose ZSTD as a module compression algo.

Shouldn't it be done for the default Xanmod configurations as well?
Thanks.

**Comment by xanmod** [comment]
If I'm not mistaken, initramfs and init systems need to have support for zstd, most distributions do not yet have these newer components

**Comment by solbjorn** [comment]
Ah, I see, sure.
