### ISSUE TITLE
virtualbox-dkms not supported, help pls

### ISSUE THREAD

**Issue by diiegg** [xanmod/linux#149]
I wanted to use a virtual machine and I got this error, any help I'm running  an Ubuntu focal

`Loading new virtualbox-6.1.16 DKMS files...
Building for 5.12.3-xanmod2
Building initial module for 5.12.3-xanmod2
ERROR (dkms apport): kernel package linux-headers-5.12.3-xanmod2 is not supported
Error! Bad return status for module build on kernel: 5.12.3-xanmod2 (x86_64)
Consult /var/lib/dkms/virtualbox/6.1.16/build/make.log for more information.
dpkg: error processing package virtualbox-dkms (--configure):
installed virtualbox-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
virtualbox-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by xanmod** [comment]
https://www.virtualbox.org/wiki/Linux_Downloads
