### ISSUE TITLE
amdgpu freeze with LRU Framework

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#153]
I just reported a system freeze with the 5.12 ZEN kernel. And this freeze seems to be caused by the LTU framework. 
I see the same freezes with the 5.12 xanmod kernel.

This is about a freeze of amdgpu when the PC is idle for a few minutes. Please see the details here:

 https://github.com/zen-kernel/zen-kernel/issues/213

**Comment by ms178** [comment]
Just to keep this thread updated, the op posted the following comment in the linked thread https://github.com/zen-kernel/zen-kernel/issues/213#issuecomment-855888810, and the problem did turn out to be an AMDGPU problem, not a LRU Framework problem.

**Comment by mabod** [comment]
Yes. It looks like to be more complex and not related to LRU. I will  close this issue for now.
