### ISSUE TITLE
linux-image-5.12.9-xanmod1-edge: subprocess installed package linux-image-5.12.9-xanmod1-edge post-installation script returned error code 1

### ISSUE THREAD

**Issue by TomaszMyszak** [xanmod/linux#157]
Hello, 

anyone have solutions for this issue:

linux-image-5.12.9-xanmod1-edge: subprocess installed package linux-image-5.12.9-xanmod1-edge post-installation script returned error code 1

thank You for help

**Comment by xanmod** [comment]
This error apparently no longer persists, closing this issue.
