### ISSUE TITLE
DKMS installations fail after upgrading to 5.12.9 git20210607.e2253e0 from 5.12.9 git20210603.2d3e6cc (edge)

### ISSUE THREAD

**Issue by ryannathans** [xanmod/linux#158]
I'm using linux-xanmod-edge

See https://github.com/openrazer/openrazer/issues/1526

Something is different/broken with 5.12.9-edge, none of my DKMS installations succeeded on update from 5.12.9 due to the same error `ERROR (dkms apport): kernel package linux-headers-5.12.9-xanmod1-edge is not supported`

Maybe this is a hint? First time I have seen -edge have a different header to stable

![image](https://user-images.githubusercontent.com/1307375/121485744-d912a800-ca13-11eb-8d85-92e6bc7d262f.png)

![image](https://user-images.githubusercontent.com/1307375/121485910-019aa200-ca14-11eb-9233-e8bc491fa1a8.png)

**Comment by ryannathans** [comment]
![image](https://user-images.githubusercontent.com/1307375/121486278-58a07700-ca14-11eb-8893-ec28b1793aba.png)
No change in headers used if I swap to stable?

**Comment by ryannathans** [comment]
```
ls /boot
config-5.11.0-7614-generic
config-5.12.9-xanmod1
config-5.12.9-xanmod1-edge
efi
initrd.img
initrd.img-5.11.0-7614-generic
initrd.img-5.11.0-7614-generic.old-dkms
initrd.img-5.12.9-xanmod1
initrd.img-5.12.9-xanmod1-edge
initrd.img-5.4.47
initrd.img-5.4.47-rt28-xanmod1.dpkg-bak
initrd.img.old
System.map-5.11.0-7614-generic
System.map-5.12.9-xanmod1
System.map-5.12.9-xanmod1-edge
vmlinuz
vmlinuz-5.11.0-7614-generic
vmlinuz-5.12.9-xanmod1
vmlinuz-5.12.9-xanmod1-edge
vmlinuz.old

```

interesting, no 5.12.8, did 5.12.9-xanmod1 update to 5.12.9-xanmod1-edge?

**Comment by ryannathans** [comment]
confirming that booting the previous kernel works around this issue

working with 5.12.9-xanmod1 #0~git20210603.2d3e6cc but not git20210607.e2253e0

**Comment by figue** [comment]
Alexandre announced that edge is now built with LLVM's Clang ThinLTO:

![image](https://user-images.githubusercontent.com/3238330/121489335-4868a780-c9d4-11eb-83ee-0833692ba2a3.png)

You have to look around to enable the same flags for dkms, in case these modules support Clang.

**Comment by viig99** [comment]
> Alexandre announced that edge is now built with LLVM's Clang ThinLTO:
> 
> ![image](https://user-images.githubusercontent.com/3238330/121489335-4868a780-c9d4-11eb-83ee-0833692ba2a3.png)
> 
> You have to look around to enable the same flags for dkms, in case these modules support Clang.

Nvidia driver installation also fails on the new kernel, are there many flags we need to pass to get it to work ?

**Comment by figue** [comment]
I built kernel with clang with these flags and dkms for VirtualBox works:
```
sudo env LLVM=1 LLVM_IAS=1 CC=clang CXX=clang++ dkms install --no-depmod -m vboxhost -v 6.1.22_OSE -k 5.12.9-xanmod1-1-git-edge+
```

**Comment by ryannathans** [comment]
Where are these announcements?

I am guessing this breaks compatibility with the majority of modules? Fixed for now by downgrading to non-edge
