### ISSUE TITLE
How to uninstall this package

### ISSUE THREAD

**Issue by TomaszMyszak** [xanmod/linux#159]
I`m new in linux, did U have instruction for uninstall?

I have a answer:
"dpkg: błąd przetwarzania pakietu linux-image-5.12.8-xanmod1 (--remove):
 podproces zainstalowany pakiet linux-image-5.12.8-xanmod1 skrypt post-removal zwrócił kod błędu 1
dpkg: zbyt wiele błędów, zatrzymanie
Wystąpiły błędy podczas przetwarzania:
 linux-image-5.12.8-xanmod1
Przetwarzanie zostało zatrzymane z powodu wystąpienia zbyt wielu błędów.
E: Sub-process /usr/bin/dpkg returned an error code (1)"

dpkg: error processing linux-image-5.12.8-xanmod1 (--remove) package:
  subprocess installed package linux-image-5.12.8-xanmod1 post-removal script returned error code 1
dpkg: too many bugs, stop
Errors occurred while processing:
  linux-image-5.12.8-xanmod1
Processing has stopped because too many errors have occurred.
E: Sub-process / usr / bin / dpkg returned an error code (1)

in Ubuntu 20.04

**Comment by kkaosninja** [comment]
Might sound like an obvious question, but did you try `sudo apt remove linux-xanmod` ?

**Comment by xanmod** [comment]
https://itsfoss.com/dpkg-returned-an-error-code-1/
