### ISSUE TITLE
About Anbox Support

### ISSUE THREAD

**Issue by bigbruno** [xanmod/linux#16]
I do not know if it would be possible because of license, but it would be great if the xanmod kernel came with the modules ashmem_linux.ko and binder_linux.ko

Both are needed for Anbox to work, which is already included in the official Debian Testing repository

**Comment by xanmod** [comment]
If possible they will be included in the next release. Grateful.

**Comment by xanmod** [comment]
As of v5.2.2, these modules will be included.
