### ISSUE TITLE
FUTEX2 support for WINE is missing

### ISSUE THREAD

**Issue by gabriele2000** [xanmod/linux#161]
I'm running POP_OS 21.04 with kernel `5.12.12-xanmod1-cacule`, CONFIG_FUTEX2 is enabled of course, but `/sys/kernel/futex2` is missing.
Thanks to this, WINE cannot benefit from FUTEX2 and I honestly don't know what to do to "fix" the problem

**Comment by xanmod** [comment]
@andrealmeid

**Comment by andrealmeid** [comment]
@xanmod, it seems that I forgot to point you a patch for that. Can you apply this one here? https://gitlab.collabora.com/tonyk/linux/-/commit/ea9a7956b5f6f44f3ee70d82542c64fcb7c86c5e It should solve the problem.

**Comment by gabriele2000** [comment]
> @xanmod, it seems that I forgot to point you a patch for that. Can you apply this one here? https://gitlab.collabora.com/tonyk/linux/-/commit/ea9a7956b5f6f44f3ee70d82542c64fcb7c86c5e It should solve the problem.

Awesome! The fix will be available since xanmod-5-13 or you'll reupload 5.12.12 with the applied patch?

**Comment by xanmod** [comment]
Tomorrow the 5.12.13 rev will be released with this patch.

**Comment by gabriele2000** [comment]
> Tomorrow the 5.12.13 rev will be released with this patch.

WONDERFUL! Thanks a lot, your kernel is amazing and your support is awesome!

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/a6d4c4dcca870569737ddc8483c14bb6fa2f90b0
