### ISSUE TITLE
Upgrade failure?

### ISSUE THREAD

**Issue by yonderbread** [xanmod/linux#162]
I had the `5.12.12-xanmod1` kernel installed before, and then I upgraded to the `5.12.13` version, but when I run `neofetch` it shows I'm still using the old kernel? Do I need to explicitly boot into Linux using the new version or am I doing something wrong? Updates before automatically booted into Linux with the upgraded version except this time.

**Comment by xanmod** [comment]
Your installation must have failed, try running the apt upgrade again.

**Comment by yonderbread** [comment]
So it did get installed but I had to go and manually reconfigure my grub boot options.
