### ISSUE TITLE
AMD GPU 100% Usage  (>65W) When Idle

### ISSUE THREAD

**Issue by ryannathans** [xanmod/linux#163]
Problem does not occur in 5.12.12 but does occur in 5.12.13.

![image](https://user-images.githubusercontent.com/1307375/123339382-d1174400-d58d-11eb-9bce-bbd81b5080b7.png)

I have a Radeon VII

**Comment by ryannathans** [comment]
Comparison with 5.12.12

![image](https://user-images.githubusercontent.com/1307375/123339635-4daa2280-d58e-11eb-88a4-0375afea8199.png)

**Comment by xanmod** [comment]
Known issue and new revision soon with fix.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=44db63d1ad8d71c6932cbe007eb41f31c434d140

**Comment by ryannathans** [comment]
Resolved in 5.12.14
