### ISSUE TITLE
bbr2 problem

### ISSUE THREAD

**Issue by gz83** [xanmod/linux#164]
Hello, I installed your edge version of the kernel on my server, but when I tried to open bbr2, I found that the lsmod command could not find the information of bbr2, and the sysctl net.ipv4.tcp_available_congestion_control command only showed reno bbr2, not cubic information.

The server system is the latest version of debian10, and the kernel version is 5.12.13-xanmod1-edge.

**Comment by xanmod** [comment]
### cat /proc/sys/net/ipv4/tcp_congestion_control
```
bbr2
```


### modinfo tcp_bbr2
```
`name:           tcp_bbr2
filename:       (builtin)
author:         Van Jacobson <vanj@google.com>
author:         Neal Cardwell <ncardwell@google.com>
author:         Yuchung Cheng <ycheng@google.com>
author:         Soheil Hassas Yeganeh <soheil@google.com>
author:         Priyaranjan Jha <priyarjha@google.com>
author:         Yousuk Seung <ysseung@google.com>
author:         Kevin Yang <yyd@google.com>
author:         Arjun Roy <arjunroy@google.com>
description:    TCP BBR (Bottleneck Bandwidth and RTT)
file:           net/ipv4/tcp_bbr2
license:        Dual BSD/GPL
parm:           usage_based_cwnd:bool
parm:           undo:bool
parm:           tso_rtt_shift:int
parm:           startup_cwnd_gain:int
parm:           refill_add_inc:uint
parm:           probe_rtt_win_ms:uint
parm:           probe_rtt_mode_ms:uint
parm:           probe_rtt_cwnd_gain:uint
parm:           precise_ece_ack:bool
parm:           pacing_gain:array of int
parm:           min_tso_rate:int
parm:           min_rtt_win_sec:uint
parm:           loss_thresh:uint
parm:           inflight_headroom:uint
parm:           high_gain:int
parm:           full_loss_cnt:uint
parm:           full_ecn_cnt:uint
parm:           full_bw_thresh:uint
parm:           full_bw_cnt:uint
parm:           flags:uint
parm:           fast_path:bool
parm:           fast_ack_mode:uint
parm:           extra_acked_win_rtts:uint
parm:           extra_acked_max_us:uint
parm:           extra_acked_in_startup:int
parm:           extra_acked_gain:int
parm:           ecn_thresh:uint
parm:           ecn_reprobe_gain:uint
parm:           ecn_max_rtt_us:uint
parm:           ecn_factor:uint
parm:           ecn_enable:bool
parm:           ecn_alpha_init:uint
parm:           ecn_alpha_gain:uint
parm:           drain_to_target:bool
parm:           drain_gain:int
parm:           debug_with_printk:bool
parm:           debug_port_mask:ushort
parm:           debug_ftrace:bool
parm:           cwnd_warn_val:uint
parm:           cwnd_tso_bduget:uint
parm:           cwnd_min_target:uint
parm:           cwnd_gain:int
parm:           bw_probe_reno_gain:uint
parm:           bw_probe_rand_us:uint
parm:           bw_probe_rand_rounds:uint
parm:           bw_probe_pif_gain:uint
parm:           bw_probe_max_rounds:uint
parm:           bw_probe_base_us:uint
parm:           beta:uint
parm:           ack_epoch_acked_reset_thresh:uint 
```
### modinfo tcp_cubic
```
filename:       /lib/modules/5.12.13-xanmod1-edge/kernel/net/ipv4/tcp_cubic.ko
author:         Sangtae Ha, Stephen Hemminger
description:    CUBIC TCP
license:        GPL
version:        2.3
depends:        
intree:         Y
name:           tcp_cubic
retpoline:      Y
srcversion:     234F5A9AE12AF71F295C842
vermagic:       5.12.13-xanmod1-edge SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        73:B6:DA:ED:6A:6E:41:CB:CA:FD:C3:69:D8:B6:B0:F6:63:80:1D:08
sig_hashalgo:   sha512
signature:      0E:FE:74:53:46:A8:DB:72:82:DF:23:1B:D1:C6:98:59:78:9C:54:09:
		C0:06:9B:12:14:EA:BB:CA:DE:53:9B:5C:F5:93:A8:AC:47:8A:86:07:
		89:93:EC:56:FE:EB:B0:32:E2:BC:D0:64:6D:B6:F7:42:EB:88:50:FA:
		31:C8:94:E9:5E:68:C6:5E:DA:17:C4:13:4F:27:0E:4D:A7:5E:57:5A:
		D6:B2:1D:B5:73:F4:9F:7B:A6:9D:51:03:1D:D9:F8:D4:DA:41:18:F4:
		D4:CE:37:DE:BF:20:2A:20:9F:BE:DA:EE:AA:22:55:D0:F1:D8:B5:C2:
		88:C2:FF:66:14:23:40:AE:62:D7:85:62:68:26:81:83:AD:9C:D3:C1:
		60:87:41:15:2C:52:7C:EE:76:26:8C:10:E6:4B:07:E6:1B:69:AB:4B:
		9E:AD:88:15:C0:09:AA:08:A4:DC:4E:54:AB:DB:47:72:07:5A:EF:98:
		FF:88:01:82:42:EA:F7:8B:0C:5D:C1:8A:72:0E:F7:52:F8:A2:91:C2:
		B2:D1:AE:0B:81:42:0D:54:D0:D9:F0:30:92:8A:38:6E:D6:BE:2B:C9:
		3A:E1:11:66:28:45:D3:F3:96:1C:75:BD:B0:2E:8E:D4:86:0B:82:25:
		7A:F7:1C:22:05:B0:A8:F6:DC:38:C0:2D:31:2E:5C:47:8A:52:70:AE:
		F7:9F:FD:E9:1C:C6:7F:F6:48:BA:D6:84:9C:1E:ED:A0:8B:47:EC:BC:
		A8:A5:32:6C:AC:3A:A9:77:A8:0B:E7:7B:0A:EC:EC:66:3D:C2:C3:65:
		59:5E:FF:40:13:3A:EE:02:59:69:97:80:99:20:31:DB:9B:1C:84:5D:
		BD:A3:C4:B3:C4:BE:D9:6B:F4:83:64:2C:7A:E0:D7:CB:E4:21:07:67:
		5F:33:88:35:94:8C:F2:C4:C4:AF:2C:EB:EC:34:29:A4:2D:E4:49:57:
		34:6F:3F:A8:A4:4F:C6:78:46:E7:71:82:E2:A2:D2:6F:6C:34:9F:AD:
		8E:2F:1E:0F:E1:40:DB:BD:97:B1:6B:E5:16:8F:4A:8E:1C:FF:81:FE:
		9A:FF:10:8C:71:5C:31:1C:66:C1:FA:CF:11:9C:FB:3E:1A:38:B1:B3:
		7C:E1:23:E0:BD:CC:33:DB:9C:DA:13:0D:A7:CA:F1:6A:B1:43:FB:BB:
		52:3C:16:19:88:6F:0A:2A:57:69:C4:AF:F5:F2:FF:64:90:B7:27:37:
		F2:1D:18:A6:39:C7:C7:D5:7D:43:38:0F:73:66:E9:B9:39:C0:B2:EF:
		2B:38:97:10:6D:30:D8:93:0F:47:9E:A4:18:20:50:B4:89:C3:3D:05:
		9A:BA:FC:3E:73:A0:B3:C9:88:1B:C3:A8
parm:           tcp_friendliness:turn on/off tcp friendliness (int)
parm:           initial_ssthresh:initial value of slow start threshold (int)
parm:           hystart_low_window:lower bound cwnd for hybrid slow start (int)
parm:           hystart_detect:hybrid slow start detection mechanisms 1: packet-train 2: delay 3: both packet-train and delay (int)
parm:           hystart_ack_delta_us:spacing between ack's indicating train (usecs) (int)
parm:           hystart:turn on/off hybrid slow start algorithm (int)
parm:           fast_convergence:turn on/off fast convergence (int)
parm:           bic_scale:scale (scaled by 1024) value for bic function (bic_scale/1024) (int)
parm:           beta:beta for multiplicative increase (int)
```

**Comment by gz83** [comment]
> ### cat /proc/sys/net/ipv4/tcp_congestion_control
> ```
> bbr2
> ```
> 
> ### modinfo tcp_bbr2
> ```
> `name:           tcp_bbr2
> filename:       (builtin)
> author:         Van Jacobson <vanj@google.com>
> author:         Neal Cardwell <ncardwell@google.com>
> author:         Yuchung Cheng <ycheng@google.com>
> author:         Soheil Hassas Yeganeh <soheil@google.com>
> author:         Priyaranjan Jha <priyarjha@google.com>
> author:         Yousuk Seung <ysseung@google.com>
> author:         Kevin Yang <yyd@google.com>
> author:         Arjun Roy <arjunroy@google.com>
> description:    TCP BBR (Bottleneck Bandwidth and RTT)
> file:           net/ipv4/tcp_bbr2
> license:        Dual BSD/GPL
> parm:           usage_based_cwnd:bool
> parm:           undo:bool
> parm:           tso_rtt_shift:int
> parm:           startup_cwnd_gain:int
> parm:           refill_add_inc:uint
> parm:           probe_rtt_win_ms:uint
> parm:           probe_rtt_mode_ms:uint
> parm:           probe_rtt_cwnd_gain:uint
> parm:           precise_ece_ack:bool
> parm:           pacing_gain:array of int
> parm:           min_tso_rate:int
> parm:           min_rtt_win_sec:uint
> parm:           loss_thresh:uint
> parm:           inflight_headroom:uint
> parm:           high_gain:int
> parm:           full_loss_cnt:uint
> parm:           full_ecn_cnt:uint
> parm:           full_bw_thresh:uint
> parm:           full_bw_cnt:uint
> parm:           flags:uint
> parm:           fast_path:bool
> parm:           fast_ack_mode:uint
> parm:           extra_acked_win_rtts:uint
> parm:           extra_acked_max_us:uint
> parm:           extra_acked_in_startup:int
> parm:           extra_acked_gain:int
> parm:           ecn_thresh:uint
> parm:           ecn_reprobe_gain:uint
> parm:           ecn_max_rtt_us:uint
> parm:           ecn_factor:uint
> parm:           ecn_enable:bool
> parm:           ecn_alpha_init:uint
> parm:           ecn_alpha_gain:uint
> parm:           drain_to_target:bool
> parm:           drain_gain:int
> parm:           debug_with_printk:bool
> parm:           debug_port_mask:ushort
> parm:           debug_ftrace:bool
> parm:           cwnd_warn_val:uint
> parm:           cwnd_tso_bduget:uint
> parm:           cwnd_min_target:uint
> parm:           cwnd_gain:int
> parm:           bw_probe_reno_gain:uint
> parm:           bw_probe_rand_us:uint
> parm:           bw_probe_rand_rounds:uint
> parm:           bw_probe_pif_gain:uint
> parm:           bw_probe_max_rounds:uint
> parm:           bw_probe_base_us:uint
> parm:           beta:uint
> parm:           ack_epoch_acked_reset_thresh:uint 
> ```
> 
> ### modinfo tcp_cubic
> ```
> filename:       /lib/modules/5.12.13-xanmod1-edge/kernel/net/ipv4/tcp_cubic.ko
> author:         Sangtae Ha, Stephen Hemminger
> description:    CUBIC TCP
> license:        GPL
> version:        2.3
> depends:        
> intree:         Y
> name:           tcp_cubic
> retpoline:      Y
> srcversion:     234F5A9AE12AF71F295C842
> vermagic:       5.12.13-xanmod1-edge SMP preempt mod_unload modversions 
> sig_id:         PKCS#7
> signer:         Build time autogenerated kernel key
> sig_key:        73:B6:DA:ED:6A:6E:41:CB:CA:FD:C3:69:D8:B6:B0:F6:63:80:1D:08
> sig_hashalgo:   sha512
> signature:      0E:FE:74:53:46:A8:DB:72:82:DF:23:1B:D1:C6:98:59:78:9C:54:09:
> 		C0:06:9B:12:14:EA:BB:CA:DE:53:9B:5C:F5:93:A8:AC:47:8A:86:07:
> 		89:93:EC:56:FE:EB:B0:32:E2:BC:D0:64:6D:B6:F7:42:EB:88:50:FA:
> 		31:C8:94:E9:5E:68:C6:5E:DA:17:C4:13:4F:27:0E:4D:A7:5E:57:5A:
> 		D6:B2:1D:B5:73:F4:9F:7B:A6:9D:51:03:1D:D9:F8:D4:DA:41:18:F4:
> 		D4:CE:37:DE:BF:20:2A:20:9F:BE:DA:EE:AA:22:55:D0:F1:D8:B5:C2:
> 		88:C2:FF:66:14:23:40:AE:62:D7:85:62:68:26:81:83:AD:9C:D3:C1:
> 		60:87:41:15:2C:52:7C:EE:76:26:8C:10:E6:4B:07:E6:1B:69:AB:4B:
> 		9E:AD:88:15:C0:09:AA:08:A4:DC:4E:54:AB:DB:47:72:07:5A:EF:98:
> 		FF:88:01:82:42:EA:F7:8B:0C:5D:C1:8A:72:0E:F7:52:F8:A2:91:C2:
> 		B2:D1:AE:0B:81:42:0D:54:D0:D9:F0:30:92:8A:38:6E:D6:BE:2B:C9:
> 		3A:E1:11:66:28:45:D3:F3:96:1C:75:BD:B0:2E:8E:D4:86:0B:82:25:
> 		7A:F7:1C:22:05:B0:A8:F6:DC:38:C0:2D:31:2E:5C:47:8A:52:70:AE:
> 		F7:9F:FD:E9:1C:C6:7F:F6:48:BA:D6:84:9C:1E:ED:A0:8B:47:EC:BC:
> 		A8:A5:32:6C:AC:3A:A9:77:A8:0B:E7:7B:0A:EC:EC:66:3D:C2:C3:65:
> 		59:5E:FF:40:13:3A:EE:02:59:69:97:80:99:20:31:DB:9B:1C:84:5D:
> 		BD:A3:C4:B3:C4:BE:D9:6B:F4:83:64:2C:7A:E0:D7:CB:E4:21:07:67:
> 		5F:33:88:35:94:8C:F2:C4:C4:AF:2C:EB:EC:34:29:A4:2D:E4:49:57:
> 		34:6F:3F:A8:A4:4F:C6:78:46:E7:71:82:E2:A2:D2:6F:6C:34:9F:AD:
> 		8E:2F:1E:0F:E1:40:DB:BD:97:B1:6B:E5:16:8F:4A:8E:1C:FF:81:FE:
> 		9A:FF:10:8C:71:5C:31:1C:66:C1:FA:CF:11:9C:FB:3E:1A:38:B1:B3:
> 		7C:E1:23:E0:BD:CC:33:DB:9C:DA:13:0D:A7:CA:F1:6A:B1:43:FB:BB:
> 		52:3C:16:19:88:6F:0A:2A:57:69:C4:AF:F5:F2:FF:64:90:B7:27:37:
> 		F2:1D:18:A6:39:C7:C7:D5:7D:43:38:0F:73:66:E9:B9:39:C0:B2:EF:
> 		2B:38:97:10:6D:30:D8:93:0F:47:9E:A4:18:20:50:B4:89:C3:3D:05:
> 		9A:BA:FC:3E:73:A0:B3:C9:88:1B:C3:A8
> parm:           tcp_friendliness:turn on/off tcp friendliness (int)
> parm:           initial_ssthresh:initial value of slow start threshold (int)
> parm:           hystart_low_window:lower bound cwnd for hybrid slow start (int)
> parm:           hystart_detect:hybrid slow start detection mechanisms 1: packet-train 2: delay 3: both packet-train and delay (int)
> parm:           hystart_ack_delta_us:spacing between ack's indicating train (usecs) (int)
> parm:           hystart:turn on/off hybrid slow start algorithm (int)
> parm:           fast_convergence:turn on/off fast convergence (int)
> parm:           bic_scale:scale (scaled by 1024) value for bic function (bic_scale/1024) (int)
> parm:           beta:beta for multiplicative increase (int)
> ```

After the modinfo tcp_bbr2 command is executed, the error modinfo: ERROR: Module tcp_bbr2 not found is returned, and the output of the other two commands is normal.

**Comment by xanmod** [comment]
Thanks for reporting!

I noticed that from the kmod package (>=27) has support for built-in bbr2.

BBR2 is already up and running because it is a built-in kernel module. Kmod is an external tool for manipulating kernel modules.

You can install the latest version of kmod without any problems:
http://ftp.debian.org/debian/pool/main/k/kmod/kmod_28-1_amd64.deb
http://ftp.debian.org/debian/pool/main/k/kmod/libkmod2_28-1_amd64.deb

**Comment by xanmod** [comment]
Then we will add the kmod package to the repository for all supported distros.

**Comment by gz83** [comment]
> Thanks for reporting!
> 
> I noticed that from the kmod package (>=27) has support for built-in bbr2.
> 
> BBR2 is already up and running because it is a built-in kernel module. Kmod is an external tool for manipulating kernel modules.
> 
> You can install the latest version of kmod without any problems:
> http://ftp.debian.org/debian/pool/main/k/kmod/kmod_28-1_amd64.deb<img alt="" width="16" height="16" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAdtJREFUOBHFUs9LVGEUPfe9lzb+ahQ0Bg1sEdaQC2nhM4nMTZg2C6GF06JN0CLobwihf8BWgWtdSIqmhm1GMFNo4aaFUKQoAyFBBaON1Jvbvdf5hsfkMugM3/ede+4537y5b4D/Dep/m2mMvkdPmLj+DNPk2vDiTricGaVSdB1EnfaAzLvs+e827yzM3lgaufiL+CExHfpJf4LCxeF5Zs6okYjyYD5goMeCVRsBW2JqE3972b8QgDHofOWGNZ0WP+1ilt1Bsh7AOVfHz7oggaGOQVvKTwfnvLMN9Vl5tElnOHrzFT55eN77DI/bH9hSrpr2HDSjWW/11kyBibZcI3GzBWHrNTQV6tAfhraUq6Y9B81oNlBBbrvifhnVekgnu5BKpTB2P2t+5emfXVg/eO/yltHCLgDxkQyzgmRNE4IgwNPx8Yp2rqaxwo1oRiBDtGPn5DzZi1ExXho/jo6rNM8ydoGH0ma8u/3jU7w0Xq25jK/d/amPXy5kL3ULTWu9V8ijpbYZ5xOtKMo3r+RXMfV5DiX5KGRmLzdGlifK3DQM5O41FAuHL5gwJvMQzykgyD8e0/L6HukbUMdfxr6Vu5f5dzTETFel2awmme83Iv5Agf964/arbdX+Gf4AGR+gT8wubJYAAAAASUVORK5CYII=">
> http://ftp.debian.org/debian/pool/main/k/kmod/libkmod2_28-1_amd64.deb<img alt="" width="16" height="16" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAdtJREFUOBHFUs9LVGEUPfe9lzb+ahQ0Bg1sEdaQC2nhM4nMTZg2C6GF06JN0CLobwihf8BWgWtdSIqmhm1GMFNo4aaFUKQoAyFBBaON1Jvbvdf5hsfkMugM3/ede+4537y5b4D/Dep/m2mMvkdPmLj+DNPk2vDiTricGaVSdB1EnfaAzLvs+e827yzM3lgaufiL+CExHfpJf4LCxeF5Zs6okYjyYD5goMeCVRsBW2JqE3972b8QgDHofOWGNZ0WP+1ilt1Bsh7AOVfHz7oggaGOQVvKTwfnvLMN9Vl5tElnOHrzFT55eN77DI/bH9hSrpr2HDSjWW/11kyBibZcI3GzBWHrNTQV6tAfhraUq6Y9B81oNlBBbrvifhnVekgnu5BKpTB2P2t+5emfXVg/eO/yltHCLgDxkQyzgmRNE4IgwNPx8Yp2rqaxwo1oRiBDtGPn5DzZi1ExXho/jo6rNM8ydoGH0ma8u/3jU7w0Xq25jK/d/amPXy5kL3ULTWu9V8ijpbYZ5xOtKMo3r+RXMfV5DiX5KGRmLzdGlifK3DQM5O41FAuHL5gwJvMQzykgyD8e0/L6HukbUMdfxr6Vu5f5dzTETFel2awmme83Iv5Agf964/arbdX+Gf4AGR+gT8wubJYAAAAASUVORK5CYII=">

Hello, after I installed the two deb packages you provided to me, the system can find the bbr2 module, but I still cannot start bbr2 normally.

**Comment by xanmod** [comment]
BBR2 is already running, it's the default.

It is compiled as a built-in kernel and not a module, so it doesn't show information in lsmod.

**Comment by gz83** [comment]
> ```
> CONFIG_TCP_CONG_BBR2=y
> CONFIG_DEFAULT_BBR2=y
> CONFIG_DEFAULT_TCP_CONG="bbr2"
> ```
> 
> BBR2 is already running, it's the default.
> 
> It is compiled as a built-in kernel and not a module, so it doesn't show information in lsmod.

The problem has been solved, thank you for your help.
