### ISSUE TITLE
for the first time in a long time it does not work

### ISSUE THREAD

**Issue by virhao** [xanmod/linux#166]
X230 5.13

![IMG_20210630_075157](https://user-images.githubusercontent.com/60742438/123909578-87f23600-d979-11eb-9dbb-8de872f9ad15.jpg)

**Comment by xanmod** [comment]
Which distro?
if it's based on Ubuntu, please test with mainline:

[linux-headers](
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.13/amd64/linux-headers-5.13.0-051300-lowlatency_5.13.0-051300.202106272333_amd64.deb)
[headers](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.13/amd64/linux-headers-5.13.0-051300_5.13.0-051300.202106272333_all.deb)
[linux-image](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.13/amd64/linux-image-unsigned-5.13.0-051300-lowlatency_5.13.0-051300.202106272333_amd64.deb)
[linux-modules](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.13/amd64/linux-modules-5.13.0-051300-lowlatency_5.13.0-051300.202106272333_amd64.deb)

**Comment by virhao** [comment]
Xubuntu tested witch mainline and it works but xanmod still does not

**Comment by xanmod** [comment]
Try this rev:

[linux-image](https://dl.xanmod.org/rc/5.13.0-xanmod2-edge/linux-image-5.13.0-xanmod2-edge_5.13.0-xanmod2-edge-0~git20210701.0650e71_amd64.deb)
[linux-headers](https://dl.xanmod.org/rc/5.13.0-xanmod2-edge/linux-headers-5.13.0-xanmod2-edge_5.13.0-xanmod2-edge-0~git20210701.0650e71_amd64.deb)

**Comment by virhao** [comment]
![image](https://user-images.githubusercontent.com/60742438/124311164-9bfe8900-db6d-11eb-819c-31a342c621b3.png)

Now works thx
