### ISSUE TITLE
xanmod 5.12.5 default compilation parameter exception

### ISSUE THREAD

**Issue by Alion548** [xanmod/linux#168]
The make menuconfig command finds many kernel parameters unchecked by default, such as BBR, BBR2.
![image](https://user-images.githubusercontent.com/8340545/124052486-1685b680-da51-11eb-8cb3-5531db04555c.png)

**Comment by xanmod** [comment]
```
# Linux/x86 5.12.5 Kernel Configuration
:
CONFIG_TCP_CONG_BBR=m
CONFIG_TCP_CONG_BBR2=y
# CONFIG_DEFAULT_RENO is not set
CONFIG_DEFAULT_BBR2=y
```
In kernel config is correct. Try it out with the latest version of 5.12. Today is 5.12.14.
