### ISSUE TITLE
Tons of bad page map errors

### ISSUE THREAD

**Issue by ms178** [xanmod/linux#169]
Hello, 

I don't know if this bug report is actionable at all as I am probably using too fancy compiler flags and run it on an unsupported distro, but maybe someone knows what's going wrong here. I was using Xanmod succesfully on openSUSE Tumbleweed until 5.12.14 and 5.13, they spit out tons of "bad page map errors" during compilation workloads (see dmesg-log attached).

As compiler I use LLVM/Clang 12 provided by SUSE and added a Kernel patch by a Google engineer (see: https://github.com/ClangBuiltLinux/linux/issues/1369#issuecomment-832307198) to make LTO work with TRIM_UNUSED_KSYMS.

[dmesg-errors.txt](https://github.com/xanmod/linux/files/6760346/dmesg-errors.txt)
[config.txt](https://github.com/xanmod/linux/files/6760347/config.txt)
[Makefile.txt](https://github.com/xanmod/linux/files/6760348/Makefile.txt)

I already replaced the CPU, as I faced some quirky WHEA-errors on Windows on the same machine the last days which are now gone, so the hardware should be fine.

**Comment by ms178** [comment]
As a follow-up, I tried GCC 11.1.1 20210629 with a different set of cflags and due to using GCC LTO was disabled; I disabled the Multigenerational LRU option. The issue persists though, albeit with less error messages: 

[Jul11 20:23] BUG: Bad page map in process cc1  pte:800000030d100867 pmd:22a5f1067
[  +0,000010] page:00000000d425abd0 refcount:1 mapcount:-256 mapping:0000000000000000 index:0x7fc062020 pfn:0x30d100
[  +0,000004] memcg:ffff8b853709d000
[  +0,000002] anon flags: 0x17ff800000080014(uptodate|lru|swapbacked|node=0|zone=2|lastcpupid=0xfff)
[  +0,000006] raw: 17ff800000080014 fffff8a3c8229e48 fffff8a3cb100848 ffff8b85073802c1
[  +0,000002] raw: 00000007fc062020 0000000000000000 00000001fffffeff ffff8b853709d000
[  +0,000001] page dumped because: bad pte
[  +0,000001] addr:00007fc062020000 vm_flags:08100073 anon_vma:ffff8b85073802c0 mapping:0000000000000000 index:7fc062020
[  +0,000003] file:(null) fault:0x0 mmap:0x0 readpage:0x0
[  +0,000006] CPU: 14 PID: 11675 Comm: cc1 Not tainted 5.13.1-xanmod1-gcc-1 #2
[  +0,000003] Hardware name: LENOVO GAMING TF/X99-TF Gaming, BIOS CX99DE26 10/10/2020
[  +0,000001] Call Trace:
[  +0,000005]  dump_stack+0x64/0x7c
[  +0,000006]  print_bad_pte.cold+0x82/0xf9
[  +0,000005]  unmap_page_range+0x7b5/0xc60
[  +0,000006]  unmap_vmas+0x65/0xe0
[  +0,000003]  unmap_region+0x8f/0xe0
[  +0,000004]  __do_munmap+0x2b1/0x4c0
[  +0,000004]  __vm_munmap+0x52/0xa0
[  +0,000003]  __x64_sys_munmap+0x23/0x40
[  +0,000004]  do_syscall_64+0x3a/0xc0
[  +0,000004]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[  +0,000005] RIP: 0033:0x7fc06284bfab
[  +0,000003] Code: 8b 15 c9 7e 0c 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb 89 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa b8 0b 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 95 7e 0c 00 f7 d8 64 89 01 48
[  +0,000002] RSP: 002b:00007ffd730855b8 EFLAGS: 00000206 ORIG_RAX: 000000000000000b
[  +0,000003] RAX: ffffffffffffffda RBX: fffffffffffffbf8 RCX: 00007fc06284bfab
[  +0,000001] RDX: 0000000000000000 RSI: 00000000000d0000 RDI: 00007fc061fb1000
[  +0,000001] RBP: 0000000000000016 R08: 00007fc061fb1000 R09: 0000000003a18d38
[  +0,000002] R10: 0000000003a191b0 R11: 0000000000000206 R12: 0000000000000001
[  +0,000001] R13: 0000000003a71be0 R14: 0000000003aaddd0 R15: 00007fc061fb1010
[  +0,000013] Disabling lock debugging due to kernel taint
(END)

**Comment by ms178** [comment]
FYI, I can reproduce the issue with a 5.14 RC1 mainline Kernel with the same GCC flags and Kernel config options which also produce these errors on 5.13.1-Xanmod.

**Comment by ms178** [comment]
Good news, I cannot reproduce the issue anymore on Manjaro 21.0.7 with 5.13.4-Linux-Xanmod from AUR, with GCC 11 and a more Arch-specific Kernel config which is far less stripped down / altered as the one in the original post.

**Comment by ms178** [comment]
Sorry, I spoke to soon and hit this again with 5.13.4-Linux-Xanmod on Manjaro. But I couldn't reproduce the issue yet with the standard Manjaro Kernel (5.10.52) before.

**Comment by ms178** [comment]
I also couldn't reproduce the issue with the default Kernel on Kubuntu 21.04 (5.11-25) with the same hardware setup.

**Comment by joder666** [comment]
Just a wild guess, have you tried with CMA disabled?

**Comment by ms178** [comment]
@joder666 Not yet, but it is very hard to reproduce the issue on 5.13.8 any longer on Kubuntu 21.10 (with O3, Clang 12.0.1 + Thin-LTO). I have seen "Transparent Huge Pages" fail when compiled with O3 and GCC 11.2 though - no web pages will load any longer and similar dmesg entries appear.

**Comment by ms178** [comment]
I am closing this issue, I am not sure exactly where the issue comes from, but with 5.13.8 Xanmod (compiled with GCC 11.2, O3 + march=native) and Dbus-broker compiled with GCC 11.2, I cannot reproduce the issue any longer reliably. Hence it could be a Clang-related issue with my config/compiler flags in either the Kernel or Dbus-Broker.
