### ISSUE TITLE
4.20  

### ISSUE THREAD

**Issue by scafroglia93** [xanmod/linux#17]
------------[ cut here ]------------
[    2.286601] nouveau 0000:01:00.0: timeout
[    2.286645] WARNING: CPU: 3 PID: 259 at drivers/gpu/drm/nouveau/nvkm/subdev/secboot/ls_ucode_msgqueue.c:183 acr_ls_sec2_post_run+0x1a4/0x250 [nouveau]
[    2.286645] Modules linked in: nouveau(+) i2c_algo_bit ttm drm_kms_helper syscopyarea sysfillrect sysimgblt nvme fb_sys_fops mxm_wmi r8169 drm nvme_core ahci i2c_i801 libahci video wmi
[    2.286651] CPU: 3 PID: 259 Comm: systemd-udevd Not tainted 4.20.0-xanmod1 #1.181225
[    2.286652] Hardware name: Micro-Star International Co., Ltd. MS-7B48/Z370-A PRO (MS-7B48), BIOS 2.70 08/03/2018
[    2.286679] RIP: 0010:acr_ls_sec2_post_run+0x1a4/0x250 [nouveau]
[    2.286679] Code: d0 e9 c0 fe ff ff 49 8b 7f 10 48 8b 5f 50 48 85 db 74 1e e8 7e d3 38 d0 48 89 da 48 c7 c7 b3 e4 43 c0 48 89 c6 e8 36 63 da cf <0f> 0b e9 0a ff ff ff 48 8b 5f 10 eb dc 8b 45 20 48 c7 c6 68 56 43
[    2.286680] RSP: 0018:ffffa36401eb3650 EFLAGS: 00010282
[    2.286681] RAX: 0000000000000000 RBX: ffff8fb79c2295c0 RCX: ffffffff91465a68
[    2.286681] RDX: 0000000000000001 RSI: 0000000000000096 RDI: 0000000000000246
[    2.286682] RBP: ffff8fb79c525b80 R08: 0000000000000001 R09: 00000000000002bf
[    2.286682] R10: 0000000000000004 R11: 0000000000000000 R12: 0000000000000040
[    2.286683] R13: ffff8fb78f760b40 R14: 0000000088541920 R15: ffff8fb78e997c00
[    2.286684] FS:  00007f6a1dde3680(0000) GS:ffff8fb79eac0000(0000) knlGS:0000000000000000
[    2.286684] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.286685] CR2: 00007f6a1dc62000 CR3: 000000044eb0e005 CR4: 00000000003606e0
[    2.286686] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    2.286686] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[    2.286687] Call Trace:
[    2.286714]  acr_r352_bootstrap+0x19b/0x290 [nouveau]
[    2.286739]  acr_r352_reset+0x35/0x220 [nouveau]
[    2.286767]  gf100_gr_init_ctxctl+0x6d/0xa10 [nouveau]
[    2.286789]  nvkm_engine_init+0xaa/0x1e0 [nouveau]
[    2.286811]  nvkm_subdev_init+0xb2/0x200 [nouveau]
[    2.286831]  nvkm_engine_ref.part.0+0x43/0x60 [nouveau]
[    2.286852]  nvkm_ioctl_new+0x125/0x200 [nouveau]
[    2.286879]  ? nvkm_fifo_chan_child_del+0x90/0x90 [nouveau]
[    2.286905]  ? gf100_gr_dtor+0xd0/0xd0 [nouveau]
[    2.286926]  nvkm_ioctl+0xd8/0x170 [nouveau]
[    2.286947]  nvif_object_init+0xbf/0x110 [nouveau]
[    2.286974]  nvc0_fbcon_accel_init+0x59/0x910 [nouveau]
[    2.286999]  nouveau_fbcon_create+0x545/0x550 [nouveau]
[    2.287005]  __drm_fb_helper_initial_config_and_unlock+0x1cd/0x410 [drm_kms_helper]
[    2.287029]  nouveau_fbcon_init+0x15a/0x1c0 [nouveau]
[    2.287054]  nouveau_drm_device_init+0x43b/0x7f0 [nouveau]
[    2.287057]  ? pci_bus_read_config_word+0x49/0x70
[    2.287081]  nouveau_drm_probe+0x274/0x2d0 [nouveau]
[    2.287083]  local_pci_probe+0x41/0x90
[    2.287084]  pci_device_probe+0x188/0x1a0
[    2.287087]  really_probe+0xf8/0x3b0
[    2.287088]  driver_probe_device+0xb3/0xf0
[    2.287089]  __driver_attach+0xdd/0x110
[    2.287091]  ? driver_probe_device+0xf0/0xf0
[    2.287092]  bus_for_each_dev+0x76/0xc0
[    2.287093]  bus_add_driver+0x152/0x230
[    2.287094]  ? 0xffffffffc04a0000
[    2.287095]  driver_register+0x6b/0xb0
[    2.287096]  ? 0xffffffffc04a0000
[    2.287098]  do_one_initcall+0x46/0x1f5
[    2.287099]  ? free_pcp_prepare+0x4a/0xd0
[    2.287101]  ? kmem_cache_alloc_trace+0x2f/0x1d0
[    2.287103]  do_init_module+0x5a/0x210
[    2.287104]  load_module+0x2116/0x23a0
[    2.287107]  ? ima_post_read_file+0xf4/0x100
[    2.287109]  ? __do_sys_finit_module+0xa8/0x110
[    2.287110]  __do_sys_finit_module+0xa8/0x110
[    2.287112]  do_syscall_64+0x65/0x190
[    2.287114]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[    2.287115] RIP: 0033:0x7f6a1d8ed839
[    2.287116] Code: 00 f3 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 1f f6 2c 00 f7 d8 64 89 01 48
[    2.287117] RSP: 002b:00007ffd8224b0e8 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[    2.287117] RAX: ffffffffffffffda RBX: 000055f07e842a70 RCX: 00007f6a1d8ed839
[    2.287118] RDX: 0000000000000000 RSI: 00007f6a1d5cc145 RDI: 0000000000000013
[    2.287118] RBP: 00007f6a1d5cc145 R08: 0000000000000000 R09: 00007ffd8224b200
[    2.287119] R10: 0000000000000013 R11: 0000000000000246 R12: 0000000000000000
[    2.287119] R13: 000055f07e7f8470 R14: 0000000000020000 R15: 000055f07e842a70
[    2.287120] ---[ end trace dabc1c2442916b9b ]---

**Comment by xanmod** [comment]
And with latest drivers from oibaf ppa?
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

**Comment by scafroglia93** [comment]
No nmore with oibaf ppa; it's a sporadic issue.

This log was sent inside bugzilla

**Comment by xanmod** [comment]
Hi @scafroglia93, the last v4.20.4 solved this issue?
