### ISSUE TITLE
Enable PSI by default

### ISSUE THREAD

**Issue by hakavlad** [xanmod/linux#173]
Seems like PSI metrics are not provided by the kernel by default:
```
$ uname -a
Linux user-vb 5.10.48-xanmod1 #0~git20210707.195170f SMP PREEMPT Wed Jul 7
14:04:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /proc/pressure/memory
cat: /proc/pressure/memory: No such file or directory
```
https://facebookmicrosites.github.io/psi/

PSI metrics are used by userspace OOM handlers (oomd, systemd-oomd, nohang etc).

Could you enable `CONFIG_PSI=y`, please?

**Comment by xanmod** [comment]
```
CONFIG_PSI=y
CONFIG_PSI_DEFAULT_DISABLED=y
```
https://cateee.net/lkddb/web-lkddb/PSI_DEFAULT_DISABLED.html

**Comment by hakavlad** [comment]
>The overhead is too low to affect common scheduling-intense workloads in practice

https://cateee.net/lkddb/web-lkddb/PSI_DEFAULT_DISABLED.html

Could you disable `CONFIG_PSI_DEFAULT_DISABLED=y`, please?

Possible benefits: users will be able to enjoy PSI metrics by default without passing `psi=1` during boot.

**Comment by xanmod** [comment]
In the past we have had discussions about psi about its possible overhead problems.

For these reasons, mainline keeps the PSI_DEFAULT_DISABLED option.

With psi=1 there was ~2% loss in a system with no workload.

I've kept psi=0 for years and you're the first to ask about it. I'm still not motivated to enable this feature by default.

**Comment by hakavlad** [comment]
OK, thanks.
