### ISSUE TITLE
Internet Connection works on normal linux but doesn't on xanmod-cacule

### ISSUE THREAD

**Issue by AndreVuillemot160** [xanmod/linux#178]
Greetings, I use an AUR package linux-xanmod-cacule with it's headers files. Unfortunately after an update, kernel broke internet connection, meanwhile on normal linux kernel it works.

**Comment by xanmod** [comment]
send your `/var/log/kern.log` or `dmeng`, `lshw` and `lsmod` (normal linux and xanmod)

**Comment by AndreVuillemot160** [comment]
[logs.zip](https://github.com/xanmod/linux/files/6892985/logs.zip)
Here are logs loonix-normal, is linux original kernel
And xanmod, well is xanmod-cacule

**Comment by xanmod** [comment]
Apply this patch: [0001-hrtimer-revert-highres-variants.patch.gz](https://github.com/xanmod/linux/files/6893790/0001-hrtimer-revert-highres-variants.patch.gz)

**Comment by xanmod** [comment]
I need xanmod logs too

**Comment by xanmod** [comment]
Your network device requires a proprietary r8168 module, try installing the r8168-dkms package.
Note, this must be a kernel build with gcc.

**Comment by AndreVuillemot160** [comment]
Thanks! Working now. Issue closed
