### ISSUE TITLE
Could you please make Anbox/halium support builtin

### ISSUE THREAD

**Issue by shemgp** [xanmod/linux#181]
[Anbox-halium](https://github.com/Anbox-halium/anbox-halium) is a way to run Android apps in Linux. It needs kernel modifications that are usually mainline already but are not enabled in the Xanmod kernel. It would be nice if it's enabled by defaults so I don't have to rebuild the kernel.

```
git clone https://github.com/Anbox-halium/anbox-halium.git
cd anbox-halium/scripts
./check-kernel-config.sh /boot/config-5.13.6-xanmod1-edge 


Checking config file for Halium specific config options.


 CONFIG_SW_SYNC_USER is neither enabled nor disabled in the config file
 CONFIG_SW_SYNC_USER is not set, set it
 CONFIG_NET_CLS_CGROUP is already set
 CONFIG_CGROUP_NET_CLASSID is already set
 CONFIG_VETH is already set
 CONFIG_ANDROID_BINDER_DEVICES is set, but to "binder,hwbinder,vndbinder" not "binder,hwbinder,vndbinder,anbox-binder,anbox-hwbinder,anbox-vndbinder".
 

Config file checked, found 2 errors that I did not fix.
```

I guess what's needed is just `CONFIG_SW_SYNC_USER`.

Thanks.

**Comment by xanmod** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.13.y&id=a44eb74cd413fa62733d7df89942eabaf26176eb

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.13.y&id=d3ae4fa40088045b500f4d1ce85eb926b6cd2d3e

CONFIG_SW_SYNC_USER has been moved to CONFIG_SW_SYNC ( ! / ? )

https://github.com/Anbox-halium/anbox-halium/blob/b5e46b24c821d87b67de3b63e627a83a85adb05f/scripts/check-kernel-config.sh#L17

**Comment by xanmod** [comment]
@erfanoabdi

**Comment by erfanoabdi** [comment]
yeah this `check-kernel-config.sh` script is only for android halium devices with non-mainline kernels
 xanmod kernel already have all the needed drivers, no changes require here.  

i should update my scripts to be able to pick "*binder" nodes instead of "anbox-*binder"
