### ISSUE TITLE
CacULE edge version?

### ISSUE THREAD

**Issue by AndreVuillemot160** [xanmod/linux#182]
Just got an idea in my mind, is there a chance of building something like this in the title?

**Comment by xanmod** [comment]
The edge version (clang+lto) still doesn't work with most proprietary modules. I would have to create one more branch. But cacule + rdb is a candidate for edge and stable branches when considered stable.

**Comment by AndreVuillemot160** [comment]
As I said, it was just an idea.

**Comment by xanmod** [comment]
I'm explaining to clarify for more users.
