### ISSUE TITLE
NTFS3 driver does not want to work anymore.

### ISSUE THREAD

**Issue by jarrard** [xanmod/linux#189]
For some reason this ntfs3 driver worked for a couple days then suddenly stopped working and spits out a very generic error code.

The module is loaded.

The useless error is _wrong fs type, bad option, bad superblock on /dev/sdb2, missing codepage or helper program, or other error._

Not really sure what could be going wrong, I've tried clearing mount flags and messing with them but it appears that isn't the issue. The drives are NVME and SSD and mount fine with NTFS and under Windows10.. could there be something wrong with my drives that prevents driver from working?

**Comment by joder666** [comment]
Boot into windows and run check disk on the drive.

**Comment by jarrard** [comment]
> Boot into windows and run check disk on the drive.

Ok

**Comment by jarrard** [comment]
Looks like you were right; that seemed to have fixed it. I have no idea how they got mismatches on them in first place. Hope its not going to become a common thing :(
