### ISSUE TITLE
Malformed patch-5.14.0-xanmod1

### ISSUE THREAD

**Issue by solbjorn** [xanmod/linux#195]
If you compare the mentioned patch from the Releases section with the manual GitHub comparison:

https://github.com/xanmod/linux/compare/7d2a07b769330c34b4deabeed939325c77a7ec2f..8c839bfa06e51e6409f73894a13f8dfa6d8d8b34.diff

you'll see that the release version lacks LRNG, hrtimer stuff and probably more.

Also, I didn't get why you decided to enable UBSAN and MAXSMP on non-debug kernels (both were disabled on 5.13-). That's a huge overhead.

(GenLRU also got disabled due to MAXSMP)

**Comment by xanmod** [comment]
Thanks to report. Patch fixed.

This config is based on the Ubuntu kernel. I haven't had time to review everything yet, recent releases from the edge branch undergo maturation to the stable branch.

I decided to keep MAXSMP to virtually remove the cpus limitation, this feature only slightly increases the size of vmlinuz without prejudice. MGLRU was already disabled by default, enabling it disables le9 patch protection `vm.clean_low_kbytes`.

**Comment by solbjorn** [comment]
Ok, I see.

Regarding MAXSMP -- not recommended to enable it without a real need (like building a kernel for server cluster or so). It moves all cpumask variables from stack to heap -> increases memory usage and slightly decreases performance in several critical workloads.
