### ISSUE TITLE
Failed to start entropy daemon based on havege algorithm

### ISSUE THREAD

**Issue by mskpluk** [xanmod/linux#196]
Debian runing on testing repository. Ryzen 2700 platform.
Haveged systemd daemon failing to start on all 5.14 kernel versions (.1-.6, edge and cacule) Same on latest 5.13.19
if I execute haveged -F -v 1 in terminal I get segfault error.
Works fine with 5.13.13-xanmod1-cacule however.
Haveged version 1.9.14-1 - same in bullseye, bookworm and sid.

**Comment by ms178** [comment]
Aye, I've also seen this error message on Manjaro but it was the other way around: The haveged provided by Manjaro segfaults and when I use haveged-git compiled from AUR, I get the error [  +0,003561] systemd[1]: /usr/lib/systemd/system/haveged.service:9: Neither a valid executable name nor an absolute path: SBIN_DIR@/haveged

Even if I manually adjust the haveged.service to take the absolute path (/usr/bin/haveged in my case), it fails.

**Comment by xanmod** [comment]
Can you tell me on which kernel version 5.13 this issue arises?

**Comment by mskpluk** [comment]
I was wrong about 5.13.13-xanmod1-cacule - it crashing on this kernel too. Sorry for misinformation.
It's crashing from 5.12.18-xanmod3. Runs fine on 5.12.18-xanmod2 and earlier versions

**Comment by xanmod** [comment]
It is related to lrng.

Updated patchset to v42, please see if problem persists with 5.14.8-xanmod1-edge / 5.10.69-xanmod1

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/12d0d9b97e6b9131c375a1c2f1202fc3b3719d2e/CONFIGS/xanmod/gcc/config#L4601

@smuellerDD

**Comment by mskpluk** [comment]
Failing to start on 5.14.8-xanmod1-edge / 5.10.69-xanmod1
Runs fine if compiled with '# CONFIG_LRNG is not set'

**Comment by smuellerDD** [comment]
Am Dienstag, dem 28.09.2021 um 09:29 -0700 schrieb mskpluk:
> Failing to start on 5.14.8-xanmod1-edge / 5.10.69-xanmod1
> Runs fine if compiled with '# CONFIG_LRNG is not set'
> 

The problem is in haveged in function run_daemon with the following lines:

```
 if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
         error_exit("Couldn't query entropy-level from kernel");
      /* get number of bytes needed to fill pool */
      nbytes = (poolSize  - current)/8;
```

This code assumes that the poolsize is strictly larger than the available
entropy /dev/random can process. This is true for the legacy /dev/random but
it is not true for the LRNG considering that it has additional entropy
sources.

Here is a gdb output:

(gdb) p poolSize
$10 = 1024
(gdb)
696           if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
(gdb)
699           nbytes = (poolSize  - current)/8;
(gdb) p current
$13 = 1093
(gdb) p nbytes
$14 = <optimized out>
(gdb) p (poolSize  - current)
$15 = 4294967227
(gdb) p (poolSize  - current)/8
$16 = 536870903
(gdb) n
700           if(nbytes<1)   continue;
(gdb) p nbytes
$17 = 536870903

Do you want to open a bug at haveged and copy me?

Thanks for the report.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, dem 28.09.2021 um 19:44 +0200 schrieb Stephan Mueller:
> Am Dienstag, dem 28.09.2021 um 09:29 -0700 schrieb mskpluk:
> > Failing to start on 5.14.8-xanmod1-edge / 5.10.69-xanmod1
> > Runs fine if compiled with '# CONFIG_LRNG is not set'
> > 
> 
> The problem is in haveged in function run_daemon with the following lines:
> 
> ```
>  if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
>          error_exit("Couldn't query entropy-level from kernel");
>       /* get number of bytes needed to fill pool */
>       nbytes = (poolSize  - current)/8;
> ```
> 
> This code assumes that the poolsize is strictly larger than the available
> entropy /dev/random can process. This is true for the legacy /dev/random but
> it is not true for the LRNG considering that it has additional entropy
> sources.
> 
> Here is a gdb output:
> 
> (gdb) p poolSize
> $10 = 1024
> (gdb)
> 696           if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
> (gdb)
> 699           nbytes = (poolSize  - current)/8;
> (gdb) p current
> $13 = 1093
> (gdb) p nbytes
> $14 = <optimized out>
> (gdb) p (poolSize  - current)
> $15 = 4294967227
> (gdb) p (poolSize  - current)/8
> $16 = 536870903
> (gdb) n
> 700           if(nbytes<1)   continue;
> (gdb) p nbytes
> $17 = 536870903
> 
> Do you want to open a bug at haveged and copy me?
> 
> Thanks for the report.

I have filed a bug report https://github.com/jirka-h/haveged/issues/62

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 29.09.2021 um 21:24 +0200 schrieb Stephan Mueller:
> Am Dienstag, dem 28.09.2021 um 19:44 +0200 schrieb Stephan Mueller:
> > Am Dienstag, dem 28.09.2021 um 09:29 -0700 schrieb mskpluk:
> > > Failing to start on 5.14.8-xanmod1-edge / 5.10.69-xanmod1
> > > Runs fine if compiled with '# CONFIG_LRNG is not set'
> > > 
> > 
> > The problem is in haveged in function run_daemon with the following lines:
> > 
> > ```
> >  if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
> >          error_exit("Couldn't query entropy-level from kernel");
> >       /* get number of bytes needed to fill pool */
> >       nbytes = (poolSize  - current)/8;
> > ```
> > 
> > This code assumes that the poolsize is strictly larger than the available
> > entropy /dev/random can process. This is true for the legacy /dev/random
> > but
> > it is not true for the LRNG considering that it has additional entropy
> > sources.
> > 
> > Here is a gdb output:
> > 
> > (gdb) p poolSize
> > $10 = 1024
> > (gdb)
> > 696           if (ioctl(random_fd, RNDGETENTCNT, &current) == -1)
> > (gdb)
> > 699           nbytes = (poolSize  - current)/8;
> > (gdb) p current
> > $13 = 1093
> > (gdb) p nbytes
> > $14 = <optimized out>
> > (gdb) p (poolSize  - current)
> > $15 = 4294967227
> > (gdb) p (poolSize  - current)/8
> > $16 = 536870903
> > (gdb) n
> > 700           if(nbytes<1)   continue;
> > (gdb) p nbytes
> > $17 = 536870903
> > 
> > Do you want to open a bug at haveged and copy me?
> > 
> > Thanks for the report.
> 
> I have filed a bug report https://github.com/jirka-h/haveged/issues/62

Patch is created for haveged and confirmed working.

Ciao
Stephan
> 
> Ciao
> Stephan
>

**Comment by mskpluk** [comment]
Thank You
