### ISSUE TITLE
Wine / Proton Fsync not working on 5.14.9

### ISSUE THREAD

**Issue by italoghost** [xanmod/linux#199]
Hi! I am current using Pop!_OS 21.04 and downloaded the latest stable xanmod version (5.14.9). Since then, FSYNC is not working properly on games launched through Lutris. I have to disable it to make it work and this behaviour didn't occur on other versions of the Kernel.

Tell me if I have to submit some log file.

Thanks!

**Comment by ms178** [comment]
I also see problems with newer Proton-versions above 6.3 (eg. Glorious Eggroll's 6.18-GE-2) with some games, such as Battlefield 1. Origin crashes and high CPU-load remains until I manually kill some processes. Company of Heroes 2 doesn't seem to be affected though.

**Comment by italoghost** [comment]
@ms178 I experienced high CPU-load as well. The Division managed to open with FSYNC enabled but it was very sluggish and with my CPU with 100% usage. Origin didn't even open with it enabled.

**Comment by ms178** [comment]
I don't know which version of the FUTEX-patchset Xanmod currently carries, but there are newer versions out there which are incompatible with the older patchset. Maybe at some point it would make more sense to carry the newer version (but that would brake older Proton-versions).

**Comment by xanmod** [comment]
Please, test this build:
https://dl.xanmod.org/rc/5.14.9-xanmod2/

**Comment by italoghost** [comment]
@xanmod how can I do that? Just run both the headers and the image .deb?

**Comment by xanmod** [comment]
`sudo dpkg -i linux-image-5.14.9-xanmod2*.deb linux-headers-5.14.9-xanmod2*.deb`

**Comment by italoghost** [comment]
Tested some launchers (Ubisoft and Origin) and played 1 hour of The Division with fsync enabled. Everything is working fine!

**Comment by ms178** [comment]
@xanmod I can also confirm that Battlefield 1 (via Steam/Origin) does now work fine with Glorious Eggroll's 6.18-GE-2. Thank you for the fix!
