### ISSUE TITLE
Drivers adicionais do ALSA

### ISSUE THREAD

**Issue by rauldipeas** [xanmod/linux#20]
Eu citei a adição de drivers adicionais do ALSA na live to Toca do Tux, estava me referindo especificamente à [este pacote](https://launchpad.net/~kxstudio-debian/+archive/ubuntu/kxstudio/+packages?field.name_filter=alsa-firmware&field.status_filter=published&field.series_filter=).

**Comment by xanmod** [comment]
Legal Raul,
Mas como este pacote contém firmwares de licença proprietária, será melhor incluir no pacote linux-firmware ou diretamente no repositório.

**Comment by rauldipeas** [comment]
Eu acho que você poderia disponibilizar como dependência do meta-pacote do XenMod.
