### ISSUE TITLE
5.14.14 renders unusable all USB ports except one

### ISSUE THREAD

**Issue by SoftExpert** [xanmod/linux#207]
Hello,

I updated to 5.14.14-xanmod1-cacule and then to 5.14.14-xanmod2-cacule - both versions render unusable my USB ports except the one that has pass-through charging.
When booting in the previous version 5.14.13 all USB ports function normally.
Here are the requested files:
[lshw5.14.13.log](https://github.com/xanmod/linux/files/7391333/lshw5.14.13.log)
[lshw5.14.14.log](https://github.com/xanmod/linux/files/7391334/lshw5.14.14.log)
[kern.log](https://github.com/xanmod/linux/files/7391287/kern.log)
I also performed a sudo lsusb -v under both versions:
[lsusb_xanmod5.14.14.txt](https://github.com/xanmod/linux/files/7391339/lsusb_xanmod5.14.14.txt)
[lsusb_xanmod5.14.13.txt](https://github.com/xanmod/linux/files/7391340/lsusb_xanmod5.14.13.txt)

**Comment by xanmod** [comment]
@matnyman

**Comment by SoftExpert** [comment]
Hello, I confirm the same issue with 5.14.16 and with 5.15.0 ...

**Comment by wfzyx** [comment]
I'm using 5.14.20-xanmod1 #0~git20211118.f58acc8 and it indeed it broke something with USB interfaces, half of them doesn't work anymore.

**Comment by xanmod** [comment]
Send your kern.log / syslog in /var/log/

**Comment by xanmod** [comment]
@gregkh @sashalevin

**Comment by wfzyx** [comment]
Attached as requested. Note that I reverted back to 5.14.17 for now

[kern.log](https://github.com/xanmod/linux/files/7572385/kern.log
[syslog.log](https://github.com/xanmod/linux/files/7572386/syslog.log)
)

**Comment by xanmod** [comment]
Do the same problems persist in current builds? I need to create a build with some reverted usb commits to testing.

**Comment by SoftExpert** [comment]
Since 5.15.2 tt there are no longer issues with USB on my side.

**Comment by wfzyx** [comment]
5.14.21 seems to be fine too, I've just tested it

**Comment by SoftExpert** [comment]
I confirm, 5.14.21 good here too ...
