### ISSUE TITLE
kernel 5.2.1???

### ISSUE THREAD

**Issue by Potterli20** [xanmod/linux#21]
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.2.1.tar.xz

**Comment by Potterli20** [comment]
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.2.1.tar.xz

**Comment by xanmod** [comment]
https://dl.xanmod.org/5.2/Changes-5.2.1-xanmod2

We were waiting for the new revision of bmq.
