### ISSUE TITLE
Is Xanmod-Cacule not updated anymore?

### ISSUE THREAD

**Issue by bigshans** [xanmod/linux#211]
I found that xanmod-cacule has not been updated to 5.15.

**Comment by MoisesMH** [comment]
Well I've read TT-CPU-Scheduler is the successor of CacULE. It's coded by the same owner.
https://github.com/hamadmarri/TT-CPU-Scheduler

So xanmod developers decided to merge its new scheduler (revision 2) for testing I guess. Also, CacULE is now an archived repository by its author.
https://github.com/hamadmarri/cacule-cpu-scheduler/

**Comment by HougeLangley** [comment]
Sorry for my delay 😅

See this one: https://github.com/HougeLangley/xanmod-archlinux

**Comment by HougeLangley** [comment]
I will close

**Comment by ptr1337** [comment]
https://github.com/CachyOS/cacule-cpu-scheduler

here its getting updated. 

https://github.com/CachyOS/linux-cachyos

Here you will find cacule kernels. Maybe will create just patches so they can be applied to all distros.

**Comment by Vistaus** [comment]
> https://github.com/CachyOS/cacule-cpu-scheduler
> 
> here its getting updated.

By a different developer.
