### ISSUE TITLE
Futex2 no longer part of 5.15.1-tt ?

### ISSUE THREAD

**Issue by SicLuceatLux** [xanmod/linux#213]
Maybe there has been some relabeling but is it normal that 5.15.1-tt does only show "fsync is up and running" in the Lutris logs (instead of "fsync2 is ..." ? doesnt matter which proton-ge version I m using.

**Comment by xanmod** [comment]
https://github.com/andrealmeid/futex_waitv_patches

The latest implementation is just futex_waitv() for futex, before futex2.

Compatibility with proton/wine for fsync is in progress, try the proton experimental. The 5.14 (stable: linux-xanmod) has the futex2 patchset compatible with current protons.

**Comment by gabriele2000** [comment]
So what's the flag for wine to use this new implementation?

**Comment by SicLuceatLux** [comment]
> https://github.com/andrealmeid/futex_waitv_patches
> 
> The latest implementation is just futex_waitv() for futex, before futex2.
> 
> Compatibility with proton/wine for fsync is in progress, try the proton experimental. The 5.14 (stable: linux-xanmod) has the futex2 patchset compatible with current protons.

Sorry for my late reply. This is my question, "fsync2..." notification was appearing with the xanmod-5.14.X+proton-experimental or proton-ge builds why is it not implemented in current 5.15.1-tt kernel?

**Comment by xanmod** [comment]
The new futex_waitv() api needed for fsync is present since the first 5.15.0 build, the recent proton experimental is already supported. 

https://github.com/ValveSoftware/wine/commit/0dad4bc333c4a15a963b12de956cfa36c65c020c

**Comment by xanmod** [comment]
The new fsync api has been merged into proton 6.3-8.
