### ISSUE TITLE
MGLRU and 5.15

### ISSUE THREAD

**Issue by hakavlad** [xanmod/linux#214]
Seems like MGLRU patchset is not in 5.15-xanmod. Why?

BTW, MGLRU v5: https://lore.kernel.org/lkml/20211111041510.402534-1-yuzhao@google.com/

**Comment by xanmod** [comment]
v5 will be added in the next mainline rev. upstream.

**Comment by hakavlad** [comment]
will be added in 5.15.3-xanmod, right?
