### ISSUE TITLE
Unable to update XanMod using APT due to Cloudflare block

### ISSUE THREAD

**Issue by Bungeetaco** [xanmod/linux#215]
Hi there,

I run XanMod RT on my tor exit relay servers, and up until recently had no issues with updating to newer versions, but now it looks like Cloudflare is refusing the requests from my IPs, returning 403.

Here is the apt update log with the error:
```
2003) [0] darkrai:~ bungee$ sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Err:4 http://deb.xanmod.org releases InRelease
  403  Forbidden [IP: 172.64.80.1 80]
Hit:5 https://deb.torproject.org/torproject.org bullseye InRelease
Reading package lists... Done
E: Failed to fetch http://deb.xanmod.org/dists/releases/InRelease  403  Forbidden [IP: 172.64.80.1 80]
E: The repository 'http://deb.xanmod.org releases InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Here are my server's IPs: 
51.161.43.235
51.161.43.236
51.161.43.237
51.161.43.238

This has caused me some headache as I have to manually download and copy the deb file from one machine to that server everytime since then. It's only been happening for the last couple of months, so I would appreciate any assistance in resolving this if possible.

Thanks

**Comment by xanmod** [comment]
I added rules to allow this range, see if it resolved.

**Comment by Bungeetaco** [comment]
This has resolved the issue, and my VM is now able to download repository updates.
Thank you for your help, and for maintaining this project!
