### ISSUE TITLE
TCP improvement patch

### ISSUE THREAD

**Issue by Vistaus** [xanmod/linux#217]
A new patch has just been merged in the 5.17 kernel which significantly improves TCP throughput:
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.17-TCP-Optimization
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=f35f821935d8df76f9c92e2431a225bdff938169

I was wondering if this patch could be backported to the current XanMod Edge.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux-patches/tree/master/linux-5.15.y-xanmod/net

**Comment by Vistaus** [comment]
Thank you so much! 🙂
