### ISSUE TITLE
Error while compiling 5.2.2

### ISSUE THREAD

**Issue by 0x221E** [xanmod/linux#22]
Build failing while compiling;

```
  CC [M]  fs/xfs/xfs_acl.o
  CC [M]  fs/xfs/xfs_sysctl.o
  CC [M]  fs/xfs/xfs_ioctl32.o
  CC [M]  fs/xfs/xfs_pnfs.o
  LD [M]  fs/xfs/xfs.o
  AR      fs/built-in.a
==> ERROR: A failure occurred in build().
    Aborting...
```

Any idea what could be the possible cause ?

**Comment by xanmod** [comment]
Add next to your make command:
` 2>&1 | tee ../kernel-build.log`
In the log created, search for "error" to find where the error occurred and send here.

Do the git clone again too.

**Comment by 0x221E** [comment]
That helped resolving the error, thanks.
`cpio` package was missing.

Closing the issue.
