### ISSUE TITLE
[Tigerlake] GPU HANG: ecode 12:1:859ffffb

### ISSUE THREAD

**Issue by monarc99** [xanmod/linux#220]
Kernel 5.15 cause gpu hangs on intel tigerlake gpus.

Is it possible to add the patch to xanmod, until it added to the kernel?

Issue:
https://gitlab.freedesktop.org/drm/intel/-/issues/4145

Patch:

José Roberto de Souza @zehortigoza · 15 hours ago

Patches reviewed and pushed https://cgit.freedesktop.org/drm-intel/commit/?h=drm-intel-gt-next&id=f3799ff16fcfacd44aee55db162830df461b631f

So now one of the i915 maintainers will send a "fixes" pull request to the drm maintainer that will send a pull request to Linus master branch, all that should take a few weeks. When those patches lands in the Linus master branch, Greg's scripts(maintainer of Linux stable branches) will catch those patches and push to older kernels branches.

So nothing else to do here besides wait.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/releases/tag/5.15.6-xanmod2
