### ISSUE TITLE
Adding a one-liner patch

### ISSUE THREAD

**Issue by cybik** [xanmod/linux#222]
Hello!

I've stumbled upon this patch, which should help with systems using Zen 3 in a laptop configuration:

https://patchwork.kernel.org/project/platform-driver-x86/patch/CADtzkx7TdfbwtaVEXUdD6YXPey52E-nZVQNs+Z41DTx7gqMqtw@mail.gmail.com/

It's an extremely silly one-liner slated for 5.16, but I'm wondering if Xanmod would merge it in before time.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/cb65ee0c7e5981c4eca2cb3c30b389d020c3afb6

**Comment by cybik** [comment]
For the record, upstream landed it today: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.8

Thank you for applying it a hair earlier, it did help with the testing as I reported on it in the amd tracker on FreeDesktop.
