### ISSUE TITLE
Docker/K3D issues (cpu cfs quota, cpu cfs period, cpu shares support)

### ISSUE THREAD

**Issue by applike-ss** [xanmod/linux#223]
I am using `5.15.6-xanmod2-tt` and my docker info spits out:
```
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
```

which prevents me from using k3d, because it can't mount something of these.

I checked #3, but the fix mentioned `swapaccount=1` doesn't work anymore (at least not for me).

Is ther another workaround to try? Docker shouldn't be an issue in 2021 imho.

Originally coming from: https://github.com/rancher/k3d/issues/873

**Comment by xanmod** [comment]
Apparently, docker did not detect tt as a scheduler other than cfs.

The simplest solution is to use the xanmod stable branch which uses cfs by default.

**Comment by xanmod** [comment]
@hamadmarri

**Comment by applike-ss** [comment]
Will try out the regular linux-xanmod package.

Seems the warning comes from here: https://github.com/moby/moby/blob/65cc84abc522a564699bb171ca54ea1857256d10/daemon/info_unix.go#L105

**Comment by ionutnechita** [comment]
Hi applike-ss,
For you ticket exist other ticket:
https://github.com/hamadmarri/TT-CPU-Scheduler/issues/14
 - [question] Is possible to use Docker Server with TT enabled in kernel?

TT implementation is for isolation all CPU cores. And this is not working with Docker/K3S/K8S.

A good day.

Ionut Nechita
ionutnechita
Sunlight Developer Kernel - AMD/Intel Lowlatency Platform

**Comment by applike-ss** [comment]
Thanks for that. Your write up in the mentioned issue tells me that the TT scheduler would by definition never be capable for containerization. Am i correct with this statement? For the moment i am still sticking to the regular xanmod kernel which is working nicely. I am not a kernel developer myself, so i'm not going to even try to hack something in.

**Comment by ionutnechita** [comment]
Hi applike-ss,

Yes, this statement is correct.
TT is not currently designed for containers.
But that's great/powerful for desktop and gaming.

A good day.

**Comment by applike-ss** [comment]
In this case i will close the issue, because the target group for this scheduler simply isn't me.

A good day to you too :-)
