### ISSUE TITLE
Include patch to add support for MediaTek WiFi chips

### ISSUE THREAD

**Issue by Slater91** [xanmod/linux#231]
Hello!

A two-line patch was introduced to add support for some MediaTek WiFi chips that are now commonly found in laptops and motherboards from manufacturers such as ASUS. It is available here: https://patchwork.kernel.org/project/linux-wireless/patch/84ab45bf42f57fd0301c156ffc11d0fe330ff1f8.1636857817.git.deren.wu@mediatek.com/

Would it be possible to include it in the next release of the 5.15 line so that users with hardware featuring that chip can take advantage of it?

Thank you!

**Comment by xanmod** [comment]
https://github.com/xanmod/linux-patches/tree/master/linux-5.15.y-xanmod/mt76
https://github.com/xanmod/linux/releases/tag/5.15.13-xanmod1

**Comment by Slater91** [comment]
Thank you, Alexandre!
