### ISSUE TITLE
_microarchitecture=14 not working with 5.15.17-1

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#240]
On Arch linux compilation with  _microarchitecture=14 (CONFIG_MZEN2) is not working. 

```
...
   98) Intel-Native optimizations autodetected by GCC
   99) AMD-Native optimizations autodetected by GCC

    0) Generic (default)
    
==> WARNUNG: According to PKGBUILD variable _microarchitecture, your choice is 14
==> Building this package for microarchitecture: CONFIG_MZEN2

  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/menu.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
.config:413:warning: override: GENERIC_CPU2 changes choice state
#
# configuration written to .config
#
arch/x86/Makefile:178: CONFIG_X86_X32 enabled but no binutils support
  -> Prepared linux-xanmod version 5.15.17-xanmod1-1
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Beginne build()...
```

Despite this error/warning the compilation proceeds and a working package resp. kernel is coming out of it, but the compilation is done with   `-march=x86-64-v2` instead of `-march=znver2`

**Comment by figue** [comment]
The issue seems [at this point because CONFIG_GENERIC_CPU2=y](https://github.com/xanmod/linux/blame/5.16/CONFIGS/xanmod/gcc/config#L416). All microarchitectures display the same warning ".config:413:warning: override: GENERIC_CPU2 changes choice state".

For now, you can disable CONFIG_GENERIC_CPU2 and all will work again.

**Comment by figue** [comment]
With nconfig it works well, so I'll push a workaround in AUR. Please update your local repo and try again.
