### ISSUE TITLE
Kernel Name and Version difers from kernel.org Versions

### ISSUE THREAD

**Issue by securerootd** [xanmod/linux#252]
As of date, Xanmod versions are:

> Linux 5.15 | Current Stable (STABLE) | 5.15.26-xanmod1 | 2022-03-02 
> Linux 5.16 | Latest Mainline (EDGE) | 5.16.12-xanmod1 | 2022-03-02
> Linux 5.10 | Long Term Support (LTS) | 5.10.103-xanmod1 | 2022-03-02 

Where as kernel.org defines

> mainline: 	5.17-rc6 	2022-02-27 	
> stable: 	5.16.12 	2022-03-02 	
> longterm: 	5.15.26

There is a difference between current **stable** and **mainline** naming scheme between xanmod and kernel.org and that is honestly a bit misleading.

Can we please fix this or maybe take a different naming scheme?

**Comment by xanmod** [comment]
XanMod is not mainline, it's based.
