### ISSUE TITLE
Linux-xanmod-edge, No clang config

### ISSUE THREAD

**Issue by RiverOnVenus** [xanmod/linux#254]
Hi, I use the [linux-xanmod-edge](https://aur.archlinux.org/packages/linux-xanmod-edge) 5.17.0-1 from AUR and when I select clang to compile, the `config` is missing.

```
  -> Setting version...
cp: cannot stat 'CONFIGS/xanmod/clang/config': No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...

```
```
❯ cd src/linux-5.17/CONFIGS/xanmod 
linux-xanmod-edge/src/linux-5.17/CONFIGS/xanmod 
➜ ls
gcc/

```

Regards

**Comment by figue** [comment]
As far as I know, clang config is not ready yet in 5.17. I'll disable that in PKGBUILD. Thanks for reporting it.

**Comment by figue** [comment]
@RiverOnVenus Do you edit the package? Or are you using some AUR helper? In my last commit I forced _clang to gcc, so it should compile always gcc (because clang is missing for now)... So I don't understand how you bypass it.

**Comment by RiverOnVenus** [comment]
@figue At first I didn't notice your changes, I shouldn't have changed _compiler.

```
 ## Choose between GCC and CLANG config (default is GCC)
-if [ -z ${_compiler+x} ]; then
+#if [ -z ${_compiler+x} ]; then
   _compiler=gcc
-fi
+#fi
```

**Comment by figue** [comment]
Yes, I could... The fact is that you don't need to edit the PKGBUILD to use these variables. So that's why I commented "the if statment". The intended use of those variables is to declare them outside of makepkg, so the package can be compiled quickly, for example:
```
env _compiler=clang _microarchitecture=38 use_tracers=y use_numa=n use_ns=y _localmodcfg=y _compress_modules=y makepkg -sic
```

**Comment by RiverOnVenus** [comment]
Okay, thanks a lot: )

**Comment by Titaniumtown** [comment]
When will this be fixed? Would love to use clang again :(

**Comment by Souravgoswami** [comment]
Is there any update related to clang? I see Archlinux's PKGBUILD (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod) is straight up using gcc/config as clang-config.:

```
# Choose between the 4 main configs for stable branch. Default x86-64-v1 which use CONFIG_GENERIC_CPU2:
# Possible values: config_x86-64-v1 / config_x86-64-v2 (default) / config_x86-64-v3 / config_x86-64-v4
# This will be overwritten by selecting any option in microarchitecture script
# Source files: https://github.com/xanmod/linux/tree/5.17/CONFIGS/xanmod/gcc
if [ -z ${_config+x} ]; then
  _config=config_x86-64-v2
fi
```

Not sure about potential downsides, is that okay to do this?

**Comment by figue** [comment]
Hi, this part of PKGBUILD only let you choose over these config files:

https://gitlab.com/xanmod/linux/-/tree/6.5/CONFIGS/xanmod/gcc?ref_type=heads
