### ISSUE TITLE
Include patch to fix issue with MT7921e devices

### ISSUE THREAD

**Issue by Slater91** [xanmod/linux#258]
Hello.
As [bug report 214557](https://bugzilla.kernel.org/show_bug.cgi?id=214557) on the kernel's Bugzilla says, there is currently an issue with MediaTek network devices using the MT7921e driver. The issue is that the devices are not detected on boot unless the system's power is completely removed (i.e. the mains plug is removed on desktops or the battery is disconnected on laptops). This is quite inconvenient. A [patch](https://raw.githubusercontent.com/FireBurn/KernelStuff/master/04-mt76.patch) is already available, but it will only be included in kernel 5.18. Considering it is a trivial patch overall, it would be nice if it were included in the Xanmod kernel to avoid this issue.

Thank you!

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/110c4be3fc8d9d7f28bb83e1dfc212625fd71074

Fix series already present.
