### ISSUE TITLE
Debian/Ubuntu APT repository and GPG key stuck behind Cloudflare attack mode?

### ISSUE THREAD

**Issue by Leemreturn** [xanmod/linux#259]
I'm unable to wget/curl the GPG key from the dl.xanmod.org page or install anything through the APT repository due to a 503 Service Available, when checking the output of the page I get a Cloudflare attack mode message that says my browser needs to be checked? I'm in OVH SAS's network on a fresh Debian 11 install so this probably shouldn't be happening to me?

**Comment by xanmod** [comment]
Confirm that this issue still persists for you.

**Comment by Leemreturn** [comment]
It's still happening, I just curled the link and got a "Checking your browser before accessing. Your browser will redirect to your requested content shortly" page.

**Comment by Leemreturn** [comment]
Any update on fixing this?

**Comment by Leemreturn** [comment]
--2022-05-09 21:47:42--  https://dl.xanmod.org/gpg.key
Resolving dl.xanmod.org (dl.xanmod.org)... 162.159.137.85, 162.159.138.85, 2606:4700:7::a29f:8955, ...
Connecting to dl.xanmod.org (dl.xanmod.org)|162.159.137.85|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2022-05-09 21:47:42 ERROR 503: Service Unavailable.

**Comment by Minds3t** [comment]
Same here. Trying to access it from Hetzner.

**Comment by Minds3t** [comment]
More likely wrong / too strict security settings

**Comment by Leemreturn** [comment]
It's apparently been months now and this still isn't solved? There are posts about this very issue from February. The response has changed from 503 to 403. That's not exactly ideal either.

**Comment by Bungeetaco** [comment]
I'm running my server behind my residential ISP (Bell Canada) and am getting the same error (403 Forbidden).
Why does this need to be turned on for the public GPG key? There are less strict settings which would still offer protection on Cloudflare's end.

Please advise/unblock. I am unable to use XanMod due to being unable to retrieve the signing key.

**Comment by Leemreturn** [comment]
It's literally been months and this _still_ hasn't been fixed? Are you serious? @xanmod No updates?

**Comment by Leemreturn** [comment]
--2022-06-22 19:39:03--  http://dl.xanmod.org/gpg.key
Resolving dl.xanmod.org (dl.xanmod.org)... 172.64.196.7, 172.64.197.7, 2606:4700:e6::ac40:c407, ...
Connecting to dl.xanmod.org (dl.xanmod.org)|172.64.196.7|:80... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2022-06-22 19:39:04 ERROR 503: Service Temporarily Unavailable.

**Comment by Leemreturn** [comment]
<h1><span data-translate="checking_browser">Checking your browser before accessing</span> dl.xanmod.org.</h1>
 
 This is part of the response. Why close this issue when it's still an issue?

**Comment by Minds3t** [comment]
This issue still occurs! Also with my home internet connection...

**Comment by Leemreturn** [comment]
@xanmod This shouldn't be closed. This is a genuine issue that you've just chosen to ignore?

**Comment by JoneKone** [comment]
wget https://dl.xanmod.org/gpg.key
--2022-12-21 23:13:34--  https://dl.xanmod.org/gpg.key
Resolving dl.xanmod.org (dl.xanmod.org)... 188.114.96.3, 188.114.97.3, 2a06:98c1:3120::3, ...
Connecting to dl.xanmod.org (dl.xanmod.org)|188.114.96.3|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2022-12-21 23:13:34 ERROR 503: Service Temporarily Unavailable.


from hetzner.
