### ISSUE TITLE
BBRplus？？？

### ISSUE THREAD

**Issue by Potterli20** [xanmod/linux#26]
it??
https://github.com/cx9208/bbrplus
from for china!!!

**Comment by Aniverse** [comment]
The modification of bbrplus has been merged into bbr in linux kernel 5.1.

---

说白了 bbrplus 就是改了点东西，然后那部分修改在 5.1 内核里合并进去了。
换句话说，5.1 内核带的 bbr 已经包含了所谓的 bbrplus 的改进（bbr 是一直在修改的，比如说 5.0 内核的 bbr，4.15 内核的 bbr 和 4.9 内核的 bbr 其实都是不一样的）
那还要 bbrplus 干嘛，直接装 5.2 内核用自带的 bbr 就行了

**Comment by Potterli20** [comment]
> The modification of bbrplus has been merged into bbr in linux kernel 5.1.
> So just `apt-get install -y linux-xanmod`, then reboot to use bbr.
> 
> 说白了 bbrplus 就是改了点东西，然后那部分修改在 5.1 内核里合并进去了。
> 换句话说，5.1 及以上的内核里自带的 bbr 已经包含了所谓的 bbrplus 的修改
> 那还要 bbrplus 干嘛，直接装新内核用自带的 bbr 就行了
> PS：bbr 是一直在修改的，比如说 5.0 内核的 bbr，4.15 内核的 bbr 和 4.9 内核的 bbr 其实都是不一样的

好吧，我就说嘛，我为什么编译不了
