### ISSUE TITLE
Lost ethernet (r8168) internet connection on Parrot OS 5.0 after updating to 5.17.9-xanmod1

### ISSUE THREAD

**Issue by Astro4l** [xanmod/linux#267]
I am running Parrot 5.0 and after updating xanmod kernel, I am no longer able to use ethernet connection. WiFi works fine.
Switching to the parrot kernel the ethernet works fine. I first noticed this after updating to 5.17.6-xanmod1

**Comment by xanmod** [comment]
run `lsmod` and see if module r8169 appears.

enable it by:
`sudo modprobe r8169`

**Comment by Astro4l** [comment]
Well that works but I noticed I have to run the command after every reboot. Any way to make it persistent?

**Comment by ionutnechita** [comment]
Hi @Astro4l,
Yes, this module can be made persistent.

Under root, please try this command:
echo "r8169" > /etc/modules-load.d/r8169.conf

**Comment by Astro4l** [comment]
This worked! @ionutnechita I appreciate your help. Thank you.
