### ISSUE TITLE
5.18 V4L2 support breaks v4l2loopback

### ISSUE THREAD

**Issue by cybik** [xanmod/linux#270]
the .config for 5.18.1-xanmod1-x64v2 is missing `CONFIG_VIDEO_V4L2=m` even though other V4L2 options are set to Y. This breaks compiling the v4l2loopback module.

**Comment by nazar-pc** [comment]
Why did you close the issue? I have the same challenge. Though commenting-out check in dkms.conf fixed compilation at least, though it still doesn't work.
