### ISSUE TITLE
Why no most recent stabel Kernel with TT?

### ISSUE THREAD

**Issue by SicLuceatLux** [xanmod/linux#272]
Hi I was wondering why there is no TT version for the latest stable or its previous Kernel version. 
TT is a wonderful addition but I guess it only really shines with the latest Kernel. 

Phoronix Benchmarks do point out that especially gaming on AMD is gaining by using the latest Kernel.
https://www.phoronix.com/scan.php?page=article&item=rdna2-ubuntu2204-drivers&num=1  

I also remember that there had been a time where TT was always shipped with the latest Kernel. Why has that changed?

**Comment by RiverOnVenus** [comment]
Actually the TT developer currently only maintain the LTS version.

**Comment by SicLuceatLux** [comment]
Thx for the answer
