### ISSUE TITLE
5.18.2 introduces glibc 2.33 dependency, making it unusable with Ubuntu 20.04

### ISSUE THREAD

**Issue by SoftExpert** [xanmod/linux#273]
Hello,

Xanmod kernel v 5.18.2 requires glibc 2.33 to build the Nvidia module; previous version (5.18.1) was less exigent and the same Nvidia module built just fine.
I'm using the official PPA.
Is there a way to have 2 versions of the kernel with different glibc version requirements?
I'm asking because currently I use Ubuntu 20.04 and I would like to continue to use Xanmod kernels for a while with it.

Cheers !

**Comment by xanmod** [comment]
For -edge use the latest ubuntu lts or wait for v5.18.5 release which will be the stable branch.
