### ISSUE TITLE
The binary ready working for Arch 

### ISSUE THREAD

**Issue by abdulbadii** [xanmod/linux#275]
How do I get the binary ready working for Arch ? Is the release/tag page is binary, can directly used on Arch ?
Please explain simple, thanks

**Comment by ms178** [comment]
There is no pre-built binary for Arch. But you can use "pacman -S base-devel" [to get gcc compiler and some needed dependencies] and download a snapshot from https://aur.archlinux.org/packages/linux-xanmod-edge, extract it - you should have a linux-xanmod-edge directory with a file called PKGBUILD. From a console, go to that location and do a "makepkg -si --cleanbuild --skippgpcheck" to build it yourself. Take a look at the PKGBUILD first for some helpful customizations, e.g. setting your CPU architecture to optimize your Kernel.

**Comment by abdulbadii** [comment]
So sorry, different with and without edge ?

**Comment by figue** [comment]
> So sorry, I'd look preferably for best media streaming performance, more explanation the difference between with and without edge, anbox, lts, etc etc and many other kinds of xanmod ?

Please see official page:

https://xanmod.org/#install_via_apturl

**Comment by figue** [comment]
https://aur.archlinux.org/packages/linux-xanmod-edge-linux-bin-x64v2

https://aur.archlinux.org/packages/linux-xanmod-edge-linux-headers-bin-x64v2
