### ISSUE TITLE
minor error with kernel xanmod 5.3.6-xanmod5

### ISSUE THREAD

**Issue by ionutnechita** [xanmod/linux#28]
Linux ionutn 5.3.6-xanmod5 #1.191012 SMP PREEMPT Sat Oct 12 00:48:59 -03 2019 x86_64 x86_64 x86_64 GNU/Linux

I noticed that it takes longer until the kernel starts completely.

root@ionutn:/home/ionutn# systemd-analyze time
_Startup finished in 6.005s (kernel) + 18.273s (userspace) = 24.278s_
graphical.target reached after 13.840s in userspace

root@ionutn:/home/ionutn# dmesg -l err
[    2.524072] piix4_smbus 0000:00:07.3: SMBus Host Controller not enabled!
[    2.932544] sd 8:0:0:0: [sda] Assuming drive cache: write through
[   19.617250] aufs aufs_fill_super:915:mount[955]: no arg
[   19.701290] overlayfs: missing 'lowerdir'

root@ionutn:/home/ionutn# cat /etc/os-release
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

> [    0.000000] Linux version 5.3.6-xanmod5 (root@mascote) (gcc version 9.2.1 20191008 (Debian 9.2.1-9)) #1.191012 SMP PREEMPT Sat Oct 12 00:48:59 -03 2019
> [    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.3.6-xanmod5 root=/dev/mapper/ubuntu--vg-ubuntu--lv ro debian-installer/custom-installation=/custom find_preseed=/preseed.cfg auto preseed/file=/floppy/preseed.cfg automatic-ubiquity noprompt priority=critical locale=en_US console-setup/modelcode=evdev
> [    0.000000] KERNEL supported cpus:
> [    0.000000]   Intel GenuineIntel
> [    0.000000]   AMD AuthenticAMD
> [    0.000000]   Hygon HygonGenuine
> [    0.000000]   Centaur CentaurHauls
> [    0.000000]   zhaoxin   Shanghai
> 
> [    0.000000] DMI: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 04/13/2018
> [    0.000000] Hypervisor detected: VMware
> 

[dmesg.log](https://github.com/xanmod/linux/files/3736260/dmesg.log)
[journalctl.log](https://github.com/xanmod/linux/files/3736289/journalctl.log)

**Comment by ionutnechita** [comment]
with kernel stock - ubuntu
ionutn@ionutn:~$ systemd-analyze time
Startup finished in 4.750s (kernel) + 18.815s (userspace) = 23.566s
graphical.target reached after 14.139s in userspace

**Comment by xanmod** [comment]
Solves w/ 5.4.8+?

**Comment by ionutnechita** [comment]
not solved.
i try now and this issue is present on boot.

ubuntu 5.4.0-9-generic
step 1 - 5.4.0-9-generic
root@ubuntu:/home/ionutnechita# systemd-analyze time
Startup finished in 3.717s (kernel) + 13.172s (userspace) = 16.889s
graphical.target reached after 13.091s in userspace

step 2 - 5.4.0-9-generic
root@ubuntu:~# systemd-analyze time
Startup finished in 3.379s (kernel) + 34.328s (userspace) = 37.707s
graphical.target reached after 34.254s in userspace

step 3 - 5.4.0-9-generic
root@ubuntu:~# systemd-analyze time
Startup finished in 3.492s (kernel) + 14.207s (userspace) = 17.699s
graphical.target reached after 14.120s in userspace

ubuntu 5.4.10-xanmod6
step 1 - ubuntu 5.4.10-xanmod6
root@ubuntu:/home/ionutnechita# systemd-analyze time
Startup finished in 4.764s (kernel) + 33.012s (userspace) = 37.777s
graphical.target reached after 32.852s in userspace

step 2 - ubuntu 5.4.10-xanmod6
root@ubuntu:~# systemd-analyze time
Startup finished in 4.848s (kernel) + 15.037s (userspace) = 19.885s
graphical.target reached after 14.859s in userspace

step 3 - ubuntu 5.4.10-xanmod6
root@ubuntu:/home/ionutnechita# systemd-analyze time
Startup finished in 4.734s (kernel) + 14.765s (userspace) = 19.499s
graphical.target reached after 14.700s in userspace
