### ISSUE TITLE
5.18.8 missing duplicate NVMe drive

### ISSUE THREAD

**Issue by ashmrtn** [xanmod/linux#280]
There appears to be a bug in the mainline kernel that prevents NVMe drives from the same vendor appearing in some cases due to a nsid clash. This is currently happening with two sk hynix drives I have (of different sizes). A couple of threads I've dug up seem to indicate that a quirk need to be added to the kernel to fix this

thread 1: https://forum.proxmox.com/threads/only-one-of-two-nvme-detected-in-linux-duplicate-subnqn.54480/
thread 2: https://lore.kernel.org/linux-nvme/20220613175745.GB15847@lst.de/T/

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/84302918a93a694f9f94fd49308f158bd2682db5
