### ISSUE TITLE
Multi-threaded CPU decompression SquashFS 

### ISSUE THREAD

**Issue by Drsheppard01** [xanmod/linux#281]
Follow this issues https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1980861
That's help to upgrade performance of Snaps, AppImages, Linux kernel when you start PC and other stuffs, which use SquashFS

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/df1e87b93b3216f6b7f064b5eeaf244d664d91cb
