### ISSUE TITLE
VFIO-PCI impossible to passthrought GPU

### ISSUE THREAD

**Issue by Wiedzmin89** [xanmod/linux#282]
Recently I've been forwarding the GPU to a QEMU/KVM Virtual Machine.
This process involves the vfio-pci kernel module. Before starting the client system, you need to connect this module, and after turning client system off - remove this module.
After changes from https://github.com/xanmod/linux/issues/42, it is not possible to remove the module, because it's build-in.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/df1e87b93b3216f6b7f064b5eeaf244d664d91cb
