### ISSUE TITLE
AMD pstate fix for certain laptops

### ISSUE THREAD

**Issue by cybik** [xanmod/linux#283]
amd-pstate seems to be broken right now for certain laptops and/or CPUs.

Per  @superm1 over [on gitlab](https://gitlab.freedesktop.org/drm/amd/-/issues/2106), can you pull in the following commit for the next build/s?

```
https://github.com/torvalds/linux/commit/09073396ea62d0a10b03f5661dcabfd8eca3f098
```

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/75f47a64bf8a471ef4f4f2e63d5593604a0cb41c

**Comment by cybik** [comment]
Confirmed, this made the p-state shenanigans work again on 5.18.15 on my laptop.
