### ISSUE TITLE
Toshiba Laptop battery 0% problem 

### ISSUE THREAD

**Issue by noobandnothing** [xanmod/linux#284]
Hello bro,
Thanks for your kernel ,I always use it.
Excuse me, My laptop always show 0% battery .
This issue happens with all distro

I tried much but I failed .
To be honest  (I) , I tracked issue and found that issue started with kernel 4.15 (It was working until 4.14.X).
I knew from trying all old ubuntu distro , I found that it was working with 16.04.6 (with kernel 4.4)and issue started with 16.04.7(with kernel 4.15) .
I tried all version until I found that issue happens with 4.15 or higher (until now).

[dmesg-4.4.x.txt](https://github.com/xanmod/linux/files/9245338/dmesg-4.4.x.txt)
[dmesg-4.15.x.txt](https://github.com/xanmod/linux/files/9245342/dmesg-4.15.x.txt)
[5.18.15-xanmod1.txt](https://github.com/xanmod/linux/files/9245347/5.18.15-xanmod1.txt)

![Screenshot_20220802_221113](https://user-images.githubusercontent.com/93285839/182464565-14c17ea5-60b1-44da-9666-feab45141eb0.png)
![Screenshot_20220802_221125](https://user-images.githubusercontent.com/93285839/182464471-b825c887-8c0e-41f7-9e03-6f1486dcce26.png)

**Comment by xanmod** [comment]
Have you tried with a recent distribution?

Recent kernel versions should be supported with current Debian and Ubuntu LTS distributions. Apparently this problem is due to the outdated linux-firmware package.

**Comment by noobandnothing** [comment]
I am using last Kubuntu 22.04 with latest kernel ,also I made sure that linux-firmware package is installed.
Also I tried with ubuntu ,debian , fedora,archlinux , All has the issue (0% battery perentage)
![Screenshot_20220802_224717](https://user-images.githubusercontent.com/93285839/182470731-9b3c0d9d-82bb-40b7-8c31-43f30f3fa8b6.png)
.

**Comment by xanmod** [comment]
I found this possible solution in several forums.

1. Try adding this kernel parameter in _/etc/default/grub_:
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash **acpi=copy_dsdt**"
2. `sudo update-grub`
3. `reboot`

Ref. https://www.linuxquestions.org/questions/slackware-14/battery-detection-issue-acpi-878227/

**Comment by noobandnothing** [comment]
Thanks bro for replying ,Unfortunately it is not fixed !
IDK if Changes which were added in 4.15 caused this issue until now !
https://kernelnewbies.org/Linux_4.15

**Comment by xanmod** [comment]
Try:
`acpi_osi=Linux`
`acpi_osi=!`
`acpi_osi=Windows`

**Comment by noobandnothing** [comment]
Tried to put 3 props in GRUB_CMDLINE_LINUX_DEFAULT (one by one )   but unfortunately it is not fixed !

**Comment by xanmod** [comment]
Copy here `upower -i /org/freedesktop/UPower/devices/battery_BAT0` output

**Comment by noobandnothing** [comment]
upower -i /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               TKBSS
  model:                NS2P3SZMC4WR
  power supply:         yes
  updated:              Fri 12 Aug 2022 11:14:18 PM EET (88 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               empty
    warning-level:       none
    energy:              0 Wh
    energy-empty:        0 Wh
    energy-full:         88.8 Wh
    energy-full-design:  88.8 Wh
    energy-rate:         0 W
    charge-cycles:       N/A
    percentage:          0%
    capacity:            100%
    technology:          lithium-ion
    icon-name:          'battery-empty-symbolic'

**Comment by noobandnothing** [comment]
I found this : https://linux-hardware.org/?probe=14ac6c1f51&log=upower

Same battery model and it doesn't have this issue !
then something else should be the cause.

**Comment by noobandnothing** [comment]
hello pro I found the cause :
It is if statment was added in 4.19.86 kernel 
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/drivers/acpi/acpica/evregion.c?id=v4.19.86&id2=v4.19.85

**Comment by noobandnothing** [comment]
I tried to remove it , Thanks God battery is working now .
[0001-Bypass-for-fixing-Toshiba-battery.patch.txt](https://github.com/xanmod/linux/files/9610561/0001-Bypass-for-fixing-Toshiba-battery.patch.txt)


Do you see any better solution  if yes please add it to xanmod kernel ?


![Screenshot_20220920_205916](https://user-images.githubusercontent.com/93285839/191342156-cf9389e4-c824-4467-bcc8-eb3b3a3a3283.png)

**Comment by noobandnothing** [comment]
ok issue relates to ACPI_ADR_SPACE_SYSTEM_MEMORY , idk how !
here is patch 
[0001-ACPI-Bypass-for-my-toshiba-power-issue.patch.txt](https://github.com/xanmod/linux/files/9614826/0001-ACPI-Bypass-for-my-toshiba-power-issue.patch.txt)

**Comment by noobandnothing** [comment]
problem was fixed starting from  kernel 6.2 by adding FFH OpRegion support
CONFIG_ACPI_FFH
