### ISSUE TITLE
Complete lack of moderation on the XanMod forums.

### ISSUE THREAD

**Issue by subanz** [xanmod/linux#289]
Currently on the General Discussions section in the Project Related part of the forum the first two pages are spam that has been there since March. Its possible this is the case in other sections of the forum as well.

https://forum.xanmod.org/forum-5.html

For all the work and effort that goes into maintaining these kernels it doesn't inspire a large amount of confidence in using the kernel by users when the forums are filled with spam that links to possibly dangerous websites.

Please take down theses threads and make an effort to better secure the forums or disable them completely if there is nobody who can devote the time and energy to moderate them.

**Comment by xanmod** [comment]
Forum register disabled, only for preview at moment.
