### ISSUE TITLE
Freezes on AMD Ryzen 5 2500U@ 5.4.0-xanmod0

### ISSUE THREAD

**Issue by londere** [xanmod/linux#29]
Hi, after update xanmod kernel on 5.4.0-xanmod0, the system starts normally after getting in the OS, it continuously starts to freeze and I need to push the power off and the system keeps normally.

OS: Debian 10
Kernel: 5.4.0-xanmod0
CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
Desktop: Mate 1.20.5

**Comment by xanmod** [comment]
Please, send your compressed kern.log.xz here for analysis.

`xz -ke9 /var/log/kern.log`

**Comment by londere** [comment]
done here's the file:
[https://mega.nz/#!hVMThSzI!5MqPPzV43wi6yusSm8hoAU9Ct9WzRkDvttw-Ttw2Lgo](url)

**Comment by xanmod** [comment]
Ref.: https://github.com/jakeday/linux-surface/issues/350

In terminal:
1. switch to root session: `su`
2. `echo 'blacklist evbug' > /etc/modprobe.d/blacklist-evbug.conf`
3. reboot

This may stop freezing your system.

**Comment by londere** [comment]
After blacklisting the module, I still have the issue, any thoughts?

**Comment by xanmod** [comment]
Is the firmware-linux package installed?
Send me your kern.log again now with evbug disabled.

**Comment by londere** [comment]
Attached apt list and kernel log, I made a new file for kern.log
[apt.txt](https://github.com/xanmod/linux/files/3906255/apt.txt)
[kern.log](https://github.com/xanmod/linux/files/3906256/kern.log)

**Comment by xanmod** [comment]
I will soon release a stable and updated libdrm-amdgpu1 for debian. The current version is 2.4.100, Debian buster 2.4.97-1.

**Comment by londere** [comment]
After install 5.4.1-xanmod1 issue was solved, thanks for the support.
