### ISSUE TITLE
Problem with screen resolution and Nvidia drivers after installing the kernel 5.18.18 on Ubuntu 22.04

### ISSUE THREAD

**Issue by VanquisherSenya** [xanmod/linux#292]
After installing xanmod kernel 5.18.18 on Ubuntu 22.04, my screen resolution dropped to 4:3, Nvidia settings stopped opening. I am using latest nvidia driver 515.
When I try to open the driver settings, it outputs the following:
ERROR: NVIDIA driver is not loaded

(nvidia-settings:15789): GLib-GObject-CRITICAL **: 17:59:13.262: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

** (nvidia-settings:15789): CRITICAL **: 17:59:13.263: ctk_powermode_new: assertion '(ctrl_target != NULL) && (ctrl_target->h != NULL)' failed

ERROR: nvidia-settings could not find the registry key file or the X server is
       not accessible. This file should have been installed along with this
       driver at
       /usr/share/nvidia/nvidia-application-profiles-key-documentation. The
       application profiles will continue to work, but values cannot be
       prepopulated or validated, and will not be listed in the help text.
       Please see the README for possible values and descriptions.

** Message: 17:59:13.308: PRIME: No offloading required. Abort
** Message: 17:59:13.308: PRIME: is it supported? no

**Comment by WillyCB** [comment]
I second that. Nvidia kernel modules are not compiling for kernel 5.18.18 on Ubuntu 22.04

Error! Bad return status for module build on kernel: 5.18.18-xanmod1 (x86_64)
[make.log](https://github.com/xanmod/linux/files/9387701/make.log)

**Comment by holzbit** [comment]
Same Problem on Ubuntu 20.04

Setting up linux-headers-5.18.18-xanmod1 (5.18.18-xanmod1-0~20220817.gitec586ab) ...
Setting up linux-image-5.18.18-xanmod1 (5.18.18-xanmod1-0~20220817.gitec586ab) ...
 * dkms: running auto installation service for kernel 5.18.18-xanmod1       ESC[80G 
Kernel preparation unnecessary for this kernel.  Skipping...
applying patch disable_fstack-clash-protection_fcf-protection.patch...patching file Kbuild
Hunk #1 succeeded at 82 (offset 11 lines).


Building module:
cleaning build area...
unset ARCH; [ ! -h /usr/bin/cc ] && export CC=/usr/bin/gcc; env NV_VERBOSE=1 'make' -j8 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=5.18.18-xanmod1 IGNORE_XEN_PRESENCE=1 IGNORE_CC_MISMATCH=1 SYSSRC=/lib/modules/5.18.18-xanmod1/build LD=/usr/bin/ld.bfd modules.......(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-5.18.18-xanmod1 is not supported
Error! Bad return status for module build on kernel: 5.18.18-xanmod1 (x86_64)
Consult /[make.log](https://github.com/xanmod/linux/files/9389685/make.log) for more information.
^MESC[74G[ OK ]

**Comment by xanmod** [comment]
5.18.19-xanmod1 and 5.19.3-xanmod1 dkms built ok.

**Comment by WillyCB** [comment]
I can confirm. 5.18.19-xanmod1 and 5.19.3-xanmod1 are fine. Thank you, Alexandre

**Comment by VanquisherSenya** [comment]
I installed 5.19.3-xanmod1 and my problem was only half solved. My screen resolution came back, but only after uninstalling the nvidia drivers, they have the same problem as before.

**Comment by holzbit** [comment]
I can confirm, 5.18.19-xanmod1 fixed it for me on Ubuntu 20.04 too. Thank you very much.
