### ISSUE TITLE
xanmod 5.19 breaks systemd-cryptenroll / tpm support

### ISSUE THREAD

**Issue by simontretter** [xanmod/linux#300]
Both the default Arch kernels 5.18.x, 5.19.x and Xanmod 5.18.x reliably can take their LUKS secret from the tpm2 chip after it is enrolled with systemd-cryptenroll. 

However Xanmod 5.19 breaks this functionality (same config as the working 5.18) with fallback on having to enter the passphrase (if there is one stored in a LUKS slot).

Not sure where to look for useful debug info.

**Comment by xanmod** [comment]
To confirm, could you build a kernel with CONFIG_KEXEC_PURGATORY_SKIP_SIG disabled?

**Comment by simontretter** [comment]
Thank you for your attention to this issue.

`grep CONFIG_KEXEC_PURGATORY_SKIP_SIG ~/.config/linux-xanmod/myconfig
9:scripts/config --disable CONFIG_KEXEC_PURGATORY_SKIP_SIG`

`grep CONFIG_KEXEC_PURGATORY_SKIP_SIG ~/.cache/yay/linux-xanmod/config.last 
509:# CONFIG_KEXEC_PURGATORY_SKIP_SIG is not set`

Same issue with this option disabled, dracut/luks fail to take the secret from tpm.

**Comment by xanmod** [comment]
Send /var/log/kern.log, syslog and `dmesg > dmesg.log` from arch and xanmod 5.19.

**Comment by simontretter** [comment]
Here's the dmesg and journalctl -b for both Arch and Xanmod 5.19.9.
[dmesg.arch.txt](https://github.com/xanmod/linux/files/9597405/dmesg.arch.txt)
[dmesg.xanmod.txt](https://github.com/xanmod/linux/files/9597406/dmesg.xanmod.txt)
[journal.arch.txt](https://github.com/xanmod/linux/files/9597407/journal.arch.txt)
[journal.xanmod.txt](https://github.com/xanmod/linux/files/9597408/journal.xanmod.txt)

**Comment by simontretter** [comment]
Found the issue. xnamod enabled 'CONFIG_IMA' which is disabled on other kernels. Disabling 'CONFIG_IMA' fixes the issue for me.
