### ISSUE TITLE
[Feature request] Fullcone NAT for nftables

### ISSUE THREAD

**Issue by huyz-git** [xanmod/linux#310]
xanmod kernel had already added fullcone nat support for legacy xtables https://github.com/xanmod/linux/commit/58db8824f8d7b598961275348e544bffbcc5a16d
It will be great if it could also add fullcone nat support for nftables: https://github.com/fullcone-nat-nftables/nft-fullcone

**Comment by Danny3** [comment]
Is this the reason why OpenSnitch application firewall is not working with this kernel version?
