### ISSUE TITLE
is LTS no longer maintained?

### ISSUE THREAD

**Issue by enihcam** [xanmod/linux#312]
I see it being removed from the portal.
LTS is very important for those headless devices like server, router, NAS that need less frequent in customizing kernel config.
It's at least more important than `Latest Mainline (NEXT)` & `Stable Real-time (RT)`.
Please keep LTS alive. (or maybe stick `Stable Real-time (RT)` releases with LTS kernel?)

**Comment by figue** [comment]
For now, the branch is in github (https://github.com/xanmod/linux/tree/5.15.72-xanmod1) and in xanmod.org is listed.

**Comment by enihcam** [comment]
> For now, the branch is in github (https://github.com/xanmod/linux/tree/5.15.72-xanmod1) and in xanmod.org is listed.

does that mean no more updates?
