### ISSUE TITLE
linux6.0.2-rt-xanmod does not build ZFS module

### ISSUE THREAD

**Issue by bugcrazy** [xanmod/linux#315]
The common version 6.0.3 builds the ZFS module without any problems. Also  linux6.0.2-rt-xanmod version does not have the dvb.h files.

**Building DKMS module: zfs-2.1.6... FAILED!**

**Generating kernel module dependency lists... done.**

**Executing post-install kernel hook: 20-initramfs ...**

**grep: warning: stray \ before /**

**grep: warning: stray \ before /**

**dracut-install: Failed to find module 'zfs'**

**dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.b6n1va/initramfs --kerneldir /lib/modules/6.0.2-rt11-xanmod1_1/ -m zfs**

**dracut: installkernel failed in module zfs**

**Executing post-install kernel hook: 50-efibootmgr ...**

**Executing post-install kernel hook: 50-refind ...**

**linux6.0-rt-xanmod-6.0.2_1: installed successfully.**

**linux6.0-rt-xanmod-dbg-6.0.2_1: configuring ...**

**linux6.0-rt-xanmod-dbg-6.0.2_1: installed successfully.**

**linux6.0-rt-xanmod-headers-6.0.2_1: configuring ...**

**linux6.0-rt-xanmod-headers-6.0.2_1: installed successfully.**

**Comment by xanmod** [comment]
Report this issue to the openZFS team

**Comment by xanmod** [comment]
https://github.com/openzfs/zfs/issues
