### ISSUE TITLE
minor error with kernel xanmod 5.4.6-xanmod5 

### ISSUE THREAD

**Issue by Javsen** [xanmod/linux#32]
Linux javsen-ThinkPad-E495 5.4.6-xanmod4 #1.191221 SMP PREEMPT Sat Dec 21 23:18:37 -03 2019 x86_64 x86_64 x86_64 GNU/Linux

My English is not well..
my mobile disk  is connect to my computer have some error.

like this.
cannot access 'Seagate Expansion Drive': Transport endpoint is not connected

i'm not sure this is kernel  error.
beause have some error for previous version.

if speak not well .... so chinese

不知道是否是新版本的问题,我在没有更换内核之前应该是可以正常连接移动硬盘的.
但是当我换到这个内核之后就报出一个无法连接设备的错误.
就像这样:
cannot access 'Seagate Expansion Drive': Transport endpoint is not connected

**Comment by Javsen** [comment]
i try use disk is can connect.

**Comment by Javsen** [comment]
i use ubuntu 18.04.3 version.

**Comment by Javsen** [comment]
Disk /dev/loop0: 156.7 MiB, 164290560 bytes, 320880 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop1: 3.7 MiB, 3821568 bytes, 7464 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop2: 144.8 MiB, 151769088 bytes, 296424 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop3: 14.8 MiB, 15458304 bytes, 30192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop4: 89.1 MiB, 93417472 bytes, 182456 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop5: 173.4 MiB, 181846016 bytes, 355168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop6: 956 KiB, 978944 bytes, 1912 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop7: 54.6 MiB, 57274368 bytes, 111864 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/nvme0n1: 477 GiB, 512110190592 bytes, 1000215216 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 3D859175-A587-405C-BFD8-649CBBD8D251

Device           Start        End   Sectors   Size Type
/dev/nvme0n1p1    2048    1050623   1048576   512M EFI System
/dev/nvme0n1p2 1050624    2549759   1499136   732M Linux filesystem
/dev/nvme0n1p3 2549760 1000214527 997664768 475.7G Linux filesystem


Disk /dev/mapper/nvme0n1p3_crypt: 475.7 GiB, 510802264064 bytes, 997660672 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/ubuntu--vg-root: 474.8 GiB, 509771513856 bytes, 995647488 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/ubuntu--vg-swap_1: 980 MiB, 1027604480 bytes, 2007040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop8: 4.2 MiB, 4403200 bytes, 8600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop9: 44.2 MiB, 46325760 bytes, 90480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop10: 3.7 MiB, 3825664 bytes, 7472 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop11: 8.5 MiB, 8945664 bytes, 17472 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop12: 54.6 MiB, 57274368 bytes, 111864 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop13: 156 MiB, 163614720 bytes, 319560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop14: 8.5 MiB, 8941568 bytes, 17464 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop15: 4.2 MiB, 4403200 bytes, 8600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop16: 956 KiB, 978944 bytes, 1912 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop17: 14.8 MiB, 15462400 bytes, 30200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop18: 173.4 MiB, 181846016 bytes, 355168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop19: 144.6 MiB, 151646208 bytes, 296184 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop20: 42.8 MiB, 44879872 bytes, 87656 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop21: 89.1 MiB, 93429760 bytes, 182480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sdb: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0xd69422af

Device     Boot Start        End    Sectors   Size Id Type
/dev/sdb1  *       64 1953520128 1953520065 931.5G  7 HPFS/NTFS/exFAT

this is my disk info. the last is mobile disk.

**Comment by Javsen** [comment]
i try to look disk information .but fail.
shell:
sudo hdparm -i /dev/sdb1
info:
HDIO_GET_IDENTITY failed: Invalid argument

**Comment by Javsen** [comment]
this is log .. /var/sys/syslog

Dec 23 15:20:56 javsen-ThinkPad-E495 ntfs-3g[16917]: Version 2017.3.23 integrated FUSE 28
Dec 23 15:20:56 javsen-ThinkPad-E495 ntfs-3g[16917]: Mounted /dev/sda1 (Read-Write, label "Seagate Expansion Drive", NTFS 3.1)
Dec 23 15:20:56 javsen-ThinkPad-E495 ntfs-3g[16917]: Cmdline options: rw,nodev,nosuid,uid=1000,gid=1000,uhelper=udisks2
Dec 23 15:20:56 javsen-ThinkPad-E495 ntfs-3g[16917]: Mount options: rw,nodev,nosuid,uhelper=udisks2,allow_other,nonempty,relatime,default_permissions,fsname=/dev/sda1,blkdev,blksize=4096
Dec 23 15:20:56 javsen-ThinkPad-E495 ntfs-3g[16917]: Global ownership and permissions enforced, configuration type 7
Dec 23 15:20:56 javsen-ThinkPad-E495 ntfs-3g[16917]: Unmounting /dev/sda1 (Seagate Expansion Drive)
Dec 23 15:20:56 javsen-ThinkPad-E495 systemd[1]: Started Clean the /media/javsen/Seagate Expansion Drive mount point.
Dec 23 15:20:56 javsen-ThinkPad-E495 udisksd[1320]: Mounted /dev/sda1 at /media/javsen/Seagate Expansion Drive on behalf of uid 1000
Dec 23 15:20:56 javsen-ThinkPad-E495 dbus-daemon[4048]: [session uid=1000 pid=4048] Activating service name='org.gnome.Shell.HotplugSniffer' requested by ':1.16' (uid=1000 pid=4343 comm="/usr/bin/gnome-shell ")
Dec 23 15:20:56 javsen-ThinkPad-E495 dbus-daemon[4048]: [session uid=1000 pid=4048] Successfully activated service 'org.gnome.Shell.HotplugSniffer'
Dec 23 15:21:06 javsen-ThinkPad-E495 org.gnome.Shell.desktop[4343]: [9097:9117:1223/152106.056328:ERROR:socket_stream.cc(218)] Closing stream with result -2

**Comment by Javsen** [comment]
oh i find error. disk is ntfs can not read.... why?  ubuntu have  mount-3g. why can't read..

**Comment by xanmod** [comment]
Can you tell if this identification problem persists in current kernel versions as well generic (stock)?

**Comment by Javsen** [comment]
> Can you tell if this identification problem persists in current kernel versions as well generic (stock)?
i'm sure current version have problem.but i'm not sure other version.maybe is mount-3g problem. i format my disk to exfat.  exfat can to read file.so i think is mount-3g problem.may be..]
