### ISSUE TITLE
I/O information is not available due to CONFIG_TASK_DELAY_ACCT not enabled

### ISSUE THREAD

**Issue by nazar-pc** [xanmod/linux#326]
`iotop` complains:
> CONFIG_TASK_DELAY_ACCT not enabled in kernel, cannot determine SWAPIN and IO %

Generic Ubuntu 5.15 kernel has this option enabled though. Maybe it was lost somewhere in the process and it is time to update config to align closer with Ubuntu?

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/6e42d06618d376a06aec6155206f50d6b7a25ff0/CONFIGS/xanmod/gcc/config#L137
https://github.com/xanmod/linux/blob/629e4bb965817e2a354c62ef30043143299497fe/CONFIGS/xanmod/gcc/config_x86-64-v1#L145


If you installed a newer kernel for your distribution, would you agree to consider installing the newer iotop as well?

https://packages.debian.org/sid/amd64/iotop
https://packages.debian.org/sid/amd64/iotop-c

**Comment by nazar-pc** [comment]
Hm... iotop-c seems to work, while iotop doesn't (this is on Ubuntu 22.04).
I guess there is nothing wrong with the kernel, thanks!
