### ISSUE TITLE
Include patch to restore MST hub functionality with AMD GPUs

### ISSUE THREAD

**Issue by Slater91** [xanmod/linux#335]
Hello!

As evidenced by [this bug report](https://gitlab.freedesktop.org/drm/amd/-/issues/2171#note_1724186), it is currently impossible to use external docks or daisy-chained displays with AMD GPUs using the 6.1 kernel. There is a patch available that restores the functionality, but it has currently not been accepted yet and it looks like it might take some time for it to finally land. This means people with an AMD GPU won't be able to use their docks or daisy-chained displays with recent versions of the kernel until the patch is finally included in DRM. In my case, I cannot use the 6.1 kernel with my HP USB-C docking station because the UI just freezes and forces me to do a hard reset, and due to issue #321 I cannot use kernel 6.0 either, so I am stuck on kernel 5.19.15 which is not supported any more.

Would it be possible to apply the linked patch to Xanmod so the functionality is restored?

Thank you!

**Comment by xanmod** [comment]
2528ea75becdd35c82ac5d88e598e5f90e962818

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/be6bf2321343592f879176f8a02bfbea2b615826
