### ISSUE TITLE
Bluetooth 5.3 adapter Ugreen CM591 (chip ATS2851)

### ISSUE THREAD

**Issue by ShevT** [xanmod/linux#337]
Does not work.
Maybe it will be enough to add [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git/commit/?id=0bb039f39058)? ([patchwork](https://patchwork.kernel.org/project/bluetooth/patch/20221216201247.297210-1-marcel@holtmann.org/))

Dmesg:
```
[  127.272121] usb 3-4: new full-speed USB device number 3 using xhci_hcd
[  127.432156] usb 3-4: New USB device found, idVendor=10d7, idProduct=b012, bcdDevice=88.91
[  127.432163] usb 3-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  127.432165] usb 3-4: Product: general adapter
[  127.432166] usb 3-4: Manufacturer: Actions
[  127.432168] usb 3-4: SerialNumber: ACTIONS1234
[  127.511198] Bluetooth: hci0: Opcode 0x c5a failed: -56
```

**Comment by xanmod** [comment]
00f4b7c036814009e54ae2841c188fe064717ddf

**Comment by ShevT** [comment]
6.1.8-x64v1-xanmod1

```
[    3.240475] Bluetooth: Core ver 2.22
[    3.240489] NET: Registered PF_BLUETOOTH protocol family
[    3.240490] Bluetooth: HCI device and connection manager initialized
[    3.240492] Bluetooth: HCI socket layer initialized
[    3.240493] Bluetooth: L2CAP socket layer initialized
[    3.240495] Bluetooth: SCO socket layer initialized
[    3.412251] Bluetooth: hci0: HCI Read Default Erroneous Data Reporting command is advertised, but not supported.
[    3.467387] Bluetooth: hci0: Opcode 0x204b failed: -56
[    4.030187] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    4.030191] Bluetooth: BNEP filters: protocol multicast
[    4.030195] Bluetooth: BNEP socket layer initialized
```
Что-то изменилось, но есть ошибка и не работает

```
[  192.180422] Bluetooth: hci0: HCI Read Default Erroneous Data Reporting command is advertised, but not supported.
[  192.241149] Bluetooth: hci0: Opcode 0x204b failed: -56
```

**Comment by anjiahao1** [comment]
hi,i try [00f4b7](https://github.com/xanmod/linux/commit/00f4b7c036814009e54ae2841c188fe064717ddf) this patch,but it not work, get this
`[36670.898860] usb 1-6.2: new full-speed USB device number 6 using xhci_hcd
[36671.004557] usb 1-6.2: New USB device found, idVendor=10d7, idProduct=b012, bcdDevice=88.91
[36671.004560] usb 1-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[36671.004562] usb 1-6.2: Product: general adapter
[36671.004562] usb 1-6.2: Manufacturer: Actions
[36671.004563] usb 1-6.2: SerialNumber: ACTIONS1234
[36671.052495] Bluetooth: Core ver 2.22
[36671.052526] NET: Registered PF_BLUETOOTH protocol family
[36671.052527] Bluetooth: HCI device and connection manager initialized
[36671.052531] Bluetooth: HCI socket layer initialized
[36671.052533] Bluetooth: L2CAP socket layer initialized
[36671.052535] Bluetooth: SCO socket layer initialized
[36671.058909] usbcore: registered new interface driver btusb
[36671.087305] Bluetooth: hci0: Opcode 0x c5a failed: -56
[36671.142358] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[36671.142361] Bluetooth: BNEP filters: protocol multicast
[36671.142366] Bluetooth: BNEP socket layer initialized
`

**Comment by un-couteau** [comment]
![изображение](https://github.com/xanmod/linux/assets/65289168/5f9f3ffa-ed0f-49c6-99dc-c502ea2e4551)
It's almost half a year later and it still doesn't work.
Or maybe I'm doing something wrong?

**Comment by ShevT** [comment]
Yes, it still doesn't work

```
[    3.134753] Bluetooth: Core ver 2.22
[    3.135059] NET: Registered PF_BLUETOOTH protocol family
[    3.135061] Bluetooth: HCI device and connection manager initialized
[    3.135065] Bluetooth: HCI socket layer initialized
[    3.135068] Bluetooth: L2CAP socket layer initialized
[    3.135072] Bluetooth: SCO socket layer initialized
[    3.164432] Bluetooth: hci0: HCI Read Default Erroneous Data Reporting command is advertised, but not supported.
[    3.218694] Bluetooth: hci0: Opcode 0x204b failed: -56
[    4.096490] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    4.096493] Bluetooth: BNEP filters: protocol multicast
[    4.096496] Bluetooth: BNEP socket layer initialized
```

`[    3.218694] Bluetooth: hci0: Opcode 0x204b failed: -56`

6.3.2-x64v1-xanmod1

**Comment by numeropi** [comment]
It works using this kernel patch: 

Download from: https://sourceforge.net/projects/xanmod/files/releases/main/6.2.12-x64v4-xanmod1/
sudo dpkg -i linux-image-*xanmod*.deb linux-headers-*xanmod*.deb

**Comment by ShevT** [comment]
> It works using this kernel patch:
> 
> Download from: https://sourceforge.net/projects/xanmod/files/releases/main/6.2.12-x64v4-xanmod1/ sudo dpkg -i linux-image-_xanmod_.deb linux-headers-_xanmod_.deb

The phone is connected. BT headphones (Redmi buds 4 Pro) - no. Error connection.

**Comment by ShevT** [comment]
> It works using this kernel patch:
> 
> Download from: https://sourceforge.net/projects/xanmod/files/releases/main/6.2.12-x64v4-xanmod1/ sudo dpkg -i linux-image-_xanmod_.deb linux-headers-_xanmod_.deb

The phone is connected. BT headphones (Redmi buds 4 Pro) - no. Error connection.

`[    5.604131] Bluetooth: Core ver 2.22
[    5.604155] NET: Registered PF_BLUETOOTH protocol family
[    5.604156] Bluetooth: HCI device and connection manager initialized
[    5.604159] Bluetooth: HCI socket layer initialized
[    5.604161] Bluetooth: L2CAP socket layer initialized
[    5.604165] Bluetooth: SCO socket layer initialized
[    5.636564] Bluetooth: hci0: HCI Read Default Erroneous Data Reporting command is advertised, but not supported.
[    5.636570] Bluetooth: hci0: HCI Read Transmit Power Level command is advertised, but not supported.
[    5.636572] Bluetooth: hci0: HCI LE Set Random Private Address Timeout command is advertised, but not supported.
[   10.944753] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   10.944757] Bluetooth: BNEP filters: protocol multicast
[   10.944761] Bluetooth: BNEP socket layer initialized
[   10.947056] Bluetooth: MGMT ver 1.22
[   24.384594] Bluetooth: RFCOMM TTY layer initialized
[   24.384603] Bluetooth: RFCOMM socket layer initialized
[   24.384609] Bluetooth: RFCOMM ver 1.11`
