### ISSUE TITLE
enabled CONFIG_CC_HAS_ASM_INLINE break the compiling of some kernel modules with default gcc 5.x on ubuntu 16.04

### ISSUE THREAD

**Issue by pffang** [xanmod/linux#34]
The default gcc version of Ubuntu 16.04 is 5.x. It doesn't support the inline qualifier for asm.
The only supported qualifier is volatile.
    Refer to: https://gcc.gnu.org/onlinedocs/gcc-5.5.0/gcc/Basic-Asm.html
        & https://gcc.gnu.org/onlinedocs/gcc/Basic-Asm.html
I think, if xanmod want to support the old Ubuntu releases like Ubuntu 16.04, it's better to keep the compatible with default stable compiler on Ubuntu 16.04.

**Comment by xanmod** [comment]
Consider an gcc upgrade or ubuntu from 18.04 or later.
