### ISSUE TITLE
How to stay on 6.1 LTS?

### ISSUE THREAD

**Issue by mralusw** [xanmod/linux#345]
I see that `linux-xanmod-x64v*` has advanced to the unstable `6.2` kernel. How can I stay on the `6.1` branch, which is LTS until 2027 and seems the sane choice? Why is `6.2` not tagged as `-edge`?

**Comment by Ravi-Kishor** [comment]
Easy workarround is to manually install kernel, this is what I did

1. Installed 6.1.15, booted with 6.1.15...
2. Purged 6.2.2
3. Now with sudo apt/nala upgrade it doesn't show 6.2.2, but have to install newer kernels manually. 

***Imp Commands***

sudo apt install linux-image-6.1.15-x64v2-xanmod1

(replace x64v1/v2/v3 as per ur device)

apt list --installed | grep linux-image  

(check ur compatible version)

sudo apt purge linux-image-6.2.2-x64v2-xanmod1

(replace version with ur installed verion)

sudo apt autoclean

sido apt autoremove

**Comment by xanmod** [comment]
`sudo apt purge linux*xanmod* && sudo apt install linux-xanmod-lts-x64v3`

**Comment by mralusw** [comment]
Luckily it seems 6.1 is now the new LTS

> 3. Now with sudo apt/nala upgrade it doesn't show 6.2.2, but have to install newer kernels manually.

Hm, let's say I wanted to stay on 5.15 (since 6.1 is not a good example anymore, being the new default). Once no branches (LTS, edge or plain xanmod) point to 5.15 anymore, are newer 5.15 versions uploaded at all? I don't think so, it looks like you would have to compile from source, as others advised.

**Comment by ionutnechita** [comment]
Hi @mralusw,

I understand what you're saying, but 6.1 is the new LTS now, and it brings the best configurations and drivers to your device.

**Comment by mralusw** [comment]
> Hi @mralusw,
> 
> I understand what you're saying, but 6.1 is the new LTS now, and it brings the best configurations and drivers to your device.

Yes, that's what I wanted in the first place. (Just as an aside, newer kernel releases *can* drop support for older devices)

I was replying to @Ravi-Kishor. I don't think his method works, once no xanmod branches point to a specific kernel release branch. That's what I was saying.
