### ISSUE TITLE
Failure to prepare()

### ISSUE THREAD

**Issue by HunoErudhir** [xanmod/linux#360]
When I try to compile xanmod, it always gives the same error regardless of the PKGBUILD configuration. But when I use paru to install linux-xanmod, it compiles normally

This command I'm using: `env _microarchitecture=31 use_tracers=n use_numa=n _localmodcfg=y _compress_modules=y makepkg -sic`

.log of the build attempt: [kernel-build.log](https://github.com/xanmod/linux/files/11275558/kernel-build.log)

Distro: Arch Linux
(I already have base-devel and modprobed-db installed)

**Comment by figue** [comment]
Please, try again with a clean build: `env _microarchitecture=31 use_tracers=n use_numa=n _localmodcfg=y _compress_modules=y makepkg -sicC`

**Comment by HunoErudhir** [comment]
Now everything worked out
