### ISSUE TITLE
request: please keep older versions of META pkgs around for longer - until zfs can catch up

### ISSUE THREAD

**Issue by dreamcat4** [xanmod/linux#369]
Hi,
I have today been able to successfully pin my pkg versions of xanmod kernel to `6.2.x`, thanks to the following config file:

```sh
/etc/apt/preferences.d/zfs-compat-kernel-linux-image.pref:

# xanmod
# ============================================

Package: linux-xanmod-x64v1
Pin: version 6.2*
Pin-Priority: 550

Package: linux-xanmod-x64v4
Pin: version 6.2*
Pin-Priority: 550

Package: linux-xanmod-lts
Pin: version 6.2*
Pin-Priority: 550

Package: linux-xanmod-rt
Pin: version 6.2*
Pin-Priority: 550
```

This is because:

ZFS is not yet available / ready for the current 6.3 kernel. The problem however is that: xanmod debian repo already removed the `6.2` meta packages. For example "linux-xanmod" metapkg. Which is just merely a control file.

However you seem to be removing all of the older ones before the newest. This means there is no longer available and `6.2` metapkg onto which to pin the version. And it's deps have the version number baked in... so that doesn't actually work with apt pin version. Because it looses the ability to get updated over time.

So kindly, please I request that you don't keep removing older versions of these metpkgs. For example n-2. The reason for this request is because:

By the time zfs has updated to work with kernel 6.3 (the current one). Then surely linux upstream will have (by then) moved forwards to 6.4 kernel. At which time you will do newer xanmod builds for 6.4... and you will then replace the 6.3 metapkg with a 6.4 metapkg. Which is FINE... until you then immediately remove and take away the existing 6.3 metpkg and then (while I am still on 6.2)... I cannot simply jump and skip across the (now removed, never installed) 6.3 since... zfs won't be ready for 6.4 for another +1 month. Or several weeks typically.

Please consider that while I can manually hand-edit the control file of the other versions's metpkgs by hand each time... that is a tedious manual process. That is more something reserved for manually recovering from to restore a broken system state. Rather than something which could be more easily avoided...

I hope this request does not conflict with your other repo management. It is only requested because it is actually a needed feature here. Or for anybody else who needs to be lagging behind slightly. And wants to use the apt pinning feature to have some level of control for moving forwards on a delayed step.

Please consider this request, that for the way that these apt cache policy works... it should be pretty harmless so keep around some number of metapkgs. n-2 or n-3 minor releases is probably enough to be clear in terms for the zfs project.

**Comment by xanmod** [comment]
Use linux 6.1 lts for openzfs.

**Comment by dreamcat4** [comment]
Well it seems i can install both... and have the LTS around as a fallback. This is indeed a good idea. However it still does not mean you cannot consider such request around the debian repo.

In fact here on ubuntu... can't see any **`v4`** cpu version builds for those LTS meta pkgs. So would be loosing those optimizations. Which (for zfs being relatively slow FS in it's own processing), maybe it can be some little help to have those cpu optimizations included for. Not to mention other general driver improvements in newer kernels version... I still like to be able as new as it can possibly be.

Therefore  please still to consider this request: that the the META pkg deletions are being too aggressive from the apt repo. As you are still keeping along many gigabytes from the older kernel releases themselves. The meta pkg is only what? 26kb? of space to keep around. Just as being the pointer to those. It should remain available no? The APT system itself will ignore, and do all the version management to select right versions / superseed itself. That is how these debian repos are supposed to work as far as my understanding goes (if not was not other known previous issue).
