### ISSUE TITLE
i915 driver issue in 5.5.x. System freezes

### ISSUE THREAD

**Issue by figue** [xanmod/linux#37]
Reference bug in Archlinux:

https://bugs.archlinux.org/task/65392

Recently Arch merge several patches that fix for me issues with i915. It seems that until 5.6 will not be included in vanilla, so I'm testing in my laptop a patched Xanmod with them. Seems running fine  now. No freezes in all day. Without it I can't use Vanilla/Xanmod/Arch kernel more than a few minutes.

Patches I've applied:

https://git.archlinux.org/linux.git/patch/?id=1533cd73061e99ed6dd58cba03da2b762a616a95
https://git.archlinux.org/linux.git/patch/?id=4dfbfe187c731b4f33e1a66e70ca10854e469527
https://git.archlinux.org/linux.git/patch/?id=4e64b7d1a9e63f7b9c1cecc8995e6fc1fed42e77
https://git.archlinux.org/linux.git/patch/?id=167299b5c1cc6f0c1274271aec0ab2b9fec01594
https://git.archlinux.org/linux.git/patch/?id=e3d3fd13d0ac1e12848b4f2a57e9e4bf2b557bf0
https://git.archlinux.org/linux.git/patch/?id=89678e8921d00143665237e719f96cfc8425f804
https://git.archlinux.org/linux.git/patch/?id=bfe34ef7e07d52ada331df8e1c5938906693b950
https://git.archlinux.org/linux.git/patch/?id=52bc26b084be047fbc485f711dc2b88c0a1b2923
https://git.archlinux.org/linux.git/patch/?id=513cbef093293a7f0e331eb4fee8e6a1bb9bf5a2
https://git.archlinux.org/linux.git/patch/?id=2029f44eb483a6ab7c0bc017cb699b7084f5eab4

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/compare/84cc10485e76600c62053584860713a64f451b30...c40e2ac4202d2b072992537c7ba1093ee01ab628

Patches applied. Thanks.
