### ISSUE TITLE
Pipewire glitches out while gaming

### ISSUE THREAD

**Issue by Atemu** [xanmod/linux#373]
Since 6.3.4, pipewire starts glitching out after playing a CPU-intensive game for a while. Audio becomes and stays garbled for one or multiple applications; as if the quantum chosen was too small.  
I had configured a quantum even up to 256 which should most definitely be enough (usually, I had 128 while 64 was barely too small).

It's either the game or my voice chat that becomes garbled. I don't know whether the other becomes garbled too after a while since I'd restart pipewire when one of them breaks (I'd expect yes).

**Comment by xanmod** [comment]
Are the pipewire and wireplumber daemons at nice -11?

**Comment by Atemu** [comment]
RT 88; the default.

**Comment by Atemu** [comment]
False alarm it seems; the same happens on 6.3.3 too, so it's likely some other component that changed. I thought I had only changed the kernel.
