### ISSUE TITLE
CONFIG_DEBUG_INFO=y # CONFIG_DEBUG_INFO_REDUCED is not set CONFIG_DEBUG_INFO_BTF=y CONFIG_KPROBE_EVENTS=y CONFIG_BPF_EVENTS=y

### ISSUE THREAD

**Issue by newyorkthink** [xanmod/linux#375]
![image](https://github.com/xanmod/linux/assets/87791643/c00fe1f0-9068-4ebe-aa54-7e76a5e56507)

CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_INFO_REDUCED is not set
CONFIG_DEBUG_INFO_BTF=y
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y

there is not find

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/489fabdc10a99aa7fa9020e1c018b44685b562f1/CONFIGS/xanmod/gcc/config_x86-64-v3#L11670
