### ISSUE TITLE
i want to eat goose, but i use xanmod ,xanmod can not eat goose

### ISSUE THREAD

**Issue by newyorkthink** [xanmod/linux#376]
https://github.com/daeuniverse/dae

https://github.com/daeuniverse/dae/tree/main/docs/getting-started

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/489fabdc10a99aa7fa9020e1c018b44685b562f1/CONFIGS/xanmod/gcc/config_x86-64-v3#L11670
