### ISSUE TITLE
please add eBPF in xanmod

### ISSUE THREAD

**Issue by newyorkthink** [xanmod/linux#378]
![image](https://github.com/xanmod/linux/assets/87791643/5b4859ee-f5c9-4aa5-af84-1899d18cc759)

**Comment by newyorkthink** [comment]
https://github.com/daeuniverse/dae

**Comment by newyorkthink** [comment]
yes : 
zcat /proc/config.gz || cat /boot/{config,config-$(uname -r)}

i need:
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_CGROUPS=y
CONFIG_KPROBES=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_INFO_REDUCED is not set
CONFIG_DEBUG_INFO_BTF=y
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y

but xanmod is not 
CONFIG_DEBUG_INFO_REDUCED
CONFIG_DEBUG_INFO_BTF=y
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y

**Comment by Danny3** [comment]
I think somebody else asked about this too, in my issue:
https://github.com/xanmod/linux/issues/325#issuecomment-1564489956

**Comment by mdhishamsayed** [comment]
@newyorkthink what needs to be add/removed from the gcc configs to enable eBPF? any patch?

**Comment by newyorkthink** [comment]
> 

maybe ys , i don't not ：（

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/489fabdc10a99aa7fa9020e1c018b44685b562f1/CONFIGS/xanmod/gcc/config_x86-64-v3#L11670
