### ISSUE TITLE
 add zstd compression for kernel initramfs

### ISSUE THREAD

**Issue by alvin998179** [xanmod/linux#38]
Could you please add support for extracting ZSTD-compressed kernel images, as well as
ZSTD-compressed ramdisk images in the kernel boot process?

**Comment by figue** [comment]
@alvin998179 seems that this is already included or there is some additional patch that has to be merged?
```
figue@pluto ~ % zgrep ZSTD /proc/config.gz 
CONFIG_SQUASHFS_ZSTD=y
CONFIG_PSTORE_ZSTD_COMPRESS=y
CONFIG_PSTORE_ZSTD_COMPRESS_DEFAULT=y
CONFIG_CRYPTO_ZSTD=y
CONFIG_ZSTD_COMPRESS=y
CONFIG_ZSTD_DECOMPRESS=y
```

**Comment by xanmod** [comment]
There is no implementation for "CONFIG_KERNEL_ZSTD" stable on the mainline. Even so there will be a gain of only ~2% for the boot time with loss vmlinuz compression compared to xz (lzma2).
