### ISSUE TITLE
Kernel Versions All the Same

### ISSUE THREAD

**Issue by Archcan** [xanmod/linux#384]
Xanmod Kernel version 1,2,3 and 4 are all the same =6.3.10. Looking for Kernel 6.4.0. Thanks in advance for considaring a correction.
uname -r
6.3.10-x64v4-xanmod1

https://xanmod.org/

**Comment by xanmod** [comment]
the MAIN branch will migrate to the 6.4 kernel when major third-party modules work correctly with it. If you don't have hardware that needs these modules, install the rolling release linux-xanmod-edge-x64v4 target for 6.4.
