### ISSUE TITLE
Outdated Binder module

### ISSUE THREAD

**Issue by austinrojers** [xanmod/linux#386]
The new  **binder** module seems to be required for updated Waydroid instead of the old **binder_linux** module.

`linux-cachyos` has the new **binder** module and works with Waydroid, whereas `linux-xanmod` has the old **binder_linux** module and gives errors.

```

> waydroid show-full-ui
[gbinder] ERROR: Can't open /dev/binder: No such file or directory
[11:37:15] Waiting for binder Service Manager...
[11:38:15] Service Manager never appeared
[11:38:15] Failed to access IPlatform service
```

**Comment by xanmod** [comment]
In xanmod the android binder is built as a module.
`sudo modprobe binder_linux`

**Comment by austinrojers** [comment]
> In xanmod, the android binder is built as a module. 
`sudo modprobe binder_linux`

Ya, but it causes errors.

I noticed `sudo modprobe binder` returns blank output in the case of  `linux-cachyos` & `linux-zen`. 
Waydroid works fine with `linux-cachyos` & `linux-zen`.
I suppose the new Android binder is built as `binder` and not `binder_linux`.

`linux-xanmod` has the old `binder_linux` module and gives the errors as in my first comment and Waydroid doesn't launch.  

**These are all what I observed**. 
Of course, I do not know how all of this works. Maybe you can figure out what is happening here.

**Comment by austinrojers** [comment]
This is the full context, 
```
> sudo waydroid init 

[11:44:35] Already initialized


> sudo ls -1 /dev/binderfs/
anbox-binder
anbox-hwbinder
anbox-vndbinder
binder-control
features

> sudo ls -1 /dev/binder
ls: cannot access '/dev/binder': No such file or directory

> sudo waydroid status
Session:	RUNNING
Container:	STOPPED
Vendor type:	MAINLINE
Session user:	austin(1000)
Wayland display:	wayland-0

> sudo systemctl enable --now waydroid-container
 
> waydroid session start

[11:36:52] Session is already running

> sudo waydroid container start
ERROR: WayDroid container service is already running

> waydroid show-full-ui
[gbinder] ERROR: Can't open /dev/binder: No such file or directory
[11:37:15] Waiting for binder Service Manager...
[11:38:15] Service Manager never appeared
[11:38:15] Failed to access IPlatform service

> ls /dev/
drwxr-xr-x       - root   16 Apr 17:00  binderfs
lrwxrwxrwx      22 root   16 Apr 17:00  features -> /dev/binderfs/features
lrwxrwxrwx      26 root   16 Apr 17:00  anbox-binder -> /dev/binderfs/anbox-binder
lrwxrwxrwx      28 root   16 Apr 17:00  anbox-hwbinder -> /dev/binderfs/anbox-hwbinder
lrwxrwxrwx      29 root   16 Apr 17:00  anbox-vndbinder -> /dev/binderfs/anbox-vndbinder
lrwxrwxrwx      28 root   16 Apr 17:00  binder-control -> /dev/binderfs/binder-control
```

**Comment by xanmod** [comment]
Android binder driver is mainline, it is same in all kernels of same version. I use ubuntu kernel patches to build binder as module.

Are you trying with kernel 6.3 or 6.4?

**Comment by austinrojers** [comment]
> Are you trying with kernel 6.3 or 6.4?

yes

**Comment by xanmod** [comment]
https://github.com/waydroid/waydroid/issues/30#issuecomment-1145337653

**Comment by austinrojers** [comment]
I had already tried this before. This is what happens:
```
> waydroid show-full-ui
[gbinder] ERROR: Can't open /dev/binder: No such file or directory

>sudo ln -s /dev/anbox-binder  /dev/binder
      
> waydroid show-full-ui
[14:38:22] Starting waydroid session
[gbinder] ERROR: Can't open /dev/binder: Permission denied

```
Even `linux-cachyos` & `linux-zen` had the same issue, but they have fixed it now.

**Comment by xanmod** [comment]
Both don't use additional patches for the Android binder driver.

I use this additional [patch](https://gitlab.com/xanmod/linux-patches/-/blob/master/linux-6.4.y-xanmod/android_anbox/0001-binder-turn-into-module.patch) to not built-in binder in kernel image, but as module, tomorrow I will release a fix.

**Comment by xanmod** [comment]
Working with 6.4.3-xanmod1?

**Comment by austinrojers** [comment]
No, the same errors are still there with `6.4.3-x64v2-xanmod1-2`.

Thank you for your committed support and efforts.

**Comment by austinrojers** [comment]
I even tried this:

```
> waydroid show-full-ui
[14:43:50] Starting waydroid session
[gbinder] ERROR: Can't open /dev/binder: No such file or directory
[14:43:50] Failed to add presence handler: None

> ls  /dev/binderfs/
drwxr-xr-x     - root 12 Jul 14:28  features
crw------- 254,1 root 12 Jul 14:28  anbox-binder
crw------- 254,3 root 12 Jul 14:28  anbox-hwbinder
crw------- 254,2 root 12 Jul 14:28  anbox-vndbinder
crw------- 254,0 root 12 Jul 14:28  binder-control

> cd ..

> sudo ln -s /dev/binderfs/ binder

> cd /dev/binder

> ls
drwxr-xr-x     - root 12 Jul 14:28  features
crw------- 254,1 root 12 Jul 14:28  anbox-binder
crw------- 254,3 root 12 Jul 14:28  anbox-hwbinder
crw------- 254,2 root 12 Jul 14:28  anbox-vndbinder
crw------- 254,0 root 12 Jul 14:28  binder-control

austin  /dev/binder  14:41  waydroid show-full-ui
[14:41:14] Starting waydroid session
[gbinder] ERROR: Can't open /dev/binder: Is a directory
[14:41:14] Failed to add presence handler: None

```

**Comment by austinrojers** [comment]
![image](https://github.com/xanmod/linux/assets/87067093/aa25ce7f-1ff9-4efa-ad5a-7a6edecbaa1a)
This is how it is with `linux-cachyos`. Any hint?

**Comment by austinrojers** [comment]
This is an interesting observation-
This is how it looks with `linux-xanmod`:
```
> ls /dev/
drwxr-xr-x       - root     binderfs
lrwxrwxrwx      22 root     features -> /dev/binderfs/features
lrwxrwxrwx      26 root     anbox-binder -> /dev/binderfs/anbox-binder
lrwxrwxrwx      28 root     anbox-hwbinder -> /dev/binderfs/anbox-hwbinder
lrwxrwxrwx      29 root     anbox-vndbinder -> /dev/binderfs/anbox-vndbinder
lrwxrwxrwx      28 root     binder-control -> /dev/binderfs/binder-control
```
And with `linux-cachyos`:
```
> ls /dev/
drwxr-xr-x       - root     binderfs
lrwxrwxrwx      22 root     features -> /dev/binderfs/features
lrwxrwxrwx      26 root     anbox-binder -> /dev/binderfs/anbox-binder
lrwxrwxrwx      28 root     anbox-hwbinder -> /dev/binderfs/anbox-hwbinder
lrwxrwxrwx      29 root     anbox-vndbinder -> /dev/binderfs/anbox-vndbinder
lrwxrwxrwx      28 root     binder-control -> /dev/binderfs/binder-control
lrwxrwxrwx      20 root     binder -> /dev/binderfs/binder
lrwxrwxrwx      22 root   13 Jul 22:03  hwbinder -> /dev/binderfs/hwbinder
lrwxrwxrwx      23 root   13 Jul 22:03  vndbinder -> /dev/binderfs/vndbinder
```

**Comment by xanmod** [comment]
Solving the problem with waydroid is simple: just compile the kernel with:
```
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
```
Default Xanmod:
```
CONFIG_ANDROID_BINDER_IPC=m
CONFIG_ANDROID_BINDERFS=m
```
Unlike Anbox, Waydroid does not work with binder drivers as a module.
`y` tags make the component built-in to the kernel, a very small fraction of desktop pc users need binder built-in, but in waydroid, either due to some bug or developers' disinterest in implementing the ability to work with binder as a module, that would be ideal , the solution will have to make binder active for all systems, even without its use for 99% of users.

In the next release I will change it to =y.

**Comment by xanmod** [comment]
I did some tests with the waydroid. The problem is not binder related, but to PSI.

Add the `psi=1` boot parameter to your boot loader (GRUB?).

**Comment by xanmod** [comment]
I was able to replicate the same issues and found the following solution:

Before starting the waydroid-container.service you must load the binder_linux module:

To load on boot:
`echo binder_linux | sudo tee /etc/modules-load.d/binder.conf`

Also enable PSI by default:
Add the `psi=1` boot parameter to your boot loader (GRUB?).

The waydroid or gbinder service already loads the binder_linux module, but ideally it would be done correctly (/dev/binder ---> /dev/binderfs/binder), probably a bug that needs to be fixed.

**Comment by austinrojers** [comment]
> Solving the problem with waydroid is simple: just compile the kernel with:
> 
> ```
> CONFIG_ANDROID_BINDER_IPC=y
> CONFIG_ANDROID_BINDERFS=y
> ```
> 
> Default Xanmod:
> 
> ```
> CONFIG_ANDROID_BINDER_IPC=m
> CONFIG_ANDROID_BINDERFS=m
> ```
> 
> Unlike Anbox, Waydroid does not work with binder drivers as a module. `y` tags make the component built-in to the kernel, a very small fraction of desktop pc users need binder built-in, but in waydroid, either due to some bug or developers' disinterest in implementing the ability to work with binder as a module, that would be ideal> 
> In the next release I will change it to =y.

So that was the issue!
Waydroid is now working on my end!

* So after changing the tags to `y`, I suppose you won't need `psi=1` and loading modules on boot?

> The solution will have to make binder active for all systems, even without its use for 99% of users.
This is worth having cause it will make running Android in Linux a bit easier for a newb.

BTW, we now have an almost complete experience of Android in Linux. Most arm-only games/apps run with hardware acceleration without much issues.

I have created a guide at Garuda Linux forum, and I was making a list of Kernels that work with Waydroid.
https://forum.garudalinux.org/t/ultimate-guide-to-install-waydroid-in-any-arch-based-distro-especially-garuda

* I suppose the same would be the case with `binder_linux-dkms`, the missing tag `y`?
Or dkms only installs as modules(not inbuilt)?

Thank you so much for your time and support.

Cheers
Austin 
😀

**Comment by xanmod** [comment]
`CONFIG_XYZ=m` means that a driver/component is built as a kernel module.

binder_linux-dkms would be the same as the kernel's =m, but built by a source external to the kernel source tree.

When manually loaded binder_linux before waydroid-container.service loaded along with psi enabled too, then waydroid will work correctly.

**Comment by austinrojers** [comment]
> `CONFIG_XYZ=m` means that a driver/component is built as a kernel module.
> 
> binder_linux-dkms would be the same as the kernel's =m, but built by a source external to the kernel source tree.
> 
> When manually loaded binder_linux before waydroid-container.service loaded along with psi enabled too, then waydroid will work correctly.

I see 👍
Thanks

**Comment by austinrojers** [comment]
```
> ls /dev/binderfs/
drwxr-xr-x     - root 12 Jul 14:28  features
crw------- 254,1 root 12 Jul 14:28  anbox-binder
crw------- 254,3 root 12 Jul 14:28  anbox-hwbinder
crw------- 254,2 root 12 Jul 14:28  anbox-vndbinder
crw------- 254,0 root 12 Jul 14:28  binder-control
```
What about these `anbox-*`, that get automatically mounted at /dev/binderfs?
Do we need those?

**Comment by xanmod** [comment]
I repeated the test with clean installs of Debian, Ubuntu and Arch + binder_linux-dkms and gbinder worked fine with stock kernel and xanmod. Do the same to check

**Comment by austinrojers** [comment]
> I repeated the test with clean installs of Debian, Ubuntu and Arch + binder_linux-dkms and gbinder worked fine with stock kernel and xanmod. Do the same to check.

Do you mean even without manually loading binder before waydroid-container.service & psi enabled?

**Comment by xanmod** [comment]
> > I repeated the test with clean installs of Debian, Ubuntu and Arch + binder_linux-dkms and gbinder worked fine with stock kernel and xanmod. Do the same to check.
> 
> Do you mean even without manually loading binder before waydroid-container.service & psi enabled?

Yes, only enable psi

**Comment by xanmod** [comment]
I see your article, just one point. In `sudo modprobe -a binder`, when builtin binder (=y), it is not a module, it becomes a kernel component and will always be loaded in memory every boot. Case =m (binder_linux), it will become a .ko module object in `/lib/modules/.../` which will be loaded only when requested.

Another point, if the waydroid-container service is enabled to load every boot, you must add binder_linux in` /etc/modules` or `/etc/modules-load.d/` to load the modules before the waydroid container so that it works.

**Comment by austinrojers** [comment]
I tried Arch stock kernel with binder_linux-dkms, but binder dies even with psi=1.
How did you get it working?

![image](https://github.com/waydroid/waydroid/assets/87067093/a23311e4-21e1-43b8-be9f-608cb9cd4482)
Anything to do with my boot parameters?

**Comment by austinrojers** [comment]
> I see your article, just one point. In `sudo modprobe -a binder`, when builtin binder (=y), it is not a module, it becomes a kernel component and will always be loaded in memory every boot. Case =m (binder_linux), it will become a .ko module object in `/lib/modules/.../` which will be loaded only when requested.
> 
> Another point, if the waydroid-container service is enabled to load every boot, you must add binder_linux in` /etc/modules` or `/etc/modules-load.d/` to load the modules before the waydroid container so that it works.

I have understood, and thank you for your repeated detailed explanations.
In my article, I have added these under `binder_linux-dkms` install section.

So will you be adding `binder` as inbuilt or as a module for Xanmod?
I think you should consider making it inbuilt cause with kernels like **cachyos** & **zen**, you install the kernel, and just Waydroid works fine. Your main concern, I suppose, is binder will remain active for all users, but I think that outweighs the seamless experiences, excluding the need for manually loading the module and enabling psi.

Really appreciate your commitment.

Regards

**Comment by austinrojers** [comment]
Please reply @xanmod. 
I would appreciate whatever your opinion is. It's your project, after all.

Cheers
Austin

**Comment by austinrojers** [comment]
It seems that if you first initialize and run Waydroid with a certain kernel(in my case Cachyos) and then later switch to another kernel, you will have to reinitialize Waydroid to work with the later kernel.

> `sudo waydroid init -f`
> 
>         The `waydroid init -f` command initializes Waydroid.
>         ( The -f flag tells Waydroid to force a reset.)
> 
> This downloads the latest Android image (if there is an update), sets up the Waydroid configuration file and starts the Waydroid container.
> 
>

**Comment by xanmod** [comment]
Still having problems? The aur packages maintainer @figue already changed to `=y`

**Comment by austinrojers** [comment]
> Still having problems? The aur packages maintainer @figue already changed to `=y`

As I mentioned in my previous comment,
it’s working fine with the modules.
You also don’t have to auto load the module on boot.
I just had to reinitialise Waydroid for it to work with the modules.
Making the drivers inbuilt was not necessary.
Anyways no worries. It will work either ways.

> Btw, Xanmod is the only kernel that requires adding psi=1 to the kernel boot parameters.

I had closed the issue at first, then reopened it thinking that you wouldn’t notice my previous post.

Regards
Austin

**Comment by xanmod** [comment]
PSI is a /proc interface to indicate high cpu, i/o and mem pressure, the problem is the cycle consumption for tracking and data collection, under very high workload, in my tests, psi causes a slight degradation. For this reason, there is an option to include it, but disabled by default (CONFIG_PSI_DEFAULT_DISABLED).

I believe the python-gbinder developer should recommend it rather than require it, psi is a newly introduced and non-essential component.

**Comment by austinrojers** [comment]
> PSI is a /proc interface to indicate high cpu, i/o and mem pressure, the problem is the cycle consumption for tracking and data collection, under very high workload, in my tests, psi causes a slight degradation. For this reason, there is an option to include it, but disabled by default (CONFIG_PSI_DEFAULT_DISABLED).
> 
> I believe the python-gbinder developer should recommend it rather than require it, psi is a newly introduced and non-essential component.

👍
I see.
Thank you for your explanation.
All my doubts are clear now!

I will close this issue now.

Cheers
Austin
😀
