### ISSUE TITLE
no BTF found for kernel version 6.4.8-x64v4-xanmod1

### ISSUE THREAD

**Issue by liang-hiwin** [xanmod/linux#388]
apply CO-RE relocations: load kernel spec: no BTF found for kernel version 6.4.8-x64v4-xanmod1: not supported: you should re-compile linux kernel with BTF configurations; see docs for more information"

**Comment by liang-hiwin** [comment]
Duplicated post
https://github.com/xanmod/linux/issues/376

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/489fabdc10a99aa7fa9020e1c018b44685b562f1/CONFIGS/xanmod/gcc/config_x86-64-v3#L11670
