### ISSUE TITLE
feature request: bbr v3

### ISSUE THREAD

**Issue by daire-byrne** [xanmod/linux#389]
Due to be submitted to mainline soon (ish). Replaces the existing bbrv1 completely

https://github.com/google/bbr/blob/v3/README.md

**Comment by KorenKrita** [comment]
just add not remove
bbr still there years after get bbr2 in

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/3698274a6d7faba75e021b877a24d82bac59eb34
