### ISSUE TITLE
XanMod Kernel 5.5.6-xanmod5 fails building zfs-dkms on Ubuntu

### ISSUE THREAD

**Issue by typoworx-de** [xanmod/linux#39]
I'm a great fan of xanmod kernel. But with recent version 5.5.6-xanmod5 I was unable to build zfs-dkms package (Ubuntu 16).

Extract of build process:

$> sudo dkms build zfs/0.8.2
> checking kernel source directory... /lib/modules/5.5.6-xanmod5/build
> checking kernel build directory... /lib/modules/5.5.6-xanmod5/build
> checking kernel source version... 5.5.6-xanmod5
> checking kernel file name for module symbols... Module.symvers
> checking whether access_ok() has 'type' parameter... no
> checking whether modules can be built... no
> configure: error: *** Unable to build an empty module.

**Comment by figue** [comment]
Is this issue related to Xanmod?

**Comment by xanmod** [comment]
Consider an gcc / distro (>=18.04) upgrade.
