### ISSUE TITLE
No bbrv2?

### ISSUE THREAD

**Issue by Potterli20** [xanmod/linux#394]
root@debian:~# sysctl net.ipv4.tcp_available_congestion_control = reno cubic bbr2
net.ipv4.tcp_available_congestion_control = reno bbr
sysctl: cannot stat /proc/sys/reno: No such file or directory
sysctl: cannot stat /proc/sys/cubic: No such file or directory
sysctl: cannot stat /proc/sys/bbr2: No such file or directory

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/3698274a6d7faba75e021b877a24d82bac59eb34
