### ISSUE TITLE
Recent Releases after 6.4.8 are only .zip

### ISSUE THREAD

**Issue by midnightpizza** [xanmod/linux#395]
This there a particular reason for no longer Providing patch files and all those .deb packages?
This makes it very hard for distro's to package or build kernel packages themself as it used to be by just patching the kernel sources without significant changes to how the sources are fetched.. (as i do myself).

**Comment by figue** [comment]
Hi, patches are available in sourceforge, for instance:

https://sourceforge.net/projects/xanmod/files/releases/main/6.4.11-xanmod1/
