### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by russianpropaganda** [xanmod/linux#4]
I'm using 4.14

Build log: https://paste.ee/p/yRAhh

Kernel config: https://paste.ee/p/kf3mR

kernel/sched/pds.c: In function 'sched_fork':
kernel/sched/pds.c:2313:4: error: implicit declaration of function 'hrtick_start' [-Werror=implicit-function-declaration]
    hrtick_start(rq, rq->curr->time_slice);
    ^~~~~~~~~~~~

At top level:
kernel/sched/pds.c:5909:13: warning: 'set_rq_offline' defined but not used [-Wunused-function]
 static void set_rq_offline(struct rq *rq)`

**Comment by xanmod** [comment]
@cchalpha

**Comment by xanmod** [comment]
Upstream the bug fix release PDS 0.98h.
