### ISSUE TITLE
XanMod add bbr2??

### ISSUE THREAD

**Issue by Potterli20** [xanmod/linux#41]
This open source distribution contains documentation, scripts, and
other materials related to the BBR congestion control algorithm.

Quick links:

- TCP BBR v2 Alpha/Preview Release:
  https://github.com/google/bbr/blob/v2alpha/README.md
- BBR FAQ:
  https://github.com/google/bbr/blob/master/Documentation/bbr-faq.md
- TCP BBR Quick-Start: Building and Running TCP BBR on Google Compute Engine:
  https://github.com/google/bbr/blob/master/Documentation/bbr-quick-start.md
- Mailing list: Test results, performance evaluations, feedback, and
  BBR-related discussions are very welcome in the public e-mail list for BBR:
  https://groups.google.com/d/forum/bbr-dev

The latest Google code for the BBR congestion control algorithm is:

  BBR v2 Alpha/Preview release
  ----------------------------

  - For Linux TCP BBR:
      https://github.com/google/bbr/blob/v2alpha/net/ipv4/tcp_bbr2.c

  - For QUIC BBR:
      https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/core/congestion_control/bbr2_sender.cc
      https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/core/congestion_control/bbr2_sender.h

  BBR v1 release
  ----------------------------

  - For Linux TCP BBR:
      https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/tree/net/ipv4/tcp_bbr.c

  - For QUIC BBR:
      https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/core/congestion_control/bbr_sender.cc
      https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/core/congestion_control/bbr_sender.h

This is not an official Google product.

**Comment by xanmod** [comment]
Only when these patches become stable on mainline will they be merged into the repository.

**Comment by Potterli20** [comment]
> Only when these patches become stable on mainline will they be merged into the repository.

Hoping to add ECN for BBR2 and BBR2, I found that Xamnod could not turn ECN on.
