### ISSUE TITLE
CONFIG_VFIO_PCI=m -> CONFIG_VFIO_PCI=y, please

### ISSUE THREAD

**Issue by nazar-pc** [xanmod/linux#42]
This is the change that finally happened in Ubuntu downstream, would be nice for Xanmod to change config accordingly. It helps a lot with PCIe device passthrough, in particular USB controllers.

Here is launchpad ticket for reference: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1770845

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/compare/5.5.10-xanmod1...5.5.10-xanmod2
