### ISSUE TITLE
wifi does not work with 5.6.0 kernels

### ISSUE THREAD

**Issue by hedmo** [xanmod/linux#44]
See :  https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.6-Broken-Intel-IWLWIFI
Here is the patch if you want to patch your 5.6.0-xanmod1

regards hedmo

[wifi.zip](https://github.com/xanmod/linux/files/4415058/wifi.zip)

**Comment by figue** [comment]
I've applied yesterday iwlwifi patch in Archlinux package. Anyway it's included in 5.6.2.

**Comment by xanmod** [comment]
@ http://lkml.iu.edu/hypermail/linux/kernel/2004.0/01296.html
[fixes] https://github.com/xanmod/linux/commits/5.6.2-xanmod1

**Comment by figue** [comment]
Thanks for this quick update Alexandre!
