### ISSUE TITLE
Much slower loading Proton games

### ISSUE THREAD

**Issue by deathxxx123** [xanmod/linux#48]
Hi,
i play mostly Dark Souls III via lastest Proton, and i see that with XanMod edge kernel, my game is loading slower, compare to original kernels. I do not see any other issues.
I do not try stable or any other kernels. Only edge.

Proton 5.0-6
OS: Ubuntu Budgie 20.04 LTS (64 bit)
KERNEL: 5.6.4-xanmod1
CPU: Intel Core i7-6700K @ 4.00GHz
GPU: NVIDIA GeForce GTX 1060 6GB
GPU DRIVER: NVIDIA 440.64
RAM: 32 GB DDR3L

**Comment by xanmod** [comment]
Thanks for reporting deathxxx123, the most recent patch has been reimplemented.
https://github.com/xanmod/linux/compare/f64c92c678257476265dd15a09cde3662ba3fa86...16db357b022d266f042e29d9e1014f79e8f01b8f

**Comment by deathxxx123** [comment]
> Thanks for reporting deathxxx123, the most recent patch has been reimplemented.
> [f64c92c...16db357](https://github.com/xanmod/linux/compare/f64c92c678257476265dd15a09cde3662ba3fa86...16db357b022d266f042e29d9e1014f79e8f01b8f)

I do not understand much, but thanks, i think now are ok, with lastest edge kernel. The game seems loading faster. I wish to have some tool to meansure that.
Thank you for this absolutely insane work!
