### ISSUE TITLE
Please, publish patches also.

### ISSUE THREAD

**Issue by perfect7gentleman** [xanmod/linux#5]
for example, publish patch 4.14.9-xanmod13.patch for 4.14.9

**Comment by xanmod** [comment]
Ok, on the next release.

**Comment by perfect7gentleman** [comment]
good to hear it.

**Comment by xanmod** [comment]
patches available: https://github.com/xanmod/linux/releases

**Comment by perfect7gentleman** [comment]
@xanmod, I've downloaded patch for 4.14.10, tried to apply it, but there were too many warnings and errors.
Then I did the following
```
git clone --single-branch --branch 4.14 https://github.com/xanmod/linux.git xanmod
cd xanmod/
git diff b8ce8232fcc37fe7a97db79ea0a5f32098c25e72 788ca14449fe884ae74c81f094e84c61f09cd36b > 4.14.10-xanmod.patch
```
and that patch was applied without any warning.
What's wrong?
