### ISSUE TITLE
NVIDIA XanMod-RT-Edge

### ISSUE THREAD

**Issue by rauldipeas** [xanmod/linux#52]
Quando tento instalar o driver 440 do ppa:graphics/drivers, ele me informa que não é suportado...

`ERROR (dkms apport): kernel package linux-headers-5.6.4-rt3-xanmod1 is not supported`

Alguma chance de funcionar em releases futuros? No release anterior estava funcionando.

**Comment by xanmod** [comment]
Com NVIDIA 440.82?

**Comment by rauldipeas** [comment]
`DKMS make.log for nvidia-440.64 for kernel 5.6.4-rt3-xanmod1 (x86_64)
ter 28 abr 2020 17:25:20 -03
make[1]: Entering directory '/usr/src/linux-headers-5.6.4-rt3-xanmod1'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
make -f ./scripts/Makefile.build obj=/var/lib/dkms/nvidia/440.64/build \
single-build= \
need-builtin=1 need-modorder=1
The kernel you are installing for is a PREEMPT_RT kernel!

The NVIDIA driver does not support real-time kernels. If you 
are using a stock distribution kernel, please install 
a variant of this kernel that does not have the PREEMPT_RT 
patch set applied; if this is a custom kernel, please 
install a standard Linux kernel.  Then try installing the 
NVIDIA kernel module again.

*** Failed PREEMPT_RT sanity check. Bailing out! ***

make[2]: *** [/var/lib/dkms/nvidia/440.64/build/Kbuild:194: preempt_rt_sanity_check] Error 1
make[2]: ** Esperando que outros processos terminem.
make[1]: *** [Makefile:1685: /var/lib/dkms/nvidia/440.64/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.4-rt3-xanmod1'
make: *** [Makefile:81: modules] Error 2`

**Comment by rauldipeas** [comment]
Na verdade, acabei de conferir, o apt tá baixando o driver do repositório do Ubuntu mesmo, ao invés de baixar do PPA, tô investigando pra saber o motivo.

Tô num Xubuntu recém instalado.

**Comment by xanmod** [comment]
Deu certo?

**Comment by rauldipeas** [comment]
> Deu certo?

Mesmo com o PPA adicionado, o driver no repositório da Canonical é o mais novo, usando o `rt-edge` não instala o driver de vídeo de forma nenhuma.

No `edge` funciona, mas daí eu tenho alguns artefatos no som que não acontecem no `rt-edge`.

**Comment by xanmod** [comment]
https://launchpad.net/ubuntu/+source/nvidia-graphics-drivers-440.
No 20.04 é um pacote de downgrade "440.82+really.440.64-0ubuntu6". Precisa ser >=440.82 com os edges. Se preferir o v5.4-rt, utilize o meta linux-xanmod-rt.

**Comment by rauldipeas** [comment]
Saquei, vou configurar manualmente a prioridade do apt pra baixar do PPA ao invés do repositório da Canonical, valeu.

**Comment by rauldipeas** [comment]
Instalei os pacotes do PPA, 440.82, mesmo problema.
```
DKMS make.log for nvidia-440.82 for kernel 5.6.4-rt3-xanmod1 (x86_64)
qui 30 abr 2020 04:45:12 -03
make[1]: Entering directory '/usr/src/linux-headers-5.6.4-rt3-xanmod1'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
make -f ./scripts/Makefile.build obj=/var/lib/dkms/nvidia/440.82/build \
single-build= \
need-builtin=1 need-modorder=1
The kernel you are installing for is a PREEMPT_RT kernel!

The NVIDIA driver does not support real-time kernels. If you 
are using a stock distribution kernel, please install 
a variant of this kernel that does not have the PREEMPT_RT 
patch set applied; if this is a custom kernel, please 
install a standard Linux kernel.  Then try installing the 
NVIDIA kernel module again.

*** Failed PREEMPT_RT sanity check. Bailing out! ***

make[2]: *** [/var/lib/dkms/nvidia/440.82/build/Kbuild:194: preempt_rt_sanity_check] Error 1
make[2]: ** Esperando que outros processos terminem.
make[1]: *** [Makefile:1685: /var/lib/dkms/nvidia/440.82/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.4-rt3-xanmod1'
make: *** [Makefile:81: modules] Error 2
```

**Comment by xanmod** [comment]
No próprio log há aviso dos módulos não suportarem kernels rt... Veja se com v5.4.x `linux-xanmod-rt` da certo.

**Comment by rauldipeas** [comment]
Tentei com o 5.4.x, mesmo resultado...

Vou seguir pesquisando uma solução, enquanto isso vou ter que alternar entre o `rt-edge` e o `edge` quando for gravar e quando for jogar.

**Comment by xanmod** [comment]
Consegui uma solução:
Na sessão root: `export IGNORE_PREEMPT_RT_PRESENCE=1 && dkms install -m nvidia/440.82`

**Comment by rauldipeas** [comment]
Funcionou! Valeu cara, se tiver algum jeito de incluir isso nas próximas versões, seria ótimo!

**Comment by xanmod** [comment]
Passe um feedback depois, se estiver tudo ok, vou entrar em contato com os mantenedores dos pacotes para incluírem essa variável no make modules.

**Comment by rauldipeas** [comment]
Fiz alguns testes com jogos leves e renderizei um vídeo usando a GPU no OpenShot, tudo perfeito até aqui.

Só tem um lance aí que eu tive que adaptar, ao invés de rodar o `dkms` direto, eu rodei ele pelo `apt` mesmo, porque do contrário, toda vez que eu tentava fazer qualquer coisa pelo `apt` ele tentava recompilar sem a variável e dava erro.

A variável só funciona como root mesmo.

**Comment by rauldipeas** [comment]
Descobri outra forma de incluir essa variável de ambiente na execução do `dkms`, funciona com qualquer versão do driver, testei na 440.82 e na 440.64.
```
sudo sed -i 's/NV_EXCLUDE_BUILD_MODULES/IGNORE_PREEMPT_RT_PRESENCE=1 NV_EXCLUDE_BUILD_MODULES/g' /usr/src/nvidia*/dkms.conf
```
