### ISSUE TITLE
CONFIG_INPUT_EVBUG ?

### ISSUE THREAD

**Issue by figue** [xanmod/linux#53]
Module CONFIG_INPUT_EVBUG is compiled by default, but in other linux distros like Archlinux it is not. It flood logs and other stuff. You can simply blacklisting it, though.

Perhaps it can be safely disabled in the stable release.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/blob/888315f9245fc72411e366d95aeace49aa796fd7/.config#L3885

**Comment by figue** [comment]
Thanks!
