### ISSUE TITLE
[REPORT]Streets of Rage 4 now loading much faster, thanks to XanMod kernel

### ISSUE THREAD

**Issue by deathxxx123** [xanmod/linux#54]
Thanks for this great support to this kernel. I was using 5.6.6-xanmod1 and game load faster than normal kernels in Ubuntu 20.04, but now i try 5.6.10-xanmod1(the lastest one) and the game loading even faster! The game stil have loading times problem, but it's from early Proton and first support to this game. But this kernel is so fast, that almost fix this issue!
There is a video i created:
https://youtu.be/NSFXKUwZ0XQ

**Comment by deathxxx123** [comment]
This is without XanMod kernel:
https://youtu.be/kPC1Q1C5eXI
It's loading slower, compare to XanMod.

**Comment by xanmod** [comment]
I played a lot in my youth. I love this game. Thanks @deathxxx123.

**Comment by deathxxx123** [comment]
I play Sorr Remake v5, which have port for linux and it's so much dynamic, compare to Sorr 4 now.
I hope devs will do more to this new game. At least to add survival mode.
