### ISSUE TITLE
Linux kernel will WireGuard be integrated?

### ISSUE THREAD

**Issue by Potterli20** [xanmod/linux#56]
Will WireGuard be integrated?

**Comment by kennysgithub** [comment]
It was fully integrated as of 5.6, so I'd assume it's already there?

**Comment by Potterli20** [comment]
> 自5.6起已完全集成，所以我认为它已经存在了吗？

NONO

**Comment by kennysgithub** [comment]
> > 自5.6起已完全集成，所以我认为它已经存在了吗？
> 
> NONO

? : https://github.com/xanmod/linux/commit/e7096c131e5161fa3b8e52a650d7719d2857adfd

**Comment by Potterli20** [comment]
> > > 自5.6起已完全集成，所以我认为它已经存在了吗？
> > 
> > 
> > NONO
> 
> ? : [e7096c1](https://github.com/xanmod/linux/commit/e7096c131e5161fa3b8e52a650d7719d2857adfd)

But it's not running, I'm using the official command, I'm using Debian.

**Comment by Potterli20** [comment]
Is it not installed, is it not installed?

**Comment by xanmod** [comment]
~$ modinfo wireguard 
filename:       /lib/modules/5.7.1-xanmod1/kernel/drivers/net/wireguard/wireguard.ko
alias:          net-pf-16-proto-16-family-wireguard
alias:          rtnl-link-wireguard
version:        1.0.0
author:         Jason A. Donenfeld <Jason@zx2c4.com>
description:    WireGuard secure network tunnel
license:        GPL v2
srcversion:     E3F1AD2696809B6F4C436AF
depends:        libblake2s,udp_tunnel,curve25519-x86_64,libchacha20poly1305,ip6_udp_tunnel,libcurve25519-generic
retpoline:      Y
intree:         Y
name:           wireguard
vermagic:       5.7.1-xanmod1 SMP preempt mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4

**Comment by xanmod** [comment]
To load module:
`modprobe wireguard`

**Comment by Potterli20** [comment]
> 加载模块：
> `modprobe wireguard`

OK

**Comment by Potterli20** [comment]
root@iZt4ne694cocz8xo8llsapZ:~# uname -a
Linux iZt4ne694cocz8xo8llsapZ 5.7.1-xanmod1 #0 SMP PREEMPT Mon Jun 1 18:30:27 -03 2020 x86_64 GNU/Linux
root@iZt4ne694cocz8xo8llsapZ:~#  modinfo wireguard
filename:       /lib/modules/5.7.1-xanmod1/kernel/drivers/net/wireguard/wireguard.ko
alias:          net-pf-16-proto-16-family-wireguard
alias:          rtnl-link-wireguard
version:        1.0.0
author:         Jason A. Donenfeld <Jason@zx2c4.com>
description:    WireGuard secure network tunnel
license:        GPL v2
srcversion:     
depends:        libblake2s,udp_tunnel,curve25519-x86_64,libchacha20poly1305,ip6_udp_tunnel,libcurve25519-generic
retpoline:      Y
intree:         Y
name:           wireguard
vermagic:       5.7.1-xanmod1 SMP preempt mod_unload
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:       
sig_hashalgo:   sha512
signature:       md4
root@iZt4ne694cocz8xo8llsapZ:~# wg
-bash: wg: command not found
root@iZt4ne694cocz8xo8llsapZ:~#

**Comment by xanmod** [comment]
Do you need to install wireguard-tools first.

**Comment by Potterli20** [comment]
> Do you need to install wireguard-tools first.

Ok
