### ISSUE TITLE
5.6.18 failed to boot, result in kernel panic

### ISSUE THREAD

**Issue by Wello6143** [xanmod/linux#57]
Hi xanmod, 
The latest 5.6.18 build on your deb repo caused the unable to generate initramfs (or something else, I don't know), result in kernel panic that unable to mount root filesystem. I went back to 5.6.14, tried to remove that kernel but dpkg has been messed up, caused all old working kernels has gone too.
I also have 5.4 kernel updated on my server, it is now turned off and I'm not sure if it's failed to boot in.
I'm not a low-level linux user, help me if you can. Or not I'll switch back to Fedora since I also have works to do over there.
Thanks.

**Comment by xanmod** [comment]
Try to reinstall the kernel and send a compressed kern.log / syslog in _/var/log_

**Comment by xanmod** [comment]
Also run a memtest and check your hardware.

**Comment by Wello6143** [comment]
Hi
Due to I need my system get back to work as soon as possible, thus so far, I've tried to completely purge your kernel, and maybe your kernel also made `initramfs-tools` can't properly generate new initramfs for other kernels. So yeah, I installed Fedora, because I have works to do over there. All data is gone.
Thanks for your attention, take care
Please note: I'm not saying your kernel (or its tools) broke up my system, but I don't have much time to investigate.

**Comment by Wello6143** [comment]
I'll reopen this issue if I have other ubuntu system to help you with.
