### ISSUE TITLE
5.6.17-rt9 broke NVIDIA Optimus usage

### ISSUE THREAD

**Issue by not-a-dev-stein** [xanmod/linux#59]
I have been using xanmod for a couple of weeks and  a couple of days ago I decided to go for the real time edge for a change, and everything was working fine. Yesterday I updated to the aforementioned version, and now I when I turn my laptop on I get absolutely no signal on my external monitor, since it's not using the dedicated GPU, even when I select to only use the NVIDIA GPU and restart, it still only uses the integrated one.

System:
Pop_OS 20.04 LTS
i7-7700HQ (w/HD630 integrated graphics)
GTX1050Ti
 2x8GB RAM

**Comment by xanmod** [comment]
Support from NVIDIA is limited with kernels-rt, I think you better choose the stable branch at the moment. Anyway, send here a compressed (xz) your kern.log from _/var/log_ path.

**Comment by not-a-dev-stein** [comment]
Oh crap, I forgot to get the logs before using timeshift, I'm already back at stable now, sorry I can't help much, but thanks for the clarification.
