### ISSUE TITLE
release prebuilt cpu optimized kernels?

### ISSUE THREAD

**Issue by jumoog** [xanmod/linux#61]
thanks for your kernel!
Would it be possible to build and ship cpu optimized kernels as well?

Maybe you can use Azure Pipelines (free) to build cpu optimized kernels

**Comment by xanmod** [comment]
Source code available to compile for any hardware. It is not feasible to compile a kernel optimized for each type of different hardware, for several reasons such as lack of hardware to test, support and huge variety of platforms within the same architecture.
I don't discount any suggestions. Builds optimized for AMD Zen and Intel processors w/ >= AVX2 can be considered.
