### ISSUE TITLE
[question] what is ebpf.plugin?

### ISSUE THREAD

**Issue by ionutnechita** [xanmod/linux#62]
I noticed this error in dmesg:
[48934.005237] EBPF PROCESS[1536]: segfault at 6410 ip 0000000000006410 sp 00007efe01b0fb78 error 14 in ebpf.plugin (deleted)[55aa7ed97000+3000]
[48934.005250] Code: Bad RIP value.

Linux venusos 5.6.19-xanmod1 #0 SMP PREEMPT Wed Jun 17 13:05:49 -03 2020 x86_64 GNU/Linux

From what can it be? can you give an opinion?

Thanks

**Comment by xanmod** [comment]
Do you use netdata? Check if the bpftrace package is installed.

**Comment by ionutnechita** [comment]
Hi, 
Yes, i use netdata.
I reinstalled the package again.
I hope it doesn't show up again.

Thanks.

**Comment by ionutnechita** [comment]
Hi, Alexandre Frade

It is good to close this ticket.

Issue has been solved.

Thanks.
