### ISSUE TITLE
Cannot update chache for 5.7.6-xanmod1

### ISSUE THREAD

**Issue by deathxxx123** [xanmod/linux#63]
Failed to fetch http://deb.xanmod.org/dists/releases/main/binary-i386/Packages.gz  File has unexpected size (13561 != 13563). Mirror sync in progress? [IP: 172.67.147.54 80]
   Hashes of expected file:
    - Filesize:13563 [weak]
    - SHA256:318384671532146c14dc8b396af16b631db6f396279cba629f55f402a1d571b1
    - SHA1:4b5881d4d02e1269677e11cb7775aac853bb440d [weak]
    - MD5Sum:4c6cf632b7fe7c52f62ed424b32145db [weak]
   Release file created at: Fri, 26 Jun 2020 03:17:12 +0000

and when apt update:

http://deb.xanmod.org releases/main amd64 linux-firmware all 1.188                                                                                                                     
  404  Not Found [IP: 104.18.56.133 80]

Last time was no problem, but now i cannot update.

**Comment by deathxxx123** [comment]
I fix it with:
**sudo apt install linux-xanmod**
Then:
**sudo apt update** is working again with no error!

**Comment by xanmod** [comment]
Sometimes cloudflare caches synchronize part of the repository's apt package list. It should have normalized by now.
[CF cache: 2H TTL]
