### ISSUE TITLE
Tor exit apt requests blocked

### ISSUE THREAD

**Issue by 19h** [xanmod/linux#68]
Hello,

I'm using xanmod for all of my exit nodes but cannot update because the apt server for whatever reason blocks Tor IPs. Is there a suitable mirror, or a way I can maintain a mirror myself?

Regards

**Comment by xanmod** [comment]
Firewall rules updated.

**Comment by 19h** [comment]
Thanks, Alexandre.

I'm not entirely sure what kind of rules you updated, but at least one of my exits is still receiving the following error trying to update:

```
E: Failed to fetch http://deb.xanmod.org/dists/releases/InRelease  403  Forbidden [IP: 104.18.57.133 80]
```

For my case specifically, the IPs in question are 185.107.47.215, 185.107.47.171 and 185.107.70.202.
