### ISSUE TITLE
Borked up suspend on intel cpu with 5.7.10-xanmod2

### ISSUE THREAD

**Issue by UnicodeMan** [xanmod/linux#69]
I have a HP dc0019ur laptop (Intel i5 8th gen cpu), with which sleep is failing (fan is left on, keyboard is lit, laptop is completely unresponsive to keyboard led change or touchpad disabling using fn keys), also sysrq+(REISUB) does not help nor do anything. 
This happened when I tried puting my laptop to sleep after switching to kernel 5.7.10-xanmod2 (earlier it was running 5.7.10-xanmod1, suspend was working fine).

It has happened before with liquorix kernel (update, reboot, try to suspend - fails, then after a while an update fixes the problem), unfortunately, it happened several times. Not a complaint to Liquorix project, but as possibly relevant information.

**Comment by xanmod** [comment]
Fixed in new upstrem rev git20200727.f2c8ac1.
