### ISSUE TITLE
kernel: Error: Driver 'pcspkr' is already registered, aborting...

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#71]
I am giving the xanmod kernel a try on my Manjaro system. Everything works fine but the kernel introduces a new error message in the log:

`kernel: Error: Driver 'pcspkr' is already registered, aborting...`

I know that this message is harmless but nevertheless I like to have a clean log without errors. I could blacklist the pcspkr module to get rid of the message. But that would also affect the Manjaro kernels which I do not want.

I would rather like to understand why the xanmod kernels introduce this message. May be there is another solution other than blacklisting the module.

**Comment by xanmod** [comment]
@figue CONFIG_INPUT_PCSPKR=m?

**Comment by figue** [comment]
Yes, it's enabled as module in stock Arch kernel:

https://git.archlinux.org/svntogit/packages.git/tree/trunk/config?h=packages/linux#n4136

**Comment by figue** [comment]
@mabod you can create myconfig file in your package folder with this content:

```scripts/config --module CONFIG_INPUT_PCSPKR```

Then rebuild the package to apply that config.

**Comment by mabod** [comment]
This did not help. 

I created the myconfig file and I see that the option is set when the new kernel is running:
```
5# zcat /proc/config.gz | grep CONFIG_INPUT_PCSPKR
CONFIG_INPUT_PCSPKR=m
```

But the error message is still there:

`Aug 10 07:52:26 rakete kernel: Error: Driver 'pcspkr' is already registered, aborting...`

**Comment by mabod** [comment]
This is still happening with 5.8.8-xanmod1. I am lost. Why do I not see this message with stock Manjaro kernels?

**Comment by xanmod** [comment]
Probably the differences in the xanmod stock config are different from the manjaro config. Compile the kernel with the manjaro kernel config.

**Comment by mabod** [comment]
This is the solution:

`scripts/config --disable CONFIG_SND_PCSP`
