### ISSUE TITLE
UKSM patches [feature request]

### ISSUE THREAD

**Issue by nightloli** [xanmod/linux#75]
Hello, what do you think about adding uksm patches to xanmod? https://github.com/dolohow/uksm
They seem to apply without any problems since I just placed them in my `/etc/portage/patches/sys-kernel/xanmod-sources` directory and didn't have any problems with applying them
And they usually save about ~5-10% ram for me under normal workflow like browsing

Also Calculate Linux uses them as far as I know
https://forum.calculate-linux.org/t/uksm/9364 the site is in russian but google translate seems to translate it fine

![09-08-2020_17:01:14_screenshot](https://user-images.githubusercontent.com/7118699/89734012-03957c80-da62-11ea-9653-6546c292f059.png)
![09-08-2020_17:11:26_screenshot](https://user-images.githubusercontent.com/7118699/89734206-650a1b00-da63-11ea-9fa3-6cf2816a0065.png)

**Comment by veronikazaglotova** [comment]
I don't use xanmod but I double this

**Comment by xanmod** [comment]
https://github.com/dolohow/uksm/issues/33
http://dnaeon.github.io/enable-ksm-during-boot-time-on-linux/

If you can test with the current kernel versions, I would appreciate it.
Note that the UKSM consumes more resources than KSM.

**Comment by joder666** [comment]
I am a bit confuse, what's the difference between this and [ukms](https://gitlab.com/post-factum/uksmd) from the pf kernel?

**Comment by soredake** [comment]
https://www.usenix.org/system/files/conference/fast18/fast18-xia.pdf
