### ISSUE TITLE
Default qdisc to FQ-PIE instead of CAKE maybe?

### ISSUE THREAD

**Issue by enihcam** [xanmod/linux#77]
I'm not saying CAKE is bad. Actually I'm using it because it has my most wanted feature - TSO/GSO/GRO peeling. However,
It needs to be manually tuned before taking effective. This is not common for ordinary users because they need to understand the basics of layer-2 frame structures and how traffic shaping works, why it only applies to upstreaming traffic by default, and then get familiar with tc command and apply the parameters via udev etc... so I'm just guessing, most of the xanmod-linux users are using the CAKE default setting. And, if I'm right, maybe it's better to set default qdisc to FQ-PIE, which also has good performance but less manual works. CAKE fans can still configure their kernel if they are not happy with FQ-PIE because they've already got their hands dirty, right?

**Comment by xanmod** [comment]
What would be the best settings for CAKE?

**Comment by enihcam** [comment]
> What would be the best settings for CAKE?

depend on your downstream/upstream bandwidth, L2 framing (adsl, fiber, cable or what), ISP latency, NAT or not, respect QoS tag or not, TSO/GSO/GRO enabled or not, etc.

**Comment by xanmod** [comment]
fq_pie in use now in the dev env, is a new candidate along with fq_codel_fast.

**Comment by xanmod** [comment]
FQ-PIE works well with the sharing bottleneck capability without any configuration, as you mentioned. I don't focus on networking and therefore any help is welcome. Thanks @enihcam 

https://github.com/xanmod/linux/blob/2c69096ad4158be6e9660902849349a159b57fd8/.config#L1747
