### ISSUE TITLE
Can't Verify if the Deb Repo is Signed (Possibly hCaptcha's Blocking Connection)

### ISSUE THREAD

**Issue by admkhalid** [xanmod/linux#78]
`sudu apt update` output:

```
E: Failed to fetch https://deb.xanmod.org/dists/releases/InRelease  403  Forbidden [IP: 104.18.56.133 443]
E: The repository 'https://deb.xanmod.org releases InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
When I tried visiting your repo index through browser, hCaptcha appeared. This happened on your main website as well. (And I've been getting hCaptcha quite often on several websites just today). So, can you confirm this is definitely hCaptcha.

I also tried re-adding your repo and your key:
`$ echo 'deb http://deb.xanmod.org releases main' | sudo tee /etc/apt/sources.list.d/xanmod-kernel.list && wget -vO - http://dl.xanmod.org/gpg.key | sudo apt-key add -`
Output:
```
deb http://deb.xanmod.org releases main
--2020-08-12 17:01:39--  http://dl.xanmod.org/gpg.key
Resolving dl.xanmod.org (dl.xanmod.org)... 172.67.147.54, 104.18.56.133, 104.18.57.133, ...
Connecting to dl.xanmod.org (dl.xanmod.org)|172.67.147.54|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://dl.xanmod.org/gpg.key [following]
--2020-08-12 17:01:39--  https://dl.xanmod.org/gpg.key
Connecting to dl.xanmod.org (dl.xanmod.org)|172.67.147.54|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-08-12 17:01:40 ERROR 403: Forbidden.

gpg: no valid OpenPGP data found.
```
Everything (including your gpg key) is accessible once I pass hCaptcha on the browser, but can't access them through the terminal.

**Comment by xanmod** [comment]
Does this issue still persist?

**Comment by admkhalid** [comment]
Yup. Still 403 forbidden.

**Comment by xanmod** [comment]
I update the firewall rules. Try again.

**Comment by admkhalid** [comment]
Alright, it works now. Upgrading the kernel as I write this.
