### ISSUE TITLE
xanmod repository not found on Debian???

### ISSUE THREAD

**Issue by Jakecheslekov** [xanmod/linux#8]
sudo apt install linux-xanmod-4.15
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-xanmod-4.15
E: Couldn't find any package by glob 'linux-xanmod-4.15'
E: Couldn't find any package by regex 'linux-xanmod-4.15'

What's going on here? I have the repo added but theres no packages in sight except for "xanmod-repository" which I've installed.

**Comment by xanmod** [comment]
Did you run the apt update before, right?
If the apt package fails, run this command:

`echo 'deb http://deb.xanmod.org releases main' | sudo tee /etc/apt/sources.list.d/xanmod-kernel.list && wget -qO - http://deb.xanmod.org/gpg.key | sudo apt-key add -`

Alexandre
