### ISSUE TITLE
Xanmod ruined display and nvidia drivers on Pop os.

### ISSUE THREAD

**Issue by smasher-101** [xanmod/linux#82]
I tried to install xanmod kernel through Synaptic package manager, rebooted, and found a lovely 4/3 awful resolution on my 1440p ultrawide monitor. I tried to change the resolution and "display not recognized" in the os settings. So I tried to launch nvidia settings with sudo nvidia-settings and it said something to do with it not existing but I don't remember exactly.

So I ended up grabbing my usb stick again and just reinstalling popos and that fixed the issue, however I still want to use xanmod. What could I do differently to make it work?

**Comment by Snowy001** [comment]
having this same issue. after installing xanmod, my second monitor stopped registering. main one is still working though

**Comment by xanmod** [comment]
The nvidia driver from the official pop repository is out of date, with Linux 5.8 you need the latest NVIDIA 450. Update the driver through this ppa repository: https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by smasher-101** [comment]
@xanmod I ended up using the LTS version and it works but I do want the newer drivers, I added the PPA but I am not sure how to get the 450.66 driver (I would prefer to use synaptic package manager).

**Comment by smasher-101** [comment]
![image](https://user-images.githubusercontent.com/64756991/92415379-2772dd80-f148-11ea-990c-06b71cd8b773.png)
I would expect this selected one is the one to use but I REALLY don't want to fuck anything else up I am tired of fixing things.

**Comment by xanmod** [comment]
nvidia-driver-450

**Comment by smasher-101** [comment]
K I've got the driver, thanks, I would like to ask how much of a difference for gaming and general use there is between the LTS version and the real time and stable versions and what those even mean.

**Comment by smasher-101** [comment]
@xanmod I have the nvidia 450 driver and I got the RT stable version and used rEFind to boot into it with standard options, and the resolution was the same as I originally mentioned. I do not know what is wrong but the lts version works fine and none of the others I have tried do.

**Comment by xanmod** [comment]
Please, see xanmod.org frontpage in "note:"

Note: The current proprietary NVIDIA, VirtualBox, VMware Workstation / Player or some other dkms modules builds are not fully compatible with Linux 5.8 (EDGE) and **RT**.

**Comment by kurokirasama** [comment]
I'm on the 510 version of the drivers and same issue...
