### ISSUE TITLE
My System keeps freezing and my applications can't open

### ISSUE THREAD

**Issue by Arhilis** [xanmod/linux#83]
I have an old laptop with an Intel Pentium 3556u
With pop os 20.04 installed. After I installed xanmod kernel, My system constantly freezes everytime  I try to open an application or terminal, and eventhough there was no freezes it won't open the applications, and it also goes the same for trying to open GUI's I tried removing xanmod but I don't know how and I tried to use my backed up kernel it still didn't work, same issue same thing. I am having suspicion that v5.6 and above xanmod kernel doesn't work with Ubuntu based OS. The last time xanmod kernel worked with pop os was v5.5 or 5.4.

**Comment by xanmod** [comment]
and with that version?
https://sourceforge.net/projects/xanmod/files/releases/stable/5.8.8-xanmod1/

Download and install linux-image and linux-headers packages

**Comment by Arhilis** [comment]
> and with that version?
> https://sourceforge.net/projects/xanmod/files/releases/stable/5.8.8-xanmod1/
> 
> Download and install linux-image and linux-headers packages

How to I replace the stock linux-image and Linux -headers with xanmod's?

**Comment by xanmod** [comment]
Did current versions solve your problem?
