### ISSUE TITLE
config difference 5.8.9 vs. 5.8.10 regarding CACHY

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#84]
I am wondering why CACHY scheduler is no longer turned on by default in xanmod 5.8.10. 

`.config `in 5.8.10 says:

`# CONFIG_CACHY_SCHED is not set`

While in 5.8.9 it says:

`CONFIG_CACHY_SCHED=y`

Nevertheless the CACHY patch seems to be included in 5.8.10, but it is not active.
Have you changed your mind? Why?
How can CACHY scheduler be activated with 5.8.10?

**Comment by xanmod** [comment]
Cachy is experiencing problems with smp / mc performance. We're fixing that.

**Comment by figue** [comment]
Cachy is ok in latest releases.
