### ISSUE TITLE
Disabling HIGH_RES_TIMERS results in compile error

### ISSUE THREAD

**Issue by pobrn** [xanmod/linux#85]
`schedule_msec_hrtimeout()`, `schedule_min_hrtimeout()`, `schedule_msec_hrtimeout_interruptible()`, and `schedule_msec_hrtimeout_uninterruptible()` are defined twice when compiling without `CONFIG_HIGH_RES_TIMERS=y` in `include/linux/sched.h` and `kernel/time/hrtimer.c` because the definitions in `kernel/time/hrtimer.c` are not guarded by an `ifdef`.

**Comment by xanmod** [comment]
Explain why do you need to disable CONFIG_HIGH_RES_TIMERS? So, I see what is the best decision whether to create a treatment or make the hrtimer default in the kernel.

**Comment by pobrn** [comment]
Actually, I don't use the xanmod kernel. I came across this issue on a forum, a merely wanted to bring the creator's attention to it.

**Comment by p0txky** [comment]
same issue here .. don't need high resolution timer support if you enable periodic timer tics.

**Comment by xanmod** [comment]
For Linux 5.13: [0001-hrtimer-revert-highres-variants.patch.gz](https://github.com/xanmod/linux/files/6893814/0001-hrtimer-revert-highres-variants.patch.gz)
