### ISSUE TITLE
A start job is running for /dev/disk/by-uuid/...

### ISSUE THREAD

**Issue by xuanruiqi** [xanmod/linux#87]
Arch Linux user, root on Btrfs. When I try to boot with the xanmod kernel, I get stuck on

`A start job is running for /dev/disk/by-uuid/...`

I'm very, very sure I have the Btrfs drivers compiled into the kernel, and I can boot without issues with other kernels so it shouldn't be an `fstab` issue either.

**Comment by xuanruiqi** [comment]
I also have all the compression drivers compiled into the kernel, so it's probably not the compression either.

**Comment by xuanruiqi** [comment]
PS the partition that fails to mount is my root partition

**Comment by figue** [comment]
BTRFS configurations enabled in Arch stock kernel are:

```
figue@pluto ~ % zgrep -i btrfs /proc/config.gz
CONFIG_BTRFS_FS=m
CONFIG_BTRFS_FS_POSIX_ACL=y
# CONFIG_BTRFS_FS_CHECK_INTEGRITY is not set
# CONFIG_BTRFS_FS_RUN_SANITY_TESTS is not set
# CONFIG_BTRFS_DEBUG is not set
# CONFIG_BTRFS_ASSERT is not set
# CONFIG_BTRFS_FS_REF_VERIFY is not set
```

Can you compare with yours?

**Comment by xuanruiqi** [comment]
Hmm, exactly the same as mine!

**Comment by figue** [comment]
What bootloader are you running? Could be a misconfiguration between Arch stock and Xanmod entry?

**Comment by xuanruiqi** [comment]
I'm using rEFInd, with the same command-line options applied:

`root=UUID=... rootflags=subvol=@ rw initrd=@\boot\amd-ucode.img initrd=@\boot\initramfs-%v.img`

**Comment by hamadmarri** [comment]
I am on opensuse, I just copied the btrfs part in .config from opensuse, it might help to double check:

```
cat /boot/config-5.8.10-1-default | grep -i btrfs

CONFIG_BTRFS_FS=m
CONFIG_BTRFS_FS_POSIX_ACL=y
# CONFIG_BTRFS_FS_CHECK_INTEGRITY is not set
# CONFIG_BTRFS_FS_RUN_SANITY_TESTS is not set
# CONFIG_BTRFS_DEBUG is not set
CONFIG_BTRFS_ASSERT=y
# CONFIG_BTRFS_FS_REF_VERIFY is not set


```

**Comment by figue** [comment]
Unfortunately I've never used rEFInd. I'm a syslinux user for years... In any case, if Arch kernel boots, Xanmod should do it too.

Can you try to build Xanmod with Arch's config? You can do it [downloading arch's config](https://git.archlinux.org/svntogit/packages.git/plain/trunk/config?h=packages/linux&id=98b02955df4cb5e4205f8f3efac0399c3c3a3045), then renaming and copying as "myconfig" file in compilation path. Then launch makepkg.

**Comment by xuanruiqi** [comment]
Closing because not a Xanmod issue. I used a new config based on running kernel config and I was able to boot. I can't see which kernel option is missing here but it worked...
