### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by paulmootrey** [xanmod/linux#88]
Anyone else receiving this? Possibly a misconfigured kernel on my end?

[   42.226477] thermal thermal_zone9: failed to read out thermal zone (-61)
[   42.226849] ------------[ cut here ]------------
[   42.227825] WARNING: CPU: 9 PID: 1393 at nl80211_get_reg_do+0x1ec/0x220 [cfg80211]
[   42.228411] Modules linked in: bnep btusb iwlmvm btrtl btbcm btintel mac80211 bluetooth iwlwifi dell_laptop cfg80211 rfkill
[   42.228975] CPU: 9 PID: 1393 Comm: iwd Tainted: G     U            5.8.11-xanmod1-x86_64 #1
[   42.229561] Hardware name: Dell Inc. XPS 13 7390/0377MH, BIOS 1.6.0 07/07/2020
[   42.230346] RIP: 0010:nl80211_get_reg_do+0x1ec/0x220 [cfg80211]
[   42.230985] Code: 24 0c 01 00 00 00 e8 e3 37 ed f8 85 c0 0f 84 01 ff ff ff eb a6 48 89 ef 48 89 04 24 e8 dd 39 4f f9 48 8b 04 24 e9 43 ff ff ff <0f> 0b 48 89 ef e8 ca 39 4f f9 b8 ea ff ff ff e9 2f ff ff ff e9 78
[   42.231592] RSP: 0018:ffffab7080727c00 EFLAGS: 00010202
[   42.232214] RAX: 0000000000000000 RBX: 0000000000000001 RCX: 0000000000000000
[   42.232920] RDX: ffff9def34224008 RSI: 0000000000000000 RDI: ffff9def342242e0
[   42.233548] RBP: ffff9def361f4300 R08: 0000000000000004 R09: ffff9def39975014
[   42.234383] R10: 0000000000000016 R11: ffff9deef8d27bd8 R12: ffffab7080727c58
[   42.235059] R13: 0000000000000000 R14: ffff9def39975014 R15: ffff9def342242e0
[   42.235701] FS:  00007f41e68da740(0000) GS:ffff9def3e680000(0000) knlGS:0000000000000000
[   42.236350] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   42.237046] CR2: 00007f41e68666ca CR3: 00000004364b8006 CR4: 00000000003706e0
[   42.237681] Call Trace:
[   42.238316]  ? _cond_resched+0x11/0x40
[   42.238957]  genl_rcv_msg+0x198/0x2e0
[   42.239622]  ? genl_family_rcv_msg_attrs_parse.isra.0+0xd0/0xd0
[   42.240283]  netlink_rcv_skb+0x42/0x100
[   42.241000]  genl_rcv+0x1f/0x30
[   42.241637]  netlink_unicast+0x21c/0x320
[   42.242269]  netlink_sendmsg+0x23d/0x470
[   42.242905]  __sys_sendto+0x1a4/0x1c0
[   42.243532]  ? syscall_trace_enter+0x182/0x220
[   42.244380]  __x64_sys_sendto+0x20/0x30
[   42.245058]  do_syscall_64+0x3f/0x130
[   42.245685]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   42.246325] RIP: 0033:0x7f41e69dda7c
[   42.246966] Code: 89 02 48 c7 c0 ff ff ff ff eb b8 0f 1f 00 41 89 ca 64 8b 04 25 18 00 00 00 85 c0 75 19 45 31 c9 45 31 c0 b8 2c 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 64 c3 0f 1f 00 55 48 83 ec 20 48 89 54 24 10
[   42.247646] RSP: 002b:00007ffe05e19558 EFLAGS: 00000246 ORIG_RAX: 000000000000002c
[   42.248333] RAX: ffffffffffffffda RBX: 0000557cb0f21890 RCX: 00007f41e69dda7c
[   42.249028] RDX: 000000000000001c RSI: 0000557cb0f36360 RDI: 0000000000000004
[   42.249717] RBP: 0000557cb0f219e0 R08: 0000000000000000 R09: 0000000000000000
[   42.250403] R10: 0000000000000000 R11: 0000000000000246 R12: 0000557cb0f36fc0
[   42.251091] R13: 00007ffe05e195f0 R14: 0000000000000001 R15: 0000000000000000
[   42.251771] ---[ end trace a980a17e84acfb79 ]---

**Comment by xanmod** [comment]
Persists w/ 5.8.12-xanmod1?
