### ISSUE TITLE
xanmod-5.8.13 fails to compile with cachy.

### ISSUE THREAD

**Issue by hedmo** [xanmod/linux#89]
Hi. 

xanmod-5.8.13 fails to compile with this error : 

`kernel/sched/cachy.c: In function ‘check_preempt_tick’:
kernel/sched/cachy.c:4179:6: error: implicit declaration of function ‘pick_next_entity’; did you mean ‘list_next_entry’? [-Werror=implicit-function-declaration]
 4179 |  if (pick_next_entity(cfs_rq, curr) != curr)
      |      ^~~~~~~~~~~~~~~~
      |      list_next_entry
kernel/sched/cachy.c:4179:37: warning: comparison between pointer and integer
 4179 |  if (pick_next_entity(cfs_rq, curr) != curr)
      |                                     ^~
kernel/sched/cachy.c: At top level:
kernel/sched/cachy.c:4239:1: error: conflicting types for ‘pick_next_entity’
 4239 | pick_next_entity(struct cfs_rq *cfs_rq, struct sched_entity *curr)
      | ^~~~~~~~~~~~~~~~
kernel/sched/cachy.c:4179:6: note: previous implicit declaration of ‘pick_next_entity’ was here
 4179 |  if (pick_next_entity(cfs_rq, curr) != curr)
      |      ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:280: kernel/sched/cachy.o] Error 1
make[1]: *** [scripts/Makefile.build:497: kernel/sched] Error 2
make[1]: *** Waiting for unfinished jobs....`

regard hedmo

**Comment by figue** [comment]
Same here

**Comment by hamadmarri** [comment]
Sorry it was my mistake not updating the tag on cachy repo. The commit should be merge is this one https://github.com/hamadmarri/linux/commit/f213f168be8914f80cf8e6acafc97a80edbf2bfb 
I fixed some missing prototypes and kconfig

Please see the attached fix patch, apply on top of the current patch
[cachy5.8.pick.zip](https://github.com/xanmod/linux/files/5323006/cachy5.8.pick.zip)

**Comment by figue** [comment]
thanks @hamadmarri no problem

**Comment by hedmo** [comment]
@hamadmarri thanks for the fast fix.
regards hedmo
