### ISSUE TITLE
Anbox installation fails

### ISSUE THREAD

**Issue by idnovic** [xanmod/linux#9]
I am not able to build anbox (dkms module) with the xanmod kernel 4.15.5-xanmod6.
I am using Ubuntu 17.10.

`cat /var/lib/dkms/anbox-modules-binder/9/build/make.log
DKMS make.log for anbox-modules-binder-9 for 
kernel 4.15.5-xanmod6 (x86_64)
Sa 24. Feb 06:13:29 CET 2018
make -C /lib/modules/4.15.5-xanmod6/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-4.15.5-xanmod6'
Makefile:933: *** "Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-4.15.5-xanmod6'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
`

libelf-dev is installed.  I think something different is the problem. Can you try it out?

**Comment by idnovic** [comment]
https://github.com/anbox/anbox

**Comment by xanmod** [comment]
Worked with previous versions? See with the anbox developers about Oops Rewind Capability Unwinder support.

**Comment by idnovic** [comment]
first time I tried it.
If it is not too much to ask, could you please try yourself just to check if it is a problem with xanmod + anbox?

**Comment by idnovic** [comment]
https://github.com/anbox/anbox/issues/621

**Comment by xanmod** [comment]
Failed here also to build the dkms module (GCC 7.3).
Try this version (w/ frampointer instead of orc):
[http://deb.xanmod.org/experimental/4.14.9-xanmod13_framepointer/](http://deb.xanmod.org/experimental/4.14.9-xanmod13_framepointer/)

**Comment by idnovic** [comment]
builds with your suggested kernel. I need to test anbox further.
I do not know what the framepointer is, can you change xanmod 4.15.X to support anbox too?

Offtopic, do you recommend schedutil or pstate? (i3 baytrail)

**Comment by idnovic** [comment]
going back to 4.15 - thanks for your help but anbox is buggy, very buggy.

**Comment by xanmod** [comment]
Linux > 4.12 have new pstate revision (powersave) has more performance than cpufreq schedutil.
