### ISSUE TITLE
xanmod-lts not loading zfs modules on boot (sounds like a problem in the initramfs creation???)

### ISSUE THREAD

**Issue by timotheosh** [xanmod/linux#90]
How to replicate:
Install Ubuntu 20.04 desktop with experimental ZFS enabled.
Update system after first reboot
`sudo apt update && sudo apt -y dist-upgrade`
Add Xanmod repo
`echo 'deb http://deb.xanmod.org releases main' | sudo tee /etc/apt/sources.list.d/xanmod-kernel.list && wget -qO - https://dl.xanmod.org/gpg.key | sudo apt-key add -`
Install xanmod
`sudo apt install linux-xanmod-lts`
Update system (get new zfs utils from zanmod and recreates initramfs)
`sudo apt update && sudo apt -y dist-upgrade`
reboot
System dumps into initram with the message it was unable to load zfs modules, please load by hand

**Comment by xanmod** [comment]
It's not a issue related to the kernel, see if the new version of zfsutils-linux solves.

**Comment by AlexandrosAlpha** [comment]
Hello and i'm sorry if there is already a solution that i didn't notice, but is it possible to install Ubuntu ZFS and change to Xanmod Kernel. I would love to enjoy the benefits of ZFS filesystem while using the exceptional Xanmod Kernel. Thank you in advance!

**Comment by timkofu** [comment]
Hi, just ran into this issue as well with Xanmod-stable on Ubuntu 22.04.
