### ISSUE TITLE
linux-tools-xanmod package

### ISSUE THREAD

**Issue by lilianmoraru** [xanmod/linux#94]
`Xanmod` currently offers the Linux Kernel(modules, etc) + Linux headers(good for `dkms`) but no Linux Tools package.
Could we please get a `linux-tools-xanmod` package to install at least the `perf` tool that was compiled against that version of the kernel?:
`make ... -C tools/ perf_install`

**Comment by xanmod** [comment]
Yes, I can provide. Thanks for the sugestion @lilianmoraru.

**Comment by xanmod** [comment]
See if everything is ok: `sudo apt install linux-tools-xanmod`

**Comment by lilianmoraru** [comment]
Yey, it works :)
Thank you!

![image](https://user-images.githubusercontent.com/621738/98023822-2096dd00-1e10-11eb-9bba-6bd41d662030.png)

Note though that installing `linux-xanmod` and `linux-tools-xanmod`, can install unmatching `linux-tools` version.

**Comment by Natalcia** [comment]
``` 
nat@probook ~ $ cpupower
WARNING: cpupower not found for kernel 5.9.8

  You may need to install the following packages for this specific kernel:
    linux-tools-5.9.8-xanmod1
    linux-cloud-tools-5.9.8-xanmod1

  You may also want to install one of the following packages to keep up to date:
    linux-tools-xanmod1
    linux-cloud-tools-xanmod1
```
:/

**Comment by lilianmoraru** [comment]
@Natalcia it contains only `perf`

**Comment by gabriel3l** [comment]
@lilianmoraru Can we get a package for installing cpupower? I am looking for it and I believe it's something that may interest others as well

**Comment by gabriel3l** [comment]
@xanmod Can we also please have a package for installing cpupower? I am looking for it and I believe it's something that may interest others as well

**Comment by devopsec** [comment]
Doesn't look like the `linux-tools-xanmod` is being updated as new versions of `linux-xanmod` have come out:

```
[1]|anon@devbox ~|$ sudo apt install linux-tools-xanmod 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libgamemode0 libgamemodeauto0
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  linux-tools-5.9.2-xanmod1
The following NEW packages will be installed:
  linux-tools-5.9.2-xanmod1 linux-tools-xanmod
0 upgraded, 2 newly installed, 0 to remove and 2 not upgraded.
Need to get 5,640 kB of archives.
After this operation, 26.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.xanmod.org releases/main amd64 linux-tools-5.9.2-xanmod1 amd64 5.9.2-xanmod1-0~git20201031.209cae6 [5,639 kB]
Get:2 http://deb.xanmod.org releases/main amd64 linux-tools-xanmod amd64 5.9.2-xanmod1-0 [848 B]                                                                                         
Fetched 5,640 kB in 14s (399 kB/s)                                                                                                                                                       
Selecting previously unselected package linux-tools-5.9.2-xanmod1.
(Reading database ... 650091 files and directories currently installed.)
Preparing to unpack .../linux-tools-5.9.2-xanmod1_5.9.2-xanmod1-0~git20201031.209cae6_amd64.deb ...
Unpacking linux-tools-5.9.2-xanmod1 (5.9.2-xanmod1-0~git20201031.209cae6) ...
Replacing files in old package linux-tools-common (5.4.0-54.60) ...
Selecting previously unselected package linux-tools-xanmod.
Preparing to unpack .../linux-tools-xanmod_5.9.2-xanmod1-0_amd64.deb ...
Unpacking linux-tools-xanmod (5.9.2-xanmod1-0) ...
Setting up linux-tools-5.9.2-xanmod1 (5.9.2-xanmod1-0~git20201031.209cae6) ...
Setting up linux-tools-xanmod (5.9.2-xanmod1-0) ...
Processing triggers for man-db (2.9.1-1) ...
[1]|anon@devbox ~|$ uname -r
5.9.11-xanmod1
[1]|anon@devbox ~|$ dpkg -l | grep linux-xanmod
ii  linux-xanmod                                                5.9.11-xanmod1-0                                                            amd64        Complete XanMod Linux kernel and headers (STABLE) (v5.9)
```

Perf seems to find the old kernel tools and be fine with it but it looks like bpftool is more picky:

```
[1]|anon@devbox ~|$ bpftool 
WARNING: bpftool not found for kernel 5.9.11

  You may need to install the following packages for this specific kernel:
    linux-tools-5.9.11-xanmod1
    linux-cloud-tools-5.9.11-xanmod1

  You may also want to install one of the following packages to keep up to date:
    linux-tools-xanmod1
    linux-cloud-tools-xanmod1
```

And to re-iterate `linux-tools-5.9.11-xanmod1` is not available from the repos (atleast under ubuntu 20.04 )

**Comment by devopsec** [comment]
To piggyback on my last question how would I compile the tools from the linux-xanmod headers?  
When I look in the usual location for the tools I don't see them:

```
[1]|anon@devbox ~|$ ls -l /usr/src/linux-headers-$(uname -r)/tools/
total 4
drwxr-xr-x 2 root root 4096 Nov 27 13:22 objtool
```

This is with `linux-headers-5.9.11-xanmod1` installed on ubuntu 20.04

**Comment by duplexsystem** [comment]
This is still an issue

**Comment by Lortegap** [comment]
sudo install linux-tools-xanmod
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-tools-xanmod

**Comment by nazar-pc** [comment]
@xanmod is it much work to get linux-tools-xanmod going again? I'm on linux-xanmod-edge and just noticed too that perf isn't working, which is very unfortunate.

**Comment by sonicdebris** [comment]
I would also need to use `cpupower` with xanmod RT edge. :pray:

**Comment by teepean** [comment]
I would also like to see linux-tools for xanmod. I need perf I tried compiling it  but get several errors.

`In file included from bench/futex-hash.c:28:
bench/futex.h:129:50: warning: ‘struct futex_requeue’ declared inside parameter list will not be visible outside of this definition or declaration
  129 | static inline int futex2_requeue(volatile struct futex_requeue *uaddr1,
      |                                                  ^~~~~~~~~~~~~
bench/futex-hash.c: In function ‘__bench_futex_hash’:
bench/futex-hash.c:155:16: error: ‘FUTEX_32’ undeclared (first use in this function); did you mean ‘FUTEX_OP’?
  155 |   futex_flag = FUTEX_32 | (fshared * FUTEX_SHARED_FLAG);
      |                ^~~~~~~~
      |                FUTEX_OP
bench/futex-hash.c:155:16: note: each undeclared identifier is reported only once for each function it appears in
bench/futex-hash.c:155:38: error: ‘FUTEX_SHARED_FLAG’ undeclared (first use in this function); did you mean ‘FUTEX_PRIVATE_FLAG’?
  155 |   futex_flag = FUTEX_32 | (fshared * FUTEX_SHARED_FLAG);
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      FUTEX_PRIVATE_FLAG
`

**Comment by viig99** [comment]
Any instructions on how to compile and install the tools package ?

**Comment by johnblommers** [comment]
As of kernel 5.18.8-xanmod1 we still cannot run `perf` for example:

```bash
sudo perf stat -e sched:sched_switch --timeout 1000

WARNING: perf not found for kernel 5.18.8-xanmod1

  You may need to install the following packages for this specific kernel:
    linux-tools-5.18.8-xanmod1-x64v2
    linux-cloud-tools-5.18.8-xanmod1-x64v2

  You may also want to install one of the following packages to keep up to date:
    linux-tools-x64v2
    linux-cloud-tools-x64v2
```

None of the packages mentioned above are available so we cannot run `perf`. I'd be happy to know how to build the required packages and build them myself. But how?

The same problem with `perf` repeats for `cpupower`.
