### ISSUE TITLE
futex2 

### ISSUE THREAD

**Issue by SicLuceatLux** [xanmod/linux#96]
Hi,

have you tried to implement futex2 ?
I tried to apply the patches of 
https://lore.kernel.org/lkml/20200612185122.327860-2-andrealmeid@collabora.com/
from
https://gitlab.collabora.com/tonyk/linux/-/commits/futex2

on 5.9-rt16-xanmod2 but it is not straight forward compatible because there is already some additional futex patch applied ? Seems to break it.

Is there any roadmap of implementing futuex2?

**Comment by xanmod** [comment]
The patch is still in development, when developers consider it stable, it will be merged in xanmod. Probably just before the release of the Linux 5.10.

**Comment by SicLuceatLux** [comment]
Thankyou for your fast answer
