### ISSUE TITLE
 linux/tools/testing/selftests/powerpc/copyloops/memcpy_mcsafe_64.S invalid symlink

### ISSUE THREAD

**Issue by brokendreams1981** [xanmod/linux#97]
linux/tools/testing/selftests/powerpc/copyloops/memcpy_mcsafe_64.S is symlinked to arch/powerpc/lib/memcpy_mcsafe_64.S which no longer exists. i believe it was renamed to arch/powerpc/lib/copy_mc_64.S per this commit (if im reading it correctly).

https://github.com/xanmod/linux/commit/a85748ed9eb70108f9605558f2754ca94ee91401

this only effect 5.9.3 and future releases

**Comment by xanmod** [comment]
@djbw

**Comment by xanmod** [comment]
v5.9.4 fix commit: https://github.com/xanmod/linux/commit/5fec7e5a28627138223aa20f5ff484898955ff77
