### ISSUE TITLE
Cachy by default?

### ISSUE THREAD

**Issue by Vistaus** [xanmod/linux#98]
I've been running the 5.8.14-cachy Xanmod kernel for a while now and it's been running absolutely fantastic. But I read somewhere that Cachy is included and running by default now in the Edge kernel. Is that true?

**Comment by xanmod** [comment]
No, it's enabled on the cachy branch (linux-xanmod-cachy).

**Comment by Vistaus** [comment]
So just on the branch that I was already using. Thanks for the answer :) In that case, I'll just wait for a new deb package of xanmod-cachy to appear.
