### ISSUE TITLE
[FEATURE] RPM packages for other linux distributions.

### ISSUE THREAD

**Issue by ionutnechita** [xanmod/linux#99]
Hi Alexandre Frade,

I noticed that the default support is for Debian/Ubuntu distributions.
Do you plan to expand it to other distributions that use RPM packages?
Currently, I use OpenSUSE Tumbleweed, and I would have liked to install this kernel directly on my machine.
Can you help me in this regard?

Thanks for everything.
I like what you do, good luck.

**Comment by xanmod** [comment]
There are support plans for rpm systems as well. Probably until Jan/21 there will already be a repository available.

**Comment by ionutnechita** [comment]
Ok. Thanks.

**Comment by Vistaus** [comment]
Any update on this?

**Comment by Vistaus** [comment]
Anything? I don't even understand why this is closed...

**Comment by Vistaus** [comment]
Still miss Xanmod on my openSUSE. :(

**Comment by Vistaus** [comment]
I guess it will never see the light of day. Sad…
